### PR TITLE
Update IntelliJ paths

### PR DESCRIPTION
**Pull request by madrob**
I'm not sure if this change has other unintended side effects, but I needed it for my Structure101 plugin to work.

### CODE REVIEW

**Comment by dweiss** [comment]
No, please keep these folders separate. If you overlap intellij and gradle outputs things start to look really weird when you're running from the IDE and from command-line at the same time.

**Comment by dweiss** [comment]
In other words - this is an intentional configuration to separate output folders, not an oversight of some sort.

**Comment by madrob** [comment]
I imagined this was intentional, but didn't quite understand why. I suspect this was working around a bug in an older IntelliJ, maybe.

For my particular install, IntelliJ builds don't even generate these directories, so it's hard to guess the intent behind them.

**Comment by dweiss** [comment]
It depends how you run intellij. Gradle settings window will give you options to compile/run with intellij or via gradle - the default seems to be gradle these days. I prefer IntelliJ's compiler (faster and more reliable). Overlapping output folders cause headaches especially on Windows where two concurrent tools lock files, etc. 

If you really want this you could make it configurable (with the default separating builds) - a conditional on propertyOrDefault("ide.intellij.separateFolders", "true") and then override this setting locally (and document in help/ides.txt).

**Comment by madrob** [comment]
Makes sense. I decided that the Structure101 plugin wasn't worth it anyway, because it was having issues linking the byte code to the source code so lost a lot of power that way. Instead of changing the paths, I'll document more about the logic, hopefully somebody in the future will save themselves some time.

**Pull request merged**
