### PR TITLE
SOLR-15362: allow drop down box to float wider to support long core/collection names

### PR DESCRIPTION
**Pull request by epugh**
# Description

Long collection and core names, especially ones that have similar/same prefix, are hard to tell which is which in the Solr admin.

# Solution

Tweaking some CSS.

# Tests

Manual testing

# Checklist

Please review the following and check all that apply:

- [X ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ X] I have created a Jira issue and added the issue ID to my pull request title.
- [ X] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [X ] I have developed this patch against the `main` branch.
- [ X] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by HoustonPutman** [comment]
> This file is generated by `grunt build`, do not edit it by hand.

I assume this isn't really the case anymore?

**Comment by epugh** [comment]
> > This file is generated by `grunt build`, do not edit it by hand.
> 
> I assume this isn't really the case anymore?

this is another "deprecated we don't support it" Angular1 project..   So I wouldn't expect any updates...    On the other hand, maybe this setting should go in another file?   I'm not a CSS person, so not sure how to add that property to another CSS file and leave this one alone....

**Comment by epugh** [comment]
I tried to add the css to `common.css` to see what that did, and leave `chosen.css` alone, but it didn't seem to work.

**Comment by HoustonPutman** [comment]
Yeah, it was probably auto-generated, then copied into the project. Should be fine...

**Comment by epugh** [comment]
I am going to leave this PR open for a few days, to see if the original reporter wants to also try and do something with smart CSS to make the collection/core names in the "admin pane" maybe highlight nicely when you mouse over them or something.  If we get that great, otherwise I'll just merge this fix as it's already a helpful change.   (why didn't we do this 5 years ago!)

**Comment by madrob** [comment]
@epugh Do you want to merge this?

**Comment by epugh** [comment]
> @epugh Do you want to merge this?

Thanks for the ping.   I'll go ahead and do one more look and then merge it.

**Pull request merged**
