### PR TITLE
Update dependencies com.adobe.testing:s3mock-junit4 to v2.11.0, org.springframework.boot:spring-boot to 2.7.10, org.springframework:spring to 5.3.26, and software.amazon.awssdk to 2.19.1

### PR DESCRIPTION
**Pull request by solrbot**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [com.adobe.testing:s3mock-junit4](https://togithub.com/adobe/S3Mock) | test | minor | `2.1.34` -> `2.11.0` |

---

### Release Notes

<details>
<summary>adobe/S3Mock</summary>

### [`v2.11.0`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2110)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.10.2...2.11.0)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Support for GetBucketLocation API (fixes [#&#8203;985](https://togithub.com/adobe/S3Mock/issues/985))
-   Version updates
    -   Bump aws-java-sdk-s3 from 1.12.346 to 1.12.369
    -   Bump aws-v2.version from 2.18.21 to 2.19.1
    -   Bump docker-maven-plugin from 0.40.2 to 0.40.3
    -   Bump maven-dependency-plugin from 3.3.0 to 3.4.0
    -   Bump mockito-kotlin from 4.0.0 to 4.1.0
    -   Bump checkstyle from 10.4 to 10.5.0
    -   Bump kotlin.version from 1.7.21 to 1.7.22
    -   Bump alpine from 3.16.3 to 3.17.0 in /docker
    -   Bump spring-boot.version from 2.7.5 to 2.7.6

### [`v2.10.2`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2102)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.10.1...2.10.2)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Let S3Mock return correct errors for invalid bucket names (fixes [#&#8203;935](https://togithub.com/adobe/S3Mock/issues/935))
        -   Previous implementation returned a Spring generated error which does not disclose what's actually wrong
        -   If the bucket name is not valid, the bucket can't be created. If a later request still contains this invalid name, S3Mock will now return a 404 not found.

### [`v2.10.1`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2101)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.10.0...2.10.1)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Let S3Mock use streams for MD5 verification (fixes [#&#8203;939](https://togithub.com/adobe/S3Mock/issues/939))
        -   Previous implementation read the full stream into memory, leading to OutOfMemory errors if the file is larger than the available heap.

### [`v2.10.0`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2100)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.9.1...2.10.0)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Let S3Mock use container memory and cpu (fixes [#&#8203;922](https://togithub.com/adobe/S3Mock/issues/922))
        -   Set resource limits through docker like this: `docker run -it --memory="1g" --cpus="1.0"`
-   Version updates
    -   Bump alpine from 3.16.2 to 3.16.3 in /docker
    -   Bump testcontainers.version from 1.17.5 to 1.17.6
    -   Bump maven-install-plugin from 3.0.1 to 3.1.0
    -   Bump aws-v2.version from 2.18.15 to 2.18.21
    -   Bump aws-java-sdk-s3 from 1.12.340 to 1.12.346

### [`v2.9.1`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;291)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.9.0...2.9.1)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   IDs in stores must be different for all objects (fixes [#&#8203;877](https://togithub.com/adobe/S3Mock/issues/877))

### [`v2.9.0`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;290)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.8.0...2.9.0)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Support restarting S3Mock with the `retainFilesOnExit` option enabled. (fixes [#&#8203;818](https://togithub.com/adobe/S3Mock/issues/818), [#&#8203;877](https://togithub.com/adobe/S3Mock/issues/877))
    -   Let AWS SDKv2 use path style access (fixes [#&#8203;880](https://togithub.com/adobe/S3Mock/issues/880))
        -   Starting with AWS SDKv2.18.x domain style access is the default. This is currently not
            supported by S3Mock.
-   Version updates
    -   Bump aws-v2.version from 2.17.284 to 2.18.15
    -   Bump aws-java-sdk-s3 from 1.12.313 to 1.12.340
    -   Bump kotlin.version from 1.7.20 to 1.7.21
    -   Bump maven-release-plugin from 3.0.0-M6 to 3.0.0-M7
    -   Bump checkstyle from 10.3.4 to 10.4
    -   Bump spring-boot.version from 2.7.4 to 2.7.5
    -   Bump testcontainers.version from 1.17.4 to 1.17.5

### [`v2.8.0`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;280)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.7.2...2.8.0)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Add support for BucketLifecycleConfiguration APIs (fixes [#&#8203;291](https://togithub.com/adobe/S3Mock/issues/291))
        -   Implement GetBucketLifecycleConfiguration / PutBucketLifecycleConfiguration / DeleteLifecycleConfiguration
        -   S3Mock currently does not enforce the lifecycle configuration.
-   Version updates
    -   Bump aws-java-sdk-s3 from 1.12.309 to 1.12.312
    -   Bump aws-v2.version from 2.17.281 to 2.17.284
    -   Bump kotlin.version from 1.7.10 to 1.7.20
    -   Bump checkstyle from 10.3.3 to 10.3.4
    -   Bump testcontainers.version from 1.17.3 to 1.17.4

### [`v2.7.2`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;272)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.7.1...2.7.2)

Accidentally released 2.7.2 instead of 2.8.0 - please ignore :(

### [`v2.7.1`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;271)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.7.0...2.7.1)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Avoid root folder temporary directory race condition (fixes [#&#8203;837](https://togithub.com/adobe/S3Mock/issues/837))
        -   Thanks to [@&#8203;ginkel](https://togithub.com/ginkel) for the fix!

### [`v2.7.0`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;270)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.6.3...2.7.0)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Add support for ACL APIs (fixes [#&#8203;213](https://togithub.com/adobe/S3Mock/issues/213) / [#&#8203;290](https://togithub.com/adobe/S3Mock/issues/290))
        -   Implement GetObjectACL / PutObjectACL
        -   Return / accept String instead of a POJO. We need to use JAX-B annotations instead of Jackson annotations
            because AWS decided to use xsi:type annotations in the XML representation, which are not supported
            by Jackson. It doesn't seem to be possible to use bot JAX-B and Jackson for (de-)serialization in parallel.
-   Version updates
    -   Bump aws-java-sdk-s3 from 1.12.298 to 1.12.309
    -   Bump aws-v2.version from 2.17.269 to 2.17.281
    -   Bump spring-boot.version from 2.7.3 to 2.7.4
    -   Bump maven-jar-plugin from 3.2.2 to 3.3.0

### [`v2.6.3`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;263)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.6.2...2.6.3)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Handle all incoming and outgoing ETags according to RFC2616 / RFC7232 (fixes [#&#8203;807](https://togithub.com/adobe/S3Mock/issues/807))
        -   Fixes ETag handling in GetObject, HeadObject, CopyObject, UploadPartCopy APIs.
        -   We are now generating and storing ETags in the "RFC-Format" with enclosing double quotes.
        -   Incoming ETags are used verbatim to compare against the internally held representation.
        -   Wildcard ETags are also correctly handled.

### [`v2.6.2`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;262)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.6.1...2.6.2)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   LastModified must be updated when copying an object onto itself (fixes [#&#8203;811](https://togithub.com/adobe/S3Mock/issues/811))
-   Refactorings
    -   Split up integration tests by type

### [`v2.6.1`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;261)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.6.0...2.6.1)

2.x is JDK8 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   ETags in requests and responses must comply to RFC-2616 (fixes [#&#8203;801](https://togithub.com/adobe/S3Mock/issues/801))
        -   Fixes `ListObjects` and `ListObjectsV2` APIs.
        -   Whenever S3Mock uses Serialization / Deserialization with Jackson, we  must use our custom
            EtagSerializer / EtagDeserializer that wraps and unwraps the etag for the DTO.
-   Version updates
    -   Bump aws-v2.version from 2.17.267 to 2.17.269
    -   Bump aws-java-sdk-s3 from 1.12.296 to 1.12.298

### [`v2.6.0`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;260)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.5.4...2.6.0)

-   Features and fixes
    -   Add support for LegalHold APIs (fixes [#&#8203;157](https://togithub.com/adobe/S3Mock/issues/157))
        -   Implement GetObjectLegalHold / PutObjectLegalHold
        -   Implement GetObjectLockConfiguration / PutObjectLockConfiguration
        -   In S3, object locking can only be activated for versioned buckets, versions are currently not supported by S3Mock.
            S3 enforces LegalHold only for versions, so S3Mock currently can't enforce the legal hold.
    -   Add support for Retention APIs
        -   Implement GetObjectRetention / PutObjectRetention
        -   In S3, object locking can only be activated for versioned buckets, versions are currently not supported by S3Mock.
            S3 enforces retention only for versions, so S3Mock currently can't enforce the retention.
-   Refactorings
    -   Added support for IntegrationTests to use a dedicated bucket per test method
        -   Refactored some IntegrationTests to this pattern.
    -   Use AWS SDK internal Utils for instants and encoding
        -   Using `software.amazon.awssdk.utils.DateUtils` and `software.amazon.awssdk.utils.http.SdkHttpUtils`
        -   These classes are marked as `software.amazon.awssdk.annotations.SdkProtectedApi`
            which means that SDK users (liek S3Mock) should not use these classes, but S3Mock has to exactly match the
            behaviour and expectations of the AWS SDKs, and it's easier to depend on internal AWS SDK classes
            instead of replicating or copying the code.
        -   S3Mock may have violated the AWS SDK license before by including source code without explicitly
            stating that it's AWS copyrighted code. (In the JavaDoc it did say that this is a copy with
            a reference to the class, though)
-   Version updates
    -   Bump aws-v2.version from 2.17.263 to 2.17.267
    -   Bump aws-java-sdk-s3 from 1.12.292 to 1.12.296

### [`v2.5.4`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;254)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.5.3...2.5.4)

-   Features and fixes
    -   Rename local storage files, add file system structure documentation to README.md (fixes [#&#8203;220](https://togithub.com/adobe/S3Mock/issues/220))
    -   `@Configuration` / `@ConfigurationProperties` classes now public to enable customers to use `@Import` / `@ContextConfiguration` on them. (fixes [#&#8203;751](https://togithub.com/adobe/S3Mock/issues/751))

### [`v2.5.3`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;253)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.5.2...2.5.3)

-   Features and fixes
    -   Remove [Spring Component Index](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-scanning-index) from S3Mock (fixes [#&#8203;786](https://togithub.com/adobe/S3Mock/issues/786))
        -   Adding a Spring Component Index file is a breaking change for all clients of the s3mock.jar
        -   If Spring finds even one Component Index file in the classpath, all other configuration in the application
            is completely ignored by default.

### [`v2.5.2`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;252)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.5.1...2.5.2)

-   Features and fixes
    -   Correctly detect and use existing root folder (fixes [#&#8203;786](https://togithub.com/adobe/S3Mock/issues/786))

### [`v2.5.1`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;251)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.5.0...2.5.1)

-   Features and fixes
    -   Use `@SpringBootApplication` to configure S3Mock (fixes [#&#8203;782](https://togithub.com/adobe/S3Mock/issues/782))

### [`v2.5.0`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;250)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.16...2.5.0)

-   Features and fixes
    -   Add [Spring Component Index](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-scanning-index) to S3Mock (fixes [#&#8203;751](https://togithub.com/adobe/S3Mock/issues/751))
    -   Bucket lifecycle
        -   S3Mock now validates incoming Bucket names.
            -   S3 SDKs (for Java) validated the names before sending, so this should not matter for most use-cases.
        -   S3Mock now throws errors on duplicate creation (409 Conflict) / deletion (404 Not Found)
            -   These errors are defined in the S3 API, the S3Mock just never implemented them.
    -   DTOs
        -   Fix names, methods, return values to match AWS API
        -   Remove internal field "path" from `Bucket` serializations. Fortunately this did not break AWS SDKs in the past, since the "path" field is not expected in those responses.
    -   Various other fixes like
        -   Removal of duplicated / simplification of code where possible
        -   Add (hopefully useful?) logging with all incoming parameters on errors.
        -   Fix IntelliJ IDEA warnings
        -   Better assertions in tests
        -   Fix various JavaDoc issues, add links to S3 API where possible
-   Refactorings
    -   Major refactoring towards smaller classes with well-defined responsibilities.
        -   Many of the existing lines of code in the S3Mock core were changed, moved or removed.
        -   All IntegrationTests were/are still green, HTTP API did not change (other than fixed listed above)
    -   Refactor into layers `Controller -> Service -> Store`
        -   Controllers handle request/response only, Services implement higher level functionality on top of their stores, Stores read and write data from/to disk.
        -   Handle Multipart requests in `MultipartController` -> `MultipartService` -> `MultipartStore`
        -   Handle Bucket requests in `BucketController` -> `BucketService` -> `BucketStore`
        -   Handle Object requests in `ObjectController` -> `ObjectService` -> `ObjectStore`
        -   Code and documentation cleanup
        -   Let `BucketStore` store `BucketMetadata` just like `S3ObjectMetadata` locally. For now, only store the "core" metadata like creationDate and name.
        -   Store object keys in `BucketMetadata`, assign UUIDs (fixes [#&#8203;94](https://togithub.com/adobe/S3Mock/issues/94))
        -   Store objects in UUID folders, clean up name usage
    -   Extract header helper methods into `HeaderUtil` from `FileStoreController` / `ObjectController`.
-   Version updates
    -   Bump maven-javadoc-plugin from 3.4.0 to 3.4.1
    -   Bump aws-v2.version from 2.17.248 to 2.17.263
    -   Bump aws-java-sdk-s3 from 1.12.278 to 1.12.292
    -   Bump checkstyle from 10.3.2 to 10.3.3
    -   Bump maven-checkstyle-plugin from 3.1.2 to 3.2.0
    -   Bump spring-boot.version from 2.7.2 to 2.7.3

### [`v2.4.16`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2416)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.14...2.4.16)

-   Features and fixes
    -   Fix ListMultiPartUploads for Amazon SDK Java v2 (fixes [#&#8203;734](https://togithub.com/adobe/S3Mock/issues/734))
-   Refactorings
    -   Add [Maven Wrapper](https://maven.apache.org/wrapper) for reliable builds
    -   Add Spring Boot "devtools" for better local development
    -   Add "debug" profile that logs request output and enables JMX and all actuator endpoints
-   Version updates
    -   Bump aws-java-sdk-s3 from 1.12.267 to 1.12.278
    -   Bump aws-v2.version from 2.17.239 to 2.17.248
    -   Bump docker-maven-plugin from 0.40.1 to 0.40.2
    -   Bump alpine from 3.16.1 to 3.16.2 in /docker
    -   Bump checkstyle from 10.3.1 to 10.3.2

### [`v2.4.14`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2414)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.13...2.4.14)

-   Features and fixes
    -   Fix broken SSL handshake (fixes [#&#8203;706](https://togithub.com/adobe/S3Mock/issues/706))
    -   Fix KMS key handling (fixes [#&#8203;702](https://togithub.com/adobe/S3Mock/issues/702))
    -   Allow listing a MultiPartUpload with no parts (fixes [#&#8203;694](https://togithub.com/adobe/S3Mock/issues/694))
    -   Update SSL certificate with san=dns:localhost (fixes [#&#8203;228](https://togithub.com/adobe/S3Mock/issues/228))
-   Refactorings
    -   Add sortpom-maven-plugin, run sortpom
        -   To run manually, execute `mvn com.github.ekryd.sortpom:sortpom-maven-plugin:sort`
    -   Enable Kotlin compiler for integration-tests only.
-   Version updates
    -   Bump alpine from 3.16.0 to 3.16.1 in /docker
    -   Bump aws-java-sdk-s3 from 1.12.240 to 1.12.267
    -   Bump aws-v2.version from 2.17.211 to 2.17.239
    -   Bump spring-boot.version from 2.7.0 to 2.7.2
    -   Bump kotlin.version from 1.7.0 to 1.7.10
    -   Bump testng from 7.6.0 to 7.6.1
    -   Bump testcontainers.version from 1.17.2 to 1.17.3
    -   Bump checkstyle from 10.3 to 10.3.1
    -   Bump maven-deploy-plugin from 3.0.0-M2 to 3.0.0
    -   Bump docker-maven-plugin from 0.40.0 to 0.40.1
    -   Bump sortpom-maven-plugin from 3.1.3 to 3.2.0
    -   Bump maven-install-plugin from 3.0.0-M1 to 3.0.1
    -   Bump maven-resources-plugin from 3.2.0 to 3.3.0
    -   Bump exec-maven-plugin from 3.0.0 to 3.1.0

### [`v2.4.13`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2413)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.10...2.4.13)

-   Features and fixes
    -   Adds missing x-amz-server-side-encryption and x-amz-server-side-encryption-aws-kms-key-id header (fixes [#&#8203;639](https://togithub.com/adobe/S3Mock/issues/639))
-   Version updates
    -   Bump alpine from 3.15.4 to 3.16.0 in /docker
    -   Bump aws-java-sdk-s3 from 1.12.212 to 1.12.240
    -   Bump aws-v2.version from 2.17.182 to 2.17.211
    -   Bump spring-boot.version from 2.6.7 to 2.7.0
    -   Bump kotlin.version from 1.6.21 to 1.7.0
    -   Bump testng from 7.5 to 7.6.0
    -   Bump docker/setup-qemu-action from 1 to 2
    -   Bump checkstyle from 10.2 to 10.3
    -   Bump docker-maven-plugin from 0.39.1 to 0.40.0
    -   Bump maven-failsafe-plugin from 3.0.0-M6 to 3.0.0-M7
    -   Bump maven-surefire-plugin from 3.0.0-M6 to 3.0.0-M7
    -   Bump maven-release-plugin from 3.0.0-M5 to 3.0.0-M6
    -   Bump maven-enforcer-plugin from 3.0.0 to 3.1.0

### [`v2.4.10`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2410)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.9...2.4.10)

-   Features and fixes
    -   ListParts returns 404 on unknown upload id (fixes [#&#8203;475](https://togithub.com/adobe/S3Mock/issues/475))
    -   Allow CopyObject of key to same key in the same bucket (fixes [#&#8203;468](https://togithub.com/adobe/S3Mock/issues/468))
    -   Fix handling of userMetadata in CopyObject REPLACE and COPY cases (fixes [#&#8203;468](https://togithub.com/adobe/S3Mock/issues/468) again, fixes [#&#8203;569](https://togithub.com/adobe/S3Mock/issues/569))
    -   Add multipart tests for "small" last part (fixes [#&#8203;524](https://togithub.com/adobe/S3Mock/issues/524))
-   Refactorings
    -   Migrate integration tests to kotlin
-   Version updates
    -   Bump alpine from 3.15.0 to 3.15.4 in /docker
    -   Bump aws-java-sdk-s3 from 1.12.170 to 1.12.212
    -   Bump aws-v2.version from 2.17.141 to 2.17.182
    -   Bump spring-boot.version from 2.6.3 to 2.6.7
    -   Bump spring-security-oauth2 from 2.5.1.RELEASE to 2.5.2.RELEASE
    -   Bump testcontainers.version from 1.16.3 to 1.17.1
    -   Bump maven-surefire-plugin from 3.0.0-M5 to 3.0.0-M6
    -   Bump maven-failsafe-plugin from 3.0.0-M5 to 3.0.0-M6
    -   Bump maven-compiler-plugin from 3.10.0 to 3.10.1
    -   Bump maven-clean-plugin from 3.1.0 to 3.2.0
    -   Bump maven-dependency-plugin from 3.2.0 to 3.3.0
    -   Bump kotlin.version from 1.6.10 to 1.6.21
    -   Bump maven-javadoc-plugin from 3.3.2 to 3.4.0
    -   Bump checkstyle from 9.3 to 10.2

### [`v2.4.9`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;249)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.8...2.4.9)

-   Features and fixes
    -   Verify source key exists on CopyObject and CopyObjectPart (fixes [#&#8203;459](https://togithub.com/adobe/S3Mock/issues/459))
-   Refactorings
    -   Tagging does not have a "versionId" property in S3 API.
    -   CompleteMultipartUpload children are of type "CompletedPart".
    -   BatchDeleteResponse children are of type "DeletedObject".
    -   DeleteResult contains Error elements for failed deletes.
    -   Fixed JavaDoc of various classes and methods
    -   Add deprecation notice / documentation (fixes [#&#8203;418](https://togithub.com/adobe/S3Mock/issues/418))
    -   Remove unnecessary methods and constructors
    -   Rename classes to better match their counterpart in S3 API
    -   Convert Integration Test to Kotlin
-   Version updates
    -   Bump aws-java-sdk-s3 from 1.12.162 to 1.12.170
    -   Bump aws-v2.version from 2.17.133 to 2.17.141
    -   Bump docker-maven-plugin from 0.39.0 to 0.39.1

### [`v2.4.8`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;248)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.7...2.4.8)

-   Features and fixes
    -   Let S3Mock run with custom application.properties on classpath (fixes [#&#8203;434](https://togithub.com/adobe/S3Mock/issues/434))
    -   Change Docker image entrypoint to exec form (fixes [#&#8203;421](https://togithub.com/adobe/S3Mock/issues/421))
-   Version updates
    -   Bump aws-java-sdk-s3 from 1.12.150 to 1.12.162
    -   Bump aws-v2.version from 2.17.120 to 2.17.133
    -   Bump docker-maven-plugin from 0.38.1 to 0.39.0
    -   Bump maven-javadoc-plugin from 3.3.1 to 3.3.2
    -   Bump maven-compiler-plugin from 3.9.0 to 3.10.0

### [`v2.4.7`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;247)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.6...2.4.7)

-   Features and fixes
    -   getObjectTagging incorrectly returns JSON instead of XML (fixes [#&#8203;406](https://togithub.com/adobe/S3Mock/issues/406))

### [`v2.4.6`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;246)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.4.1...2.4.6)

-   Features and fixes
    -   Docker image is now available as multi arch for both `amd64` and `arm64` platforms. (fixes [#&#8203;253](https://togithub.com/adobe/S3Mock/issues/253), [#&#8203;287](https://togithub.com/adobe/S3Mock/issues/287), [#&#8203;313](https://togithub.com/adobe/S3Mock/issues/313), [#&#8203;389](https://togithub.com/adobe/S3Mock/issues/389))

### [`v2.4.1`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;2416)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.3.3...2.4.1)

-   Features and fixes
    -   Fix ListMultiPartUploads for Amazon SDK Java v2 (fixes [#&#8203;734](https://togithub.com/adobe/S3Mock/issues/734))
-   Refactorings
    -   Add [Maven Wrapper](https://maven.apache.org/wrapper) for reliable builds
    -   Add Spring Boot "devtools" for better local development
    -   Add "debug" profile that logs request output and enables JMX and all actuator endpoints
-   Version updates
    -   Bump aws-java-sdk-s3 from 1.12.267 to 1.12.278
    -   Bump aws-v2.version from 2.17.239 to 2.17.248
    -   Bump docker-maven-plugin from 0.40.1 to 0.40.2
    -   Bump alpine from 3.16.1 to 3.16.2 in /docker
    -   Bump checkstyle from 10.3.1 to 10.3.2

### [`v2.3.3`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;233)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.3.2...2.3.3)

-   Features and fixes
    -   Fix MultipartUpload without range (fixes [#&#8203;341](https://togithub.com/adobe/S3Mock/issues/341))
    -   Treat empty delimiter as `null` (fixes [#&#8203;306](https://togithub.com/adobe/S3Mock/issues/306))
    -   Fix -DskipDocker (fixes [#&#8203;344](https://togithub.com/adobe/S3Mock/issues/344))
-   Version updates
    -   Bump maven-deploy-plugin from 3.0.0-M1 to 3.0.0-M2
    -   Bump spring-boot.version from 2.6.1 to 2.6.2
    -   Bump aws-java-sdk-s3 from 1.12.130 to 1.12.131
    -   Bump checkstyle from 9.2 to 9.2.1

### [`v2.3.2`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;232)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.2.3...2.3.2)

-   Features and fixes
    -   Set only one CORS header (fixes [#&#8203;74](https://togithub.com/adobe/S3Mock/issues/74) - again)
    -   Add examples for validKmsKeys and initialBuckets configuration (fixes [#&#8203;322](https://togithub.com/adobe/S3Mock/issues/322))
-   Refactorings
    -   Using official Alpine Docker container with JDK17 from APK to run
        -   [alpine:3.15.0](https://hub.docker.com/\_/alpine)
        -   This is in preparation of multi-arch release
-   Added dependabot for automated version updates
-   Version updates
    -   Bump spring-boot from 2.3.12.RELEASE to 2.6.1
    -   Bump aws-v2 from 2.17.73 to 2.17.102
    -   Bump aws-java-sdk-s3 from 1.12.15 to 1.12.130
    -   Bump commons-io from 2.10.0 to 2.11.0
    -   Bump jaxb-api from 2.3.0 to 2.3.1
    -   Bump checkstyle from 8.44 to 9.2
    -   Bump xmlunit-assertj3 from 2.8.2 to 2.8.4
    -   Bump maven-resources-plugin from 3.1.0 to 3.2.0
    -   Bump maven-checkstyle-plugin from 3.1.1 to 3.1.2
    -   Bump maven-enforcer-plugin from 3.0.0-M3 to 3.0.0
    -   Bump maven-javadoc-plugin from 3.2.0 to 3.3.1
    -   Bump docker-maven-plugin from 0.36.1 to 0.38.1
    -   Bump Log4j2 to 2.15.0 (not actively used, just in case)

### [`v2.2.3`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;223)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.2.2...2.2.3)

-   Features and fixes
    -   Set bucket for multipart uploads, return by bucket. (Fixes [#&#8203;292](https://togithub.com/adobe/S3Mock/issues/292))

### [`v2.2.2`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;222)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.2.1...2.2.2)

-   Features and fixes
    -   Adds option "retainFilesOnExit" to keep files after exit. Default is to remove all files. (Fixes [#&#8203;286](https://togithub.com/adobe/S3Mock/issues/286))
    -   Fixes ignored "root" environment variable in Docker (Fixes [#&#8203;289](https://togithub.com/adobe/S3Mock/issues/289))
    -   Support CORS headers from any host (fixes [#&#8203;74](https://togithub.com/adobe/S3Mock/issues/74))

### [`v2.2.1`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;221)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.2.0...2.2.1)

-   Features and fixes
    -   Fixes copy part / copy object encoding issues (Fixes [#&#8203;279](https://togithub.com/adobe/S3Mock/issues/279))

### [`v2.2.0`](https://togithub.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#&#8203;220)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.1.36...2.2.0)

-   Features and fixes
    -   Add TestContainers support

### [`v2.1.36`](https://togithub.com/adobe/S3Mock/releases/tag/2.1.36)

[Compare Source](https://togithub.com/adobe/S3Mock/compare/2.1.34...2.1.36)

-   Delete all files on JVM shutdown (Fixes [#&#8203;249](https://togithub.com/adobe/S3Mock/issues/249))
-   Extract Docker build and integration tests to separate modules
-   Docker build and integration test is now optional, run with "-DskipDocker" to skip the Docker build and the integration tests. (Fixes [#&#8203;235](https://togithub.com/adobe/S3Mock/issues/235))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 3am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/solrbot/renovate-github-action)

### CODE REVIEW

**Review by risdenk — CHANGES_REQUESTED** [review]
Should also update software.amazon.awssdk in versions.props?

**Comment by risdenk** [comment]
Going to handle spring and springboot here as well since they are all related to this.

**Review by risdenk — APPROVED** [review]

**Comment by risdenk** [comment]
I ran these tests locally and somehow missed this exception:

```
                    Caused by:
                    com.fasterxml.jackson.databind.JsonMappingException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.nio.fs") (through reference chain: com.adobe.testing.s3mock.store.BucketMetadata["path"])
```

I reverted it from main. new PR https://github.com/apache/solr/pull/1535

**Comment by HoustonPutman** [comment]
@risdenk I see this was reverted from main, but I still see it in branch_9x. I'm getting conflicts when trying to backport https://github.com/apache/solr/pull/1610. Do you want to revert this before I backport the other one?

**Comment by risdenk** [comment]
O shoot if that is the case I made a mistake. I'll take care of branch_9x shortly. Sorry

**Pull request merged**
