### PR TITLE
chore(deps): update org.apache.logging.log4j:* to v2.24.1 - autoclosed

### PR DESCRIPTION
**Pull request by solrbot**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [org.apache.logging.log4j:log4j-web](https://logging.apache.org/log4j/2.x/) ([source](https://redirect.github.com/apache/logging-log4j2)) | dependencies | minor | `2.21.0` -> `2.24.1` |
| [org.apache.logging.log4j:log4j-slf4j2-impl](https://logging.apache.org/log4j/2.x/) ([source](https://redirect.github.com/apache/logging-log4j2)) | dependencies | minor | `2.21.0` -> `2.24.1` |
| [org.apache.logging.log4j:log4j-layout-template-json](https://logging.apache.org/log4j/2.x/) ([source](https://redirect.github.com/apache/logging-log4j2)) | dependencies | minor | `2.21.0` -> `2.24.1` |
| [org.apache.logging.log4j:log4j-core](https://logging.apache.org/log4j/2.x/) ([source](https://redirect.github.com/apache/logging-log4j2)) | dependencies | minor | `2.21.0` -> `2.24.1` |
| [org.apache.logging.log4j:log4j-api](https://logging.apache.org/log4j/2.x/) ([source](https://redirect.github.com/apache/logging-log4j2)) | dependencies | minor | `2.21.0` -> `2.24.1` |
| [org.apache.logging.log4j:log4j-1.2-api](https://logging.apache.org/log4j/2.x/) ([source](https://redirect.github.com/apache/logging-log4j2)) | dependencies | minor | `2.21.0` -> `2.24.1` |

---

### Configuration

📅 **Schedule**: Branch creation - "* * * * *" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these updates again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://redirect.github.com/solrbot/renovate-github-action)

### CODE REVIEW

**Review by risdenk — APPROVED** [review]

**Comment by janhoy** [comment]
This upgrade was tricky. First, it did not compile unless upgrading biz.aQute.bnd to v7.0.0. After that, the build fails, complaining about class versions:

```
/home/runner/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.23.0/10741ddf9effd8e04d568148c2948a22f3f4cc73/log4j-api-2.23.0.jar(/org/apache/logging/log4j/Level.class): warning: Cannot find annotation method 'value()' in type 'BaselineIgnore': bad class file: /home/runner/.gradle/caches/modules-2/files-2.1/biz.aQute.bnd/biz.aQute.bnd.annotation/7.0.0/8ad279ebf0d04ea89c5ce4d934189d0d16bb6d50/biz.aQute.bnd.annotation-7.0.0.jar(/aQute/bnd/annotation/baseline/BaselineIgnore.class)
    class file has wrong version 61.0, should be 55.0
```

I cannot see that Log4j have officially announced that they require Java 17, although their release note page at https://logging.apache.org/log4j/2.x/release-notes.html says for the 2.22.1 release: "**While maintaining compatibility with Java 8, the artifacts in this release where generated using JDK 17, unlike version 2.22.0 that used JDK 11.**".

@uschindler Can you decode what they mean by this and whether this is likely a bug in the 2.23.0 release or if we cannot upgrade since they require java17?

PS: We should start thinking about JDK bump for Solr on main to at least 17.

**Comment by janhoy** [comment]
I see from https://github.com/apache/logging-log4j2/issues/2232 and other discussions that log4j now tells users to include Log4j as `runtime` scope, not compile scope, and not to interact programmatically with the library (like we do).

**Comment by janhoy** [comment]
Unfortunate that we cannot upgrade due to requirement for Java 17 in a minor release... So will have to stick with the one we have I guess...

**Comment by cpoerschke** [comment]
Similar to #1821 i.e. blocked on JDK 17+ -- if I find a third solrbot PR like it I'll create a JIRA and then close out these in favour of that.

https://github.com/apache/solr/pull/1821#issuecomment-2049409176

**Comment by janhoy** [comment]
> @janhoy where did you see that log4j requires JDK 17? I don't see that based on https://logging.apache.org/log4j/2.x/release-notes.html
> 
> I found [apache/logging-log4j2#1922](https://github.com/apache/logging-log4j2/issues/1922) that affects the 2.21 version we use in Solr and we use the `notEmpty` so it actually produces more verbose logging.
> 
> I think we can upgrade log4j2

If you can make it work without compile failure then go for it. Last I tried I ran into issues https://github.com/apache/solr/pull/2047#issuecomment-1971765269

**Comment by risdenk** [comment]
Ah thanks @janhoy not sure how I missed that comment. I'll take a closer look

**Comment by risdenk** [comment]
New PR https://github.com/apache/solr/pull/2895

**Pull request closed without merging**
