### PR TITLE
SOLR-15080: Add 'zeppelin' integration to bin/solr

### PR DESCRIPTION
**Pull request by gerlowskija**
# Description

With the expansion of its streaming and math expression libraries, Solr now has a lot of analytics capabilities that integrate well with visualization and notebook software.  But Solr doesn't offer anything out of the box to aid in integration with popular notebook and visualization tools.  Providing an integration point with Apache Zeppelin, a popular notebook option, would go a long way to enabling analytics users to get started with Solr.  

# Solution

This PR create a "ZeppelinTool" integrated into the "bin/solr" scripts.  The tool deploys Zeppelin into a local sandbox and then bootstraps it to talk to Solr.  Other cleanup and update commands are supported.

# Tests

"bin/solr" scripts don't lend themselves to testing under Solr's test suites, so this has had to get by with manual testing on Linux and Mac.  (Windows to come shortly.)

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by HoustonPutman** [comment]
@gerlowskija, what does this provide over running Zeppelin locally yourself? I think `bin/solr` having an integration with Zookeeper makes a lot of sense, because Zookeeper is so tightly integrated inside of Solr. However Solr doesn't know what Zepplin is (correct me if I'm wrong here). I think it would be awesome to provide a detailed guide on using Solr and Zeppelin together, and either point to documentation on running Zeppelin, or have a short tutorial in the ref guide. However I'm not sure it's appropriate to have a command to start an unrelated service within `bin/solr`.

**Comment by epugh** [comment]
What was so interesting about this was that it seemed to lower the barrier to trying something new out, i.e using Zeppelin.   There is a lot of power around analytics locked up in Solr, and it's kind of hard to access.   I've mulled over trying to build out more analytics capablities in the Solr Admin, but that is a very steep climb.  I also thought about Jupyter, but the work that went into the analytics documentation was all based on Zeppelin, (plus another Apache project!) so it made sense to use it.  

`bin/solr` to me feels like an entry to a whole grab bag of tools, not just core "stop/start the Solr service".   

Maybe we should have had many other scripts in in `bin/` directory?   

`bin/solr zeppelin` or maybe `bin/solr demo-analytics` is all a lot easier than downloading and installing Zeppelin, and getting it configured to talk to Solr.  

I do think documenting how to connect Solr and Zeppelin would be a good thing!  Maybe we add it to the tutorial?

**Comment by HoustonPutman** [comment]
I can see the use case for solr-bin add-ons, kind of like how `kubectl` does [plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/). Would it be possible to refactor this into a separate file (maybe a bin/plugins/zepelin.sh or something), then enable it through `/bin/solr plugin zepelin`?

**Comment by epugh** [comment]
> I can see the use case for solr-bin add-ons, kind of like how `kubectl` does [plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/). Would it be possible to refactor this into a separate file (maybe a bin/plugins/zepelin.sh or something), then enable it through `/bin/solr plugin zepelin`?

Interesting idea!  CAuse eventually you do `bin/solr package zeppelin` and then `bin/solr plugin zeppelin blah blah blah`

**Comment by gerlowskija** [comment]
Hey @HoustonPutman Thanks for chiming in. A few replies inline.

> what does this provide over running Zeppelin locally yourself?

It automates all of the needed setup behind a single command: `bin/solr zeppelin bootstrap`.  So in a word: convenience.  You're right that Solr doesn't "know" about Zeppelin the same way that it knows about ZK, though Zeppelin isn't a totally random tool either.  Our ["Math Expressions" docs](https://solr.apache.org/guide/8_8/math-expressions.html) make heavy use of Zeppelin screenshots, for instance.

> I can see the use case for solr-bin add-ons, kind of like how kubectl does plugins.

I tried making [making a proper Solr plugin out of this](https://github.com/gerlowskija/binsolr-zeppelin) a month or so back, but Solr's plugin framework isn't ready for this use case yet.  (Currently, the plugin infrastructure lives in CoreContainer so only running Solr nodes have access to plugin jars.  I was able to get my plugin installed, but SolrCLI couldn't see it to run ZeppelinTool).

That's all to say - I'm only going the direct bin/solr route here because other attempts at a plugin setup failed.

Can you expand on the kubectl-plugin-like approach you have in mind?  I'm not against it necessarily, but I'm not sure I understand the benefits yet.  The large majority of the zeppelin integration logic lives in Java, with `bin/solr` really just being a passthrough call into Java-land. What does moving that passthrough over to `bin/plugins/zeppelin.sh` really get us?

**Comment by HoustonPutman** [comment]
Sorry, should have read through the PR more thoroughly. Agree that the passthrough isn't too bad if it's that small. There are a few additional questions I have but they are all related to having the Zepplin CLI code in a package (when that is supported in the future). So no need in asking them yet 🙂 

Thanks for the thorough response. Is there a ticket tracking Plugins supporting CLI additions?

**Comment by dsmiley** [comment]
I think like Houston, I would prefer to see a bin/somethingelse instead of bin/solr on principle because this is not starting solr, this is starting/installing Zeppelin.  On this point I'm "-0".  Disclaimer I very cursory looked at the diff.

**Comment by markrmiller** [comment]
This one seems a bit odd ti me as well. Given that Zeppelin is a server type app that is geared towards interfacing with a wide variety of data sources, even within a single notebook, it feels a bit odd to manage it via something out of Solr.

It's also fairly simple to setup and run - kind of feels more like a doc page. It's been a little while, but I believe you can even install the Solr interpreter as a helium plug-in with a few clicks in the UI.

Given it's difficult to test and play and anyone serious would likely just run zeppelin like you normally would, it almost seems simpler to just doc something like (outdated versions):

docker run -p 8080:8080 -d --name zeppelin apache/zeppelin:0.8.1
$ docker exec zeppelin ./bin/install-interpreter.sh --name solr --artifact com.lucidworks.zeppelin:zeppelin-solr:0.1.5
$ docker restart zeppelin # to load the interpreter

I don't even know you would have to restart these days, the helium stuff keeps improving.

**Review by risdenk — CHANGES_REQUESTED** [review]
I don't think this should be incldued in Solr. All the other commands in bin/solr are to control Solr itself - not integrate with third party code.

This has sat out here for >1 year. Do you think we should close this as "won't fix" and the jira?

**Comment by gerlowskija** [comment]
Closing this out based on (reasonable) objections from others here.

**Comment by gerlowskija** [comment]
But boy was it cool 😛

**Pull request closed without merging**
