### PR TITLE
Use hostContext property for RewriteHandler rules

### PR DESCRIPTION
**Pull request by wwelling**
https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by HoustonPutman** [comment]
I believe we recently removed the ability to specify a new hostContext in `main`. @epugh @gerlowskija

**Comment by wwelling** [comment]
@HoustonPutman thanks for the quick reply. I have been reading about that in the Jira and previous issues/PRs.

I noticed `hostContext` is still used in [solr-jetty-context.xml](https://github.com/apache/solr/blob/main/solr/server/contexts/solr-jetty-context.xml#L4).

To you by chance now why Solr is removing ability to configure its context path?

**Comment by epugh** [comment]
IIRC it was actually not well supported in recent versions of Solr, it may even not have worked at all in the 8x line...   With the V2 api's starting to live under `/api`, we want to make `/solr` and `/api` fixed paths.   I don't recall why, but this did faciliate the v2 api stuff...   Maybe @gerlowskija  can shed osme light.    

@wwelling I'd love to hear the use cases that you would *want* this for..  make sure we haven't shut the door on some reasons..

**Comment by wwelling** [comment]
Hi @epugh, our use case is through a constraint from load balancing requiring matching path with application context path. We have a solution with an additional application sidecar proxy but would like to be able to configure Solr's Jetty servlet container.

**Comment by dsmiley** [comment]
@wwelling You can configure Solr's Jetty to map `/foo` to `/solr` if that would help.

I think the overall objective was to reduce internal code maintenance on an option that didn't seem worth supporting.

**Comment by wwelling** [comment]
@dsmiley, thanks. I'll look into additional Jetty routing. Do think it is a reasonable request of the [Solr Docker](https://hub.docker.com/_/solr) image to afford environment driven context path configuration?

**Comment by dsmiley** [comment]
ehhh, no I don't TBH.  At least it's somewhat easy to create a new server/etc/jetty-customAdditions.xml and it'll be loaded.

**Comment by wwelling** [comment]
@dsmiley thanks. We will give that a try. Would be easy enough to mount a file for additional routing. Will have to see if it supports system variable or environment variable substitution. Otherwise, the context path configuration will still not be [12-factor](https://12factor.net/config).

**Comment by dsmiley** [comment]
My concern is avoiding complexity 99+% of users don't need.

**Comment by epugh** [comment]
@wwelling based on the conversation above, I am going to close this PR.  If you decide to move forward with the nesting of both `/solr` and `/api` as a new feature, please open a JIRA, and I'd be happy to review your PR!

**Pull request closed without merging**
