### PR TITLE
SOLR-16883: Use postlogs tool from windows and unix via solr cli infrastructure.

### PR DESCRIPTION
**Pull request by epugh**
https://issues.apache.org/jira/browse/SOLR-16883

# Description
experimenting with making the postlogs tool part of SolrCLI so it runs on windows and unix and elminate custom shell scripting.

Let's see if we can't get more usage/awareness of Solr consuming Solr logs!

# Solution
Similar to the SimplePostTool Approach...

# Tests

ran bats, but need one for bin/solr postlogs

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
@Willdotwhite @mkhludnev here is another one iwht changes to windows bin.cmd that owuld be nice to get independent test!

**Comment by Willdotwhite** [comment]
Tested @epugh 👍🏻 - I've no idea _what_ I just did, but it certainly did it:

```powershell
PS C:\Users\Will\Projects\solr\solr\packaging\build\dev\bin> .\solr.cmd postlogs -url http://localhost:8983/solr/gettingstarted -rootdir C:\Users\Will\Projects\solr\solr\packaging\build\dev\server\logs
Sending batch of 300 log records...
Batch sent
Sending batch of 300 log records...
Batch sent
Sending batch of 300 log records...
Batch sent
Sending batch of 300 log records...
Batch sent
Sending batch of 300 log records...
Batch sent
Sending batch of 300 log records...
Batch sent
Sending batch of 300 log records...
Batch sent
Sending last batch ...
Batch sent
Committed
```

**Comment by Willdotwhite** [comment]
The `-help` command prints the following, but doesn't actually explain **what** the command does - should that live in the help output, or do we expect people to check the online docs?

```powershell
PS C:\Users\Will\Projects\solr\solr\packaging\build\dev\bin> .\solr.cmd postlogs -help                                                                                                                   
usage: postlogs
 -help            Print this message
 -rootdir <arg>    All files found at or below the root will be indexed.
 -url <arg>       Address of the collection, example
                  http://localhost:8983/solr/collection1/.
 -verbose         Enable more verbose command output.
```

**Comment by joel-bernstein** [comment]
Sounds like a good idea to me.

**Comment by epugh** [comment]
> Sounds like a good idea to me.

Terrific!   Thanks for chiming in ;-).

**Comment by epugh** [comment]
@Willdotwhite so yeah, I have been moving the detailed help over to the Ref Guide.  Commons-cli doesn't make it easy to have a pretty/detailed "this is what the tool does", as far as I know.  So that IS something we lose...

**Comment by epugh** [comment]
@joel-bernstein I ran with it a bit and deprecated the SolrLogPostTool in favour of PostLogsTool and updated the ref guide as well in this PR.

**Pull request merged**
