### PR TITLE
SOLR-16911: Purge last hostContext references

### PR DESCRIPTION
**Pull request by gerlowskija**
https://issues.apache.org/jira/browse/SOLR-16911

# Description

SOLR-16911 removed almost all of the references to a variable called 'hostContext' used by Jetty to set a base path for v1 requests.  However, one reference remained.

# Solution

This PR removes the last removable hostContext reference from 'main': an unused parameter to a MiniSolrCloudCluster method.

# Tests

N/A - small refactor. Existing tests continue to pass.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.

### CODE REVIEW

**Comment by gerlowskija** [comment]
FYI @epugh

**Review by dsmiley — APPROVED** [review]

**Review by epugh — APPROVED** [review]
One question..   Is the "startJettySolrRunner" method actually used?  I expected that if you removed that parameter, then you'd be removing it from the caller classes too?   I wonder if that method is even needed???

**Comment by gerlowskija** [comment]
> Is the "startJettySolrRunner" method actually used? [...] I wonder if that method is even needed???

It's not used currently.  I thought about deleting it, but wasn't sure whether it might be there for the benefit of other projects that consume solr-test-framework.  Happy to remove it though if you think it's not helpful in that context?

**Comment by gerlowskija** [comment]
Alright - I'll remove it.  If the signature was less complex I'd be worried about deleting a method that users might be relying on in their tests, but looking at it, it'd take a pretty advanced user to invoke it.

It does raise an interesting question about whether backcompat even applies to solr-test-framework.  As someone who's used it in 3rd-party projects (e.g. [spark-solr](https://github.com/lucidworks/spark-solr/blob/master/pom.xml#L532)) it is a pain when breaking changes happen.  But at the same time, it probably doesn't require quite as rigid a backcompat-policy as a true client library like SolrJ.

**Comment by epugh** [comment]
Yeah...   I am not looking for more stasis and difficulty evolving Solr by establishing more "back compat" expectations...

**Comment by epugh** [comment]
🚢 it!

**Pull request merged**
