### PR TITLE
SOLR-16157, SOLR-16117: Fix maven release artifacts

### PR DESCRIPTION
**Pull request by HoustonPutman**
I think this fixes all of the issues that we could see with Solr Core (and Solr module) maven artifacts.

It overrides some of the work done in SOLR-16072. In general this approach requires less manual checking, and should just **work** whenever dependencies are added to solr-core or solr-server.

- Auto-find modules to build maven artifacts and distribution for
- Shared dependencies between solr-core and solr-server no longer need
  special dependency types, except for Jetty client libraries. This
  worked earlier because of SolrJ, and was not guaranteed to keep
  working.
- Remove the solr-server maven artifact.
- Add versioning constraints for server libraries

### CODE REVIEW

**Comment by madrob** [comment]
The comments here imply that there should be future work for splitting embedded Solr Server out into a separate module, does a JIRA for that already exist?

**Review by madrob — COMMENTED** [review]
Tested launching a separate application that depended on solr-core 10.0.0-SNAPSHOT installed via `gradlew mavenToLocalRepo` and used EmbeddedSolrServer, which worked. However, the same application worked without this PR as well. I'm not completely clear on what the underlying issue is then.

**Comment by HoustonPutman** [comment]
Hmmm interesting that it worked regardless. The ultimate goal was to make the build less error prone to changes in dependencies. Personally I think that this is better than having to keep the lists between core and server in-sync.

Also can you make sure to purge your local maven cache of all solr artifacts before trying the current implementation?

**Comment by madrob** [comment]
I think what is happening is that my project depends on solr-core, which has a transitive on solr-solrj, which then brings in the rest of what we need? Am I supposed to be depending on solr-server for anything here? That doesn't exist anymore, right?

**Review by madrob — APPROVED** [review]
Was able to see the failure before and the fix after, thanks for catching this before the release was live!

**Comment by HoustonPutman** [comment]
I also checked and the Jetty metrics that were fixed in SOLR-16072, and those are still visible with this change.

**Pull request merged**
