### PR TITLE
SOLR-15153 - Collection selector drop down does not sort collections

### PR DESCRIPTION
**Pull request by eribeiro**
# Description

Collection selector drop down does not sort collections

# Solution

call Collections.sort() on the list coming from ZK

# Tests

Manual tests. 

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by madrob — COMMENTED** [review]
Thanks for this patch, can you add an entry to CHANGES.txt so that we properly credit you?

**Comment by edwardoliveira** [comment]
Done. :)

**Comment by eribeiro** [comment]
@madrob Done. 🙂

**Comment by eribeiro** [comment]
Thanks @madrob ! 🙂

**Pull request merged**
