### PR TITLE
SOLR-15368: replace bad favicon logo to transparent background

### PR DESCRIPTION
**Pull request by almogtavor**
https://issues.apache.org/jira/browse/SOLR-15368?jql=project%20%3D%20SOLR%20AND%20component%20%3D%20website

# Description

On any modern webpage, the favicon has a transparent background, (for example - look at Github's logo as opposed to Solr's logo).

# Solution

There is actually a good logo on Solr's Jira site, which I've uploaded on this very issue PR

Example (Right is the PR, left is the current icon)
image

# Tests

The patch only replaces the favicon and left all else as is. I've run the website.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by janhoy** [comment]
Agree. What's the difference between web/favicon.ico and web/img/favicon.ico? Can one be deleted?
There is also a favicon in `solr/solr-ref-guide/src/images/icons/favicon.ico`, can you update that as well? And I guess there's one in the solr-site git repo as well, for the website?

**Comment by almogtavor** [comment]
The difference between web/favico.ico and web/img/facicon.ico is that web/favico.ico is for the web app while web/img/facicon.ico is for the admin UI (fix me if I didn't get that right @sarowe ). In my opinion, both should be replaced. I'll update them all and link the new PR here. I'll also do it for the solr-site repo as well

**Comment by almogtavor** [comment]
@janhoy I've deleted web/favicon.ico (that had no references anyway), and updated solr/solr-ref-guide/src/images/icons/favicon.ico. I've also made a PR for the website:
https://github.com/apache/solr-site/pull/21

**Comment by almogtavor** [comment]
@janhoy whats the status of this?

**Comment by janhoy** [comment]
See the linked Jira. I plan to commit in a day or two, barring any other comments.

**Pull request merged**
