### PR TITLE
SOLR-11029 Create a v2 API equivalent for DELETENODE API

### PR DESCRIPTION
**Pull request by bszabo97**
https://issues.apache.org/jira/browse/SOLR-11029

# Description

This PR implements a V2 equivalent for the `/admin/collections?action=DELETENODE` command.

# Solution

The solution makes use of JAX-RS annotations

# Tests

Because the solution uses the same methods in its core to do the actual work, I only added a test which checks the parameter conversion.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by gerlowskija** [comment]
Hi @bszabo97 

Just wanted to give you a short update on my lack of progress on this.

It is definitely still on my radar, but I've been a little distracted recently focusing on a performance regression that someone noticed in the JAX-RS framework overall: another committer noticed that the recent addition of the JAX-RS framework has slowed down Solr startup, in some cases quite significantly.  That's turned into a big blocker for the JAX-RS work overall: there's even talk of deferring the release of our JAX-RS v2 APIs until that perf regression can be mitigated.

So most of my focus has shifted to that - after all, it's not much good focusing on individual JAX-RS APIs if shipping the whole framework gets delayed 😛 If you're curious, see SOLR-16531 for more details on all this.

Anyway, that's all to say that I haven't gotten to this PR, but that I haven't forgotten it or let it fall off my radar.  I'm just focusing on this performance blocker, and plan to return to this when that's finished.  I appreciate all your work here and definitely haven't forgotten it!

**Comment by bszabo97** [comment]
Hello @gerlowskija 

Thanks for the heads up and for the great description of what should be changed in the tests. I have added a commit which changes the test and implementation according to your suggestions.
If you think there is anything around the performance blocker in which I can help with I am more than happy to do so!

**Review by gerlowskija — APPROVED** [review]
Thanks for addressing the tests; LGTM

**Comment by gerlowskija** [comment]
Alright - thanks for the PR @bszabo97, it's perfect.  My apologies again for the huge delay with the SOLR-16531 blocker, but I'm happy to say that should be cleared away at this point.

With the test changes you made back in December-ish this looks ready-to-merge to me, and it's certainly been out here for review long enough!  I've brought this up to date with the latest `main`, and `./gradlew check` is passing.  I'll merge this afternoon and then backport after a few days.  Thanks again!

**Pull request merged**
