### PR TITLE
SOLR-17481: Resolve use of -n flag in CLI commands

### PR DESCRIPTION
**Pull request by epugh**
https://issues.apache.org/jira/browse/SOLR-17481
# Description

Deal with overlaps in flags

# Solution
deprecate (9x) and remove (10.0) -n for defining the number of threads in SolrExporter
Remove  -n for no-prompt in RunExampleTool (this option is not supported via bin/solr or bin/solr.cmd so no need to deprecate).

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended, not available for branches on forks living under an organisation)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
@malliaridis this is ready for review.   I just removed "n" from RunExampleTool since it is not exposed.

**Review by malliaridis — CHANGES_REQUESTED** [review]
Thanks for providing a PR so quickly. :)

Additional occurences that should be updated:
- [x] solr/solr-ref-guide/modules/deployment-guide/pages/monitoring-with-prometheus-and-grafana.adoc - ~6 occurences of -n for --num-threads
- [ ] solr/dev-tools/scripts/cloud.sh - may be ignored, but uses -n for number of nodes

**Comment by epugh** [comment]
Going to ignore `cloud.sh` since it doesn't have any long options...  and I don't want to try to figure out adding long options!

**Review by malliaridis — APPROVED** [review]
Looks good to me then. :)

**Pull request merged**
