### PR TITLE
SOLR-16639: Fix jq parse error of solr-exporter metrics node_thread_pool_completed_total

### PR DESCRIPTION
**Pull request by chlorochrule**
https://issues.apache.org/jira/browse/SOLR-16639

# Description

jq expr `select(.key | endswith(".completed"))` matches "\*.tasks.completed" too. But the format of "\*.tasks.completed" metrics is like bellow:

"QUERY.httpShardHandler.threadPool.httpShardExecutor.tasks.completed":16,

https://github.com/apache/solr/blob/bf490f16b5e1acbbd4b01ec3aa1e5b035096716a/solr/prometheus-exporter/conf/solr-exporter-config.xml#L541

So, `$object.value.count` jq expr occurs jq parse error.

solr-exporter logs:
```
ERROR - 2023-01-28 18:11:55.401; org.apache.solr.prometheus.scraper.SolrScraper; Error apply JSON query=(.metrics["solr.node"] | to_entries | .[] | select((.key | contains(".threadPool."))) | select((.key | endswith(".completed"))) as $object | $object.key | split(".") as $key_items | $key_items | length as $label_len | $key_items[0] as $category | if ($label_len >= 5) then $key_items[1] else "" end as $handler | if ($label_len >= 5) then $key_items[3] else $key_items[2] end as $executor | $object.value.count as $value | {("name"): "solr_metrics_node_thread_pool_completed_total",("type"): "COUNTER",("help"): "See following URL: https://solr.apache.org/guide/solr/latest/deployment-guide/metrics-reporting.html",("label_names"): [("category", "handler", "executor")],("label_values"): [($category, $handler, $executor)],("value"): $value}) to result => net.thisptr.jackson.jq.exception.JsonQueryException: Cannot index number with string "count"
```

# Solution

I fixed this problem to add `select(.value | type=="object")` filter to jq expr.

# Tests

I verified this patch in my dev environment using SolrCloud.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by HoustonPutman — APPROVED** [review]
I haven't verified this, but it makes sense to me.

**Comment by chlorochrule** [comment]
@HoustonPutman Thank you for reviewing!

**Comment by HoustonPutman** [comment]
@chlorochrule could you add a CHANGES.txt entry?

**Comment by HoustonPutman** [comment]
Tested this locally and it works wonderfully!

**Comment by chlorochrule** [comment]
Thank you for merging, @HoustonPutman!

**Pull request merged**
