### PR TITLE
Refactor SolrZkclient to use a Builder pattern

### PR DESCRIPTION
**Pull request by noblepaul**

### CODE REVIEW

**Comment by dsmiley** [comment]
Just a quick comment:  Does the move to Overseer render SolrZkClient obsolete @HoustonPutman ?  Thus should we bother with changing SolrZkClient if it's going away any month now?  Maybe this is a 10x vs 9x thing.

**Comment by epugh** [comment]
Could we follow the same pattern defined in SOLR-16595 and SOLR-16590 of using `with` instead of bare property names, and using `TimeUnit`?   Have some consistency in how we create our builders!

**Comment by dsmiley** [comment]
@noblepaul The change in TestCloudManagedSchema is clearly wrong.  Notice the "(" in the string.  This test is failing on me and Jenkins now.

**Comment by noblepaul** [comment]
fixing...

**Pull request merged**
