### PR TITLE
SOLR-16500: Added --enable-preview for JDK 19 to enable MemorySegment support in MMapDirectory

### PR DESCRIPTION
**Pull request by risdenk**
https://issues.apache.org/jira/browse/SOLR-16500

### CODE REVIEW

**Review by uschindler — APPROVED** [review]
Looks fine.

I am not sure if "MMapDirectory V2" is a good term to describe it in the message.

Maybe remove the message at all. Because Lucene logs a message anyways.

**Review by janhoy — APPROVED** [review]

**Comment by risdenk** [comment]
> I am not sure if "MMapDirectory V2" is a good term to describe it in the message. Maybe remove the message at all. Because Lucene logs a message anyways.

so I want to at least leave a message that we enabled preview features and that we added a flag to the JDK. I'm open to calling it something other than `MMapDirectory V2`.

**Comment by uschindler** [comment]
> > I am not sure if "MMapDirectory V2" is a good term to describe it in the message. Maybe remove the message at all. Because Lucene logs a message anyways.
> 
> so I want to at least leave a message that we enabled preview features and that we added a flag to the JDK. I'm open to calling it something other than `MMapDirectory V2`.

Maybe call it "Java $JAVA_VER_NUM detected. Added --enable-preview to enable MemorySegment support in MMapDirectory. See SOLR-16500"

**Comment by risdenk** [comment]
Addressed wording in 346c884

**Review by uschindler — APPROVED** [review]

**Pull request merged**
