### PR TITLE
SOLR-15258: ConfigSetService operations ought to throw IOException

### PR DESCRIPTION
**Pull request by NazerkeBS**
https://issues.apache.org/jira/browse/SOLR-15258

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by madrob** [comment]
I'm not sure I understand the motivation for this change, can you please open a JIRA issue describing what this aims to solve or improve? Thanks!

**Comment by NazerkeBS** [comment]
@madrob, if `getCurrentSchemaModificationVersion` throws an exception, then its caller doesn't have to catch the exception;

**Comment by NazerkeBS** [comment]
As this change is trivial, it can be part of SOLR-15258 (ConfigSetService refactoring)

**Comment by dsmiley** [comment]
I proposed to Nazerke that she file this PR and that it was too simple to warrant a JIRA issue as well.  The issue description should have been filled to justify the PR's existence/purpose but wasn't.

Basically all operations of ConfigSetService that read/write ought to throw an IOException and most do but not this one, which I think was simply an oversight.  Thus if you call this, perhaps delegating, and if you call something that might throw IOException, then you have to wrap it.

Other methods ought to throw IOException as well but don't declare it now:
* loadConfigSetFlags

That's it, as far as I can see.

**Comment by madrob** [comment]
> if getCurrentSchemaModificationVersion throws an exception, then its caller doesn't have to catch the exception;

Is this an _is_ or _ought_ statement? In other words, are you saying that this is a problem currently? What would you expect a caller to do if there is an exception thrown? How is it different from the current case of catching SolrException?

> As this change is trivial, it can be part of SOLR-15258 (ConfigSetService refactoring)

Yes, that's fine.

**Comment by dsmiley** [comment]
> Is this an is or ought statement? 

"ought".  It's a minor nuisance really.

**Comment by janhoy** [comment]
The JIRA for this PR is closed. Should this PR also be closed or is there still work that needs to be merged?

**Comment by dsmiley** [comment]
This wasn't done; it's follow-up tiny stuff.  @NazerkeBS there are a couple things remaining I asked of you -- the empty catch, and loadConfigSetProperties

**Pull request merged**
