### PR TITLE
Update dependency com.fasterxml.jackson:jackson-bom to v2.15.2

### PR DESCRIPTION
**Pull request by solrbot**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [com.fasterxml.jackson:jackson-bom](https://togithub.com/FasterXML/jackson-bom) | dependencies | minor | `2.14.2` -> `2.15.2` |

---

### Configuration

📅 **Schedule**: Branch creation - "* * * * 0" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/solrbot/renovate-github-action)

### CODE REVIEW

**Comment by risdenk** [comment]
@noblepaul This also updated `com.fasterxml.woodstox:woodstox-core` to 6.5.1 which should have been updated in versions.props.

**Comment by risdenk** [comment]
Fixed in Fixed versions.props in f70696a96fac878a1b699606d914a69a4516d202

**Comment by janhoy** [comment]
Not necessarily a bug per se, lock file may by design have higher versions than in props. The documentation of gradle-consistent-versions plugin https://github.com/palantir/gradle-consistent-versions#versionsprops-lower-bounds-for-dependencies says:

> versions.props: lower bounds for dependencies
Specify versions for your direct dependencies in a single root-level versions.props file. Think of these versions as the minimum versions your project requires.

Once in a while we need to override the *minimum* version of a lib, but once gradle selects a compatible version by itself, perhaps we could simply remove the override of woodstox now?

```
> Task :why
com.fasterxml.woodstox:woodstox-core:6.5.1
	projects -> 6.5.1
	com.fasterxml.jackson.dataformat:jackson-dataformat-xml -> 6.5.1
	org.apache.tika:tika-parsers -> 6.3.1
```

**Comment by risdenk** [comment]
woodstox-core is explicitly used as a dependency in `solr/core/build.gradle` and `solr/modules/s3-repository/build.gradle` and want to make sure it stays at the more recent version.

Agreed its a minimum but if we have a versions.props line - it should line up with the dependency version in verisons.lock. Its  incorrect to just let the older versions.props line just sit there out of date. I know because I went through and cleaned up most of these forgotten properties a while ago.

It might be possible to remove versions.props line for woodstox-core.

**Pull request merged**
