### PR TITLE
Support ./gradlew modernizer

### PR DESCRIPTION
**Pull request by risdenk**
https://issues.apache.org/jira/browse/SOLR-XXXXX

A long time ago I was looking at ways to improve the build process to detect out of date usages. This adds `./gradlew modernizer` that will find things that can be replaced.

based on https://github.com/andygoossens/gradle-modernizer-plugin

I went through all the failures and added some exclusions to make things clean. Mostly simple stuff.

### CODE REVIEW

**Review by stillalex — APPROVED** [review]
looks good. but mainly charset related changes?

**Comment by risdenk** [comment]
Yup @stillalex this is just finding MOSTLY charset related changes right now. There are some disabled - https://github.com/apache/solr/pull/2006/files#diff-9257ac5900027c3c54700c25c646e201f7fcec13c7f39ecedd288f99c0ecb5f2R30. I don't know if this is worth it. We have cleaned up a lot of older usages with errorprone already.

**Review by cpoerschke — APPROVED** [review]

**Comment by risdenk** [comment]
Interestingly errorprone https://github.com/google/error-prone/releases/tag/v2.23.0 might have just addressed the charset stuff so this PR might not be necessary.

**Comment by stillalex** [comment]
interesting. if they add this then yeah, I agree this change is on longer useful.

**Comment by risdenk** [comment]
Yea https://github.com/apache/solr/pull/2035 covers MOST of this.

**Pull request closed without merging**
