### PR TITLE
SOLR-16995: Use leaderEligible property where it makes sense

### PR DESCRIPTION
**Pull request by pvcnt**
https://issues.apache.org/jira/browse/SOLR-16995

# Description

A new `leaderEligible` property was introduced on the `Replica.Type` in Solr 9 (?), but it is currently not used much in the codebase. Most of the code still uses something like `replicaType == Type.NRT || replicaType == Type.TLOG`, which makes the intention behind the code more difficult to read.

# Solution

This PR is a refactoring using the `leaderEligible` property wherever it makes sense, to make the code more readable.

# Tests

No new tests, as this refactoring does not introducing any new classes or methods, and does not change the existing behaviour.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by pvcnt** [comment]
Related to #1928 (split this particular change into a separate PR).

**Review by dsmiley — APPROVED** [review]
Nice.

BTW a JIRA isn't necessary for this low-impact internal refactoring.  Just an FYI; since you created it, keep it.

**Comment by pvcnt** [comment]
@dsmiley It's actually the same JIRA as #1928. It just split my end goal (making it easier to work with replica types and possibly add new ones) into several PRs.

**Comment by pvcnt** [comment]
Failing tests are passing locally, they ma be flappers.

**Comment by HoustonPutman** [comment]
I love this. To many single-class/enum cases across the codebase, which makes adding new options much harder.

**Pull request merged**
