### PR TITLE
SOLR-15333 Fix SpatialRecursivePrefixTreeFieldType schema definition warnings

### PR DESCRIPTION
**Pull request by madrob**
Co-authored-by: Steffen Moldenhauer <s.moldenhauer@intershop.de>
Co-authored-by: David Smiley <dsmiley@apache.org>

https://issues.apache.org/jira/browse/SOLR-15333

Tested with unit tests, and with manual inspection of `docker run --rm -it apache/solr:10.0.0-SNAPSHOT solr-demo`

### CODE REVIEW

**Review by dsmiley — APPROVED** [review]
Thanks.
Say, was the simple test I wrote not useful?

**Comment by dsmiley** [comment]
Right thanks but that doesn't directly address my question.  I liked the simplicity of the test I wrote.   Any way, thanks for shepherding this one through Mike.

**Comment by madrob** [comment]
Oh, I see, I misunderstood your question, then. The test you wrote is still at the heart of the method https://github.com/apache/solr/commit/7f620c7a10006f344ff660d28b17298372f102fd#diff-126773ac5b95d785af0278f711cf6cbcc33fc7913036fbf4780c81bf6f445062R1194-R1199 but I added the LogListener decorator and a few negative conditions after it.

Those could have been three different test cases, I suppose.

**Comment by dsmiley** [comment]
Ah; it's surrounded by so much other code that I simply didn't notice ;-)

**Pull request merged**
