### PR TITLE
Update io.opentelemetry to 1.29.0

### PR DESCRIPTION
**Pull request by stillalex**
https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

OTEL update. no Jira needed.
This is needed to simplify https://github.com/apache/solr/pull/1841

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by stillalex** [comment]
@janhoy just fyi. do you think it's worth backporting this to 9.x?

**Comment by janhoy** [comment]
> @janhoy just fyi. do you think it's worth backporting this to 9.x?

Yes, please do. Also, remember to add a CHANGES.txt entry under "Dependency Upgrades", both on main branch and branch_9x.

**Comment by stillalex** [comment]
> Also, remember to add a CHANGES.txt entry under "Dependency Upgrades",

Is that still necessary? I was looking at the automated dependency updates from Renovate bot we have and those do not add an entry.

**Comment by stillalex** [comment]
ok I had misunderstood how that works. I forgot to add that entry, added it as https://github.com/apache/solr/pull/1847
will backport to 9.x shortly

**Comment by janhoy** [comment]
Yea, no probn. The rule is that if you commit/push a dependency upgrade manually, you have to add the entry yourself. If you merely merge a PR from @solrbot then it will be added to CHANGES in bulk during the release process.

**Pull request merged**
