### PR TITLE
SOLR-17405: allow a single thread to reestablish ZK session

### PR DESCRIPTION
**Pull request by psalagnac**
https://issues.apache.org/jira/browse/SOLR-17405

# Description

`OnReconnect` can be invoked by several threads concurrently (see Jira for the explanation).

Same change as #2644, but against `9x` branch. This bug does not exist anymore in `main` since the move to Curator.

# Solution

Always add the wrapper on the watch that handle the session expiration events. This makes sure the session is re-established in a dedicated thread, and this thread exists only once per server.

# Tests

No new tests added. Unfortunately, this is super tricky to reproduce.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by dsmiley — APPROVED** [review]
Approving based on my trust in you and our experiences with this bug fix

**Comment by dsmiley** [comment]
bug fixes can go into 9.8

**Comment by psalagnac** [comment]
> bug fixes can go into 9.8

Thanks. For clarification, do you advise to port to 9.8 branch now?

**Comment by dsmiley** [comment]
You need to finish before Anshum (in California) starts his day.

**Comment by epugh** [comment]
I actually think we won't see a 9.8 release get moving until after the new year, so we have time ;-).

**Pull request merged**
