### PR TITLE
SOLR-17089: Upgrade Jersey to 3.1.5

### PR DESCRIPTION
**Pull request by gerlowskija**
https://issues.apache.org/jira/browse/SOLR-17089

# Description

Brings in a number of bug fixes and improvements, as well as fixing some irritating stacktraces that Jersey 2.x was logging in certain startup scenarios.

# Tests

Automated tests continue to pass, manual testing of our Jersey-based v2 APIs

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.

### CODE REVIEW

**Comment by risdenk** [comment]
So having the `swagger-jaxrs2-jakarta` is ok even though we are in theory on javax still with Jetty? I have a hard time wrapping my head around when javax vs jakarta matters :/

**Comment by gerlowskija** [comment]
Yeah, I'm definitely with you - it's very confusing.

My intention with the `swagger-jaxrs2-jakarta` dep is that it's not a proper Solr dependency - it's something needed by one of the plugins our gradle build uses.  Specifically it's used by 'swagger-gradle-plugin' so that it can pick up jakarta-packaged annotations in generating the OAS.  See these [swagger-gradle-plugin](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-gradle-plugin#jakarta-namespace-support) docs for a bit more context.

**Comment by gerlowskija** [comment]
This is ready to merge, but I'm going to hold off until the 9.5 branch is cut as the Jersey dep affects a lot, some of which have wider ramifications (javax v. jakarta, jetty, etc.).

**Comment by risdenk** [comment]
@cpoerschke see https://lists.apache.org/thread/hlh1bmtgnmp55q8knhjtltf8t57pbl5q about unlicensed. I don't specifically know about the `jakarta.inject-2.6.1.jar.sha1` one but in general I know there is some weirdness with usage tracking of files without a clean.

**Comment by cpoerschke** [comment]
> ... (Probably dev mailing list thread or JIRA issue worthy but as a first step commenting here in case that helps.)

https://issues.apache.org/jira/browse/SOLR-17142 created.

**Pull request merged**
