### PR TITLE
Apache 9x

### PR DESCRIPTION
**Pull request by renatoh**
Debugging FacetComponent I noticed two little things which can be improved

### CODE REVIEW

**Comment by renatoh** [comment]
@mkhludnev Is the PR now correct? Thanks!

**Review by mkhludnev — APPROVED** [review]

**Comment by mkhludnev** [comment]
Yeah! Right. Appreciate. Thanks!

**Comment by HoustonPutman** [comment]
Did this go to `main` first?

**Comment by mkhludnev** [comment]
Absolutely, @HoustonPutman 
https://github.com/apache/solr/pull/1305

**Pull request merged**
