### PR TITLE
add build badges to README.md

### PR DESCRIPTION
**Pull request by cpoerschke**
Inspired by @stefanvodita's https://github.com/apache/lucene/pull/13476 change.

### CODE REVIEW

**Review by janhoy — APPROVED** [review]

**Comment by HoustonPutman** [comment]
Thank you! Curious why you chose the `artifact` build over the `check` build though.

**Comment by cpoerschke** [comment]
> ... Curious why you chose the `artifact` build over the `check` build though.

Errm, not a choice as such, just did the same as what the Lucene badge does. I guess technically we could have badges for both or even more than two?

As an aside, the Gradle dashboard link doesn't yet work for me, could be local issue, not yet looked into. Does it work for anyone else?

**Comment by dsmiley** [comment]
Check/Artifact:   If the intent is to offer a very latest download for Solr, then should be "Artifact".  I doubt this is useful in a world of Docker and Maven JAR artifact publication, however (ideally we conveniently link to both).  If the intent is to communicate the test status, then should link to a "check" build.  Or maybe we should link to the whole category in Jenkins.

**Comment by cpoerschke** [comment]
> As an aside, the Gradle dashboard link doesn't yet work for me, could be local issue, not yet looked into. Does it work for anyone else?

Just removed it for now.

**Comment by epugh** [comment]
Love to see this get added!

**Pull request merged**
