### PR TITLE
SOLR-15838: Update Solr to use released Lucene 9.0.0

### PR DESCRIPTION
**Pull request by uschindler**
See https://issues.apache.org/jira/browse/SOLR-15838

### CODE REVIEW

**Comment by uschindler** [comment]
I left the nightlies repository code commented out, so we can use the mechanism again in the future.

**Comment by uschindler** [comment]
Adding @jpountz as reviewer, because he did the Lucene 9.0 release to Maven central.

To me it looks like all Maven artifacts resolve correctly from Maven central.

**Comment by uschindler** [comment]
I am not 100% sure, but it looks like we do not add checksums and Licenses for Lucene's JAR files. IMHO we should now also add them to make sure all files are sane. Also Lucene is now a third party project, so we should have License, too.

**Comment by uschindler** [comment]
In the PR I added checksums and License/Notice.

Basically the NOTICE.txt file in the root folder of Lucene seems obsolete. I did not touch, it may be a separate issue.

**Comment by uschindler** [comment]
> Basically the NOTICE.txt file in the root folder of Lucene seems obsolete. I did not touch, it may be a separate issue.

not fully obsolete, but all third party text can be removed.

**Review by madrob — APPROVED** [review]
This is nearly identical to the set of changes I was making on my end before I realized that you were working on this as well.

**Comment by uschindler** [comment]
I also did some quick checks, Admin UI shows correct versions:

image

**Review by janhoy — APPROVED** [review]
LGTM.

Related question - Solr still uses Lucene's `Version` class several places. It's probably right when determining index compatibility, analysis components etc, but other places such as in Package Manager and outputing Solr's current version on startup and SolrCLI's version, it will be wrong. Do we have a JIRA already to introduce a `SolrVersion` class and use it where it makes sense?

**Comment by uschindler** [comment]
> Related question - Solr still uses Lucene's `Version` class several places. It's probably right when determining index compatibility, analysis components etc, but other places such as in Package Manager and outputing Solr's current version on startup and SolrCLI's version, it will be wrong. Do we have a JIRA already to introduce a `SolrVersion` class and use it where it makes sense?

I think this should be done! Especially the `Package#getImplementationVersion()` no longer works with module system, so Solr should at some point use the same code as Lucene's `Version` class to get implementation version from its JAR file (in case module system is present): https://github.com/apache/lucene/pull/473

I will merge this now, this should be separate issue.

**Pull request merged**
