### PR TITLE
SOLR-14115: Allow bin/solr zk commands to have parity with zkcli.sh commands.

### PR DESCRIPTION
**Pull request by epugh**

### CODE REVIEW

**Comment by epugh** [comment]
Discovered that we have some great unit testings for the ZkCLI.java, and we don't have them for bin/solr zk, so going to copy the over to a new unit test `ZkSubcommandsTest.java`.  This will also let me see if they are relatively equivalent or not.

**Comment by epugh** [comment]
Making progress...    I *think* I have `bin/solr` done, and I am *hoping* I got `bin/solr.cmd` done...   Now looking at `cloud.sh`....   cc @gus-asf on these changes coming up....

**Comment by epugh** [comment]
@gus-asf  would love your review of commit 2efdcdbc4174c4517cfc59e8fd8f42cf0bb0ec95 specifically!

**Comment by elangelo** [comment]
This PR doesn't work. When using the `solr zk` command you need to provide the `--zk-host $ZK_HOST` argument:
 https://github.com/apache/solr-operator/pull/756

**Pull request merged**
