### PR TITLE
SOLR-15456: Get field type info from luke for custom fields instead of defaulting to String

### PR DESCRIPTION
**Pull request by thelabdude**
https://issues.apache.org/jira/browse/SOLR-15456

# Description

See JIRA

# Solution

Added additional request to get schema info from luke for custom field types.

# Tests

Added unit test to verify the type information for custom fields resolves correctly.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by markrmiller — APPROVED** [review]
Nice.

**Comment by thelabdude** [comment]
Still thinking about the caching of schema info here ...

**Comment by madrob** [comment]
I think this conflicts with #177 can you and Mark chat about the proper implementation of `toSolrLiteral`/`translateTerms`

**Comment by thelabdude** [comment]
@markrmiller I decided to remove the Cache for luke responses from this PR for now. I like your idea about pushing cache support into the LukeRequestHandler, but think that should be tackled in a separate PR. For this PR, I'm not all that convinced caching would even buy us much given requests to the `/sql` handler would be load-balanced, so unlikely to see enough cache hits to justify the added code complexity of ensuring the cached field / field type info isn't stale.

**Comment by thelabdude** [comment]
> I think this conflicts with #177 can you and Mark chat about the proper implementation of `toSolrLiteral`/`translateTerms`

@markrmiller I think this PR will get merged before your upgrade ... once you merge in my changes here, you can drop the `translateTerms` call and just use my changes as I switched to calling `getValue2()` as you're doing in your PR ... thanks for catching this @madrob ;-)

**Review by markrmiller — APPROVED** [review]

**Pull request merged**
