### PR TITLE
Update dependency com.google.errorprone:error_prone_annotations to v2.22.0

### PR DESCRIPTION
**Pull request by solrbot**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [com.google.errorprone:error_prone_annotations](https://errorprone.info) ([source](https://togithub.com/google/error-prone)) | dependencies | minor | `2.18.0` -> `2.22.0` |

---

### Release Notes

<details>
<summary>google/error-prone</summary>

### [`v2.22.0`](https://togithub.com/google/error-prone/releases/tag/v2.22.0): Error Prone 2.22.0

We are considering raising the minimum supported JDK from JDK 11 to JDK 17 in a future release of Error Prone, see [#&#8203;3803](https://togithub.com/google/error-prone/issues/3803). Note that using a newer JDK version to run javac during the build doesn't prevent building code that is deployed to earlier versions, for example it's supported to use the JDK 17 javac and pass `--release 11` to compile Java 11 code that is deployed to a JDK 11 runtime. If you have feedback, please comment on [#&#8203;3803](https://togithub.com/google/error-prone/issues/3803).

New checks:

-   [`ClosingStandardOutputStreams`](https://errorprone.info/bugpattern/ClosingStandardOutputStreams): Prevents accidentally closing `System.{out,err}` with try-with-resources
-   [`TruthContainsExactlyElementsInUsage`](https://errorprone.info/bugpattern/TruthContainsExactlyElementsInUsage): `containsExactly` is preferred over `containsExactlyElementsIn` when creating new iterables
-   [`UnnecessaryAsync`](https://errorprone.info/bugpattern/UnnecessaryAsync): detects unnecessary use of async primitives in local (and hence single-threaded) scopes
-   [`ReturnAtTheEndOfVoidFunction`](https://errorprone.info/bugpattern/ReturnAtTheEndOfVoidFunction): detects unnecessary `return` statements at the end of `void` functions
-   [`MultimapKeys`](https://errorprone.info/bugpattern/MultimapKeys): Suggests using `keySet()` instead of iterating over `Multimap.keys()`, which does not collapse duplicates

Bug fixes and improvements:

-   Don't complain about literal IP addresses in `AddressSelection` (https://github.com/google/error-prone/commit/44b65527debbc57892f21ca3ba458b16771e423e)
-   Prevent SuggestedFixes#renameMethod from modifying return type declaration ([#&#8203;4043](https://togithub.com/google/error-prone/issues/4043))
-   Fix UnusedVariable false positives for private record parameters ([#&#8203;2713](https://togithub.com/google/error-prone/issues/2713))
-   When running in conservative mode, no longer assume that implementations of `Map.get`, etc. return `null` ([#&#8203;2910](https://togithub.com/google/error-prone/issues/2910))
-   CanIgnoreReturnValueSuggester: Support additional exempting method annotations ([#&#8203;4009](https://togithub.com/google/error-prone/issues/4009))
-   UnusedVariable: exclude junit5's `@RegisterExtension` ([#&#8203;3892](https://togithub.com/google/error-prone/issues/3892))
-   Support running all available patch checks ([#&#8203;947](https://togithub.com/google/error-prone/issues/947))
-   Upgrade java-diff-utils 4.0 -> 4.12 ([#&#8203;4081](https://togithub.com/google/error-prone/issues/4081))
-   Flag unused Refaster template parameters ([#&#8203;4060](https://togithub.com/google/error-prone/issues/4060))
-   Support `@SuppressWarnings("all")` ([#&#8203;4065](https://togithub.com/google/error-prone/issues/4065))
-   Prevent Refaster `UMemberSelect` from matching method parameters ([#&#8203;2456](https://togithub.com/google/error-prone/issues/2456))
-   MissingDefault : Don't require `// fall out` comments on expression switches ([#&#8203;2709](https://togithub.com/google/error-prone/issues/2709))
-   Skip UnnecessaryLambda findings for usages in enhanced for loops ([#&#8203;2518](https://togithub.com/google/error-prone/issues/2518))
-   Fix bug where nested MissingBraces violations' suggested fixes result in broken code ([#&#8203;3797](https://togithub.com/google/error-prone/issues/3797))
-   Add support for specifying `exemptPrefixes`/`exemptNames` for UnusedVariable via flags ([#&#8203;2753](https://togithub.com/google/error-prone/issues/2753))
-   UnusedMethod: Added exempting variable annotations ([#&#8203;2881](https://togithub.com/google/error-prone/issues/2881))

Full Changelog: https://github.com/google/error-prone/compare/v2.21.1...v2.22.0

### [`v2.21.1`](https://togithub.com/google/error-prone/releases/tag/v2.21.1): Error Prone 2.21.1

Changes:

-   Handle overlapping ranges in suppressedRegions (fixes [#&#8203;4040](https://togithub.com/google/error-prone/issues/4040))
-   Add [` AddressSelection  `](https://errorprone.info/bugpattern/AddressSelection) to discourage APIs that convert a hostname to a single address

Full Changelog: https://github.com/google/error-prone/compare/v2.21.0...v2.21.1

### [`v2.21.0`](https://togithub.com/google/error-prone/releases/tag/v2.21.0): Error Prone 2.21.0

New Checkers:

-   [`AttemptedNegativeZero`](https://errorprone.info/bugpattern/AttemptedNegativeZero): Prevents accidental use of `-0`, which is the same as `0`. The floating-point negative zero is `-0.0`.
-   [`ICCProfileGetInstance`](https://errorprone.info/bugpattern/ICCProfileGetInstance): Warns on uses of `ICC_Profile.getInstance(String)`, due to [JDK-8191622](https://bugs.openjdk.org/browse/JDK-8191622).
-   [`MutableGuiceModule`](https://errorprone.info/bugpattern/MutableGuiceModule): Fields in Guice modules should be `final`.
-   [`NullableOptional`](https://errorprone.info/bugpattern/NullableOptional): Discourages `@Nullable`-annotated `Optional`s.
-   [`OverridingMethodInconsistentArgumentNamesChecker`](https://errorprone.info/bugpattern/OverridingMethodInconsistentArgumentNamesChecker): Arguments of overriding method are inconsistent with overridden method.

Fixed issues: [#&#8203;3976](https://togithub.com/google/error-prone/issues/3976), [#&#8203;3986](https://togithub.com/google/error-prone/issues/3986), [#&#8203;4001](https://togithub.com/google/error-prone/issues/4001), [#&#8203;4002](https://togithub.com/google/error-prone/issues/4002), [#&#8203;4026](https://togithub.com/google/error-prone/issues/4026), [#&#8203;4027](https://togithub.com/google/error-prone/issues/4027)

Full Changelog: https://github.com/google/error-prone/compare/v2.20.0...v2.21.0

### [`v2.20.0`](https://togithub.com/google/error-prone/releases/tag/v2.20.0): Error Prone 2.20.0

Changes:

-   This release is compatible with early-access builds of JDK 21.

New Checkers:

-   [`InlineTrivialConstant`](https://errorprone.info/bugpattern/InlineTrivialConstant)
-   [`UnnecessaryStringBuilder`](https://errorprone.info/bugpattern/UnnecessaryStringBuilder)
-   [`BanClassLoader`](https://errorprone.info/bugpattern/BanClassLoader)
-   [`DereferenceWithNullBranch`](https://errorprone.info/bugpattern/DereferenceWithNullBranch)
-   [`DoNotUseRuleChain`](https://errorprone.info/bugpattern/DoNotUseRuleChain)
-   [`LockOnNonEnclosingClassLiteral`](https://errorprone.info/bugpattern/LockOnNonEnclosingClassLiteral)
-   [`MissingRefasterAnnotation`](https://errorprone.info/bugpattern/MissingRefasterAnnotation)
-   [`NamedLikeContextualKeyword`](https://errorprone.info/bugpattern/NamedLikeContextualKeyword)
-   [`NonApiType`](https://errorprone.info/bugpattern/NonApiType)

Fixes issues: [#&#8203;2232](https://togithub.com/google/error-prone/issues/2232), [#&#8203;2243](https://togithub.com/google/error-prone/issues/2243), [#&#8203;2997](https://togithub.com/google/error-prone/issues/2997), [#&#8203;3301](https://togithub.com/google/error-prone/issues/3301), [#&#8203;3843](https://togithub.com/google/error-prone/issues/3843), [#&#8203;3903](https://togithub.com/google/error-prone/issues/3903), [#&#8203;3918](https://togithub.com/google/error-prone/issues/3918), [#&#8203;3923](https://togithub.com/google/error-prone/issues/3923), [#&#8203;3931](https://togithub.com/google/error-prone/issues/3931), [#&#8203;3945](https://togithub.com/google/error-prone/issues/3945), [#&#8203;3946](https://togithub.com/google/error-prone/issues/3946)

**Full Changelog**: https://github.com/google/error-prone/compare/v2.19.1...v2.20.0

### [`v2.19.1`](https://togithub.com/google/error-prone/releases/tag/v2.19.1): Error Prone 2.19.1

This release fixes a binary compatibility issue when running on JDK 11, see [#&#8203;3895](https://togithub.com/google/error-prone/issues/3895)

**Full Changelog**: https://github.com/google/error-prone/compare/v2.19.0...v2.19.1

### [`v2.19.0`](https://togithub.com/google/error-prone/releases/tag/v2.19.0): Error Prone 2.19.0

New Checkers:

-   [`NotJavadoc`](https://errorprone.info/bugpattern/NotJavadoc)
-   [`StringCaseLocaleUsage`](https://errorprone.info/bugpattern/StringCaseLocaleUsage)
-   [`UnnecessaryTestMethodPrefix`](https://errorprone.info/bugpattern/UnnecessaryTestMethodPrefix)

Fixes issues:  [#&#8203;956](https://togithub.com/google/error-prone/issues/956), [#&#8203;3504](https://togithub.com/google/error-prone/issues/3504), [#&#8203;3654](https://togithub.com/google/error-prone/issues/3654), [#&#8203;3703](https://togithub.com/google/error-prone/issues/3703), [#&#8203;3731](https://togithub.com/google/error-prone/issues/3731), [#&#8203;3737](https://togithub.com/google/error-prone/issues/3737), [#&#8203;3760](https://togithub.com/google/error-prone/issues/3760), [#&#8203;3779](https://togithub.com/google/error-prone/issues/3779), [#&#8203;3796](https://togithub.com/google/error-prone/issues/3796), [#&#8203;3809](https://togithub.com/google/error-prone/issues/3809), [#&#8203;3813](https://togithub.com/google/error-prone/issues/3813)

**Full Changelog**: https://github.com/google/error-prone/compare/v2.18.0...v2.19.0

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "* * * * 0" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/solrbot/renovate-github-action)

### CODE REVIEW

**Comment by risdenk** [comment]
not sure why the previous one was closed

https://github.com/apache/solr/pull/1642

**Review by risdenk — CHANGES_REQUESTED** [review]
```
[NotJavadoc](https://errorprone.info/bugpattern/NotJavadoc)
[StringCaseLocaleUsage](https://errorprone.info/bugpattern/StringCaseLocaleUsage)
[UnnecessaryTestMethodPrefix](https://errorprone.info/bugpattern/UnnecessaryTestMethodPrefix)
```
need to evaluate these new rules and add to gradle/validation/error-prone.gradle either enabling or disabling them.

**Comment by risdenk** [comment]
Need to evaluate these rules too:

```
[InlineTrivialConstant](https://errorprone.info/bugpattern/InlineTrivialConstant)
[UnnecessaryStringBuilder](https://errorprone.info/bugpattern/UnnecessaryStringBuilder)
[BanClassLoader](https://errorprone.info/bugpattern/BanClassLoader)
[DereferenceWithNullBranch](https://errorprone.info/bugpattern/DereferenceWithNullBranch)
[DoNotUseRuleChain](https://errorprone.info/bugpattern/DoNotUseRuleChain)
[LockOnNonEnclosingClassLiteral](https://errorprone.info/bugpattern/LockOnNonEnclosingClassLiteral)
[MissingRefasterAnnotation](https://errorprone.info/bugpattern/MissingRefasterAnnotation)
[NamedLikeContextualKeyword](https://errorprone.info/bugpattern/NamedLikeContextualKeyword)
[NonApiType](https://errorprone.info/bugpattern/NonApiType)
```

**Comment by risdenk** [comment]
I'm looking at this today

**Review by risdenk — APPROVED** [review]
I went through all the added rules and disabled ones we don't need. I fixed a few failures that were minor.

**Comment by risdenk** [comment]
Hmmm well apparently locally didn't end up recompiling all the tests so doing that now :D

**Review by madrob — APPROVED** [review]

**Pull request merged**
