### PR TITLE
SOLR-15444 Document the SwedishMinimalStemmer

### PR DESCRIPTION
**Pull request by janhoy**
https://issues.apache.org/jira/browse/SOLR-15444

First stab at this. I don't attempt to describe the algorithms in detail, but link to Javadoc, where any such details can be given.

### CODE REVIEW

**Review by epugh — APPROVED** [review]
I know it needs update for merge conflicts, however the content looks good....

**Comment by epugh** [comment]
I found this PR by clicking on the *documentation* label as I was curious what might have fallen through the cracks!

**Comment by janhoy** [comment]
> I found this PR by clicking on the _documentation_ label as I was curious what might have fallen through the cracks!

I have waited because I'm not happy with the stemmer. It was benchmarked in a real life project, and this stemmer gave quite poor results by giving unusual number of false hits. This may be due to the nature of the Swedish language which is harder to handle by a few simple suffix rules than in e.g. the Norwegian language where this approach works well.

So intead of promoting and encouraging its use I have kept it undocumented. I should probably file an issue in lucene about the problems, but I won't have bandwidth to pursue it much.

**Comment by epugh** [comment]
I feel like having it just open and being stale isn't really helping...   I could see documenting the limitations in the ref guide, but pushing it forward so someone else could see it and decide to move it forward.    Or just close this PR?

**Review by epugh — APPROVED** [review]
LGTM!    I think this is a nice example of progress over perfection.

**Pull request merged**
