### PR TITLE
SOLR-17140 - 9x backport

### PR DESCRIPTION
**Pull request by gus-asf**
https://issues.apache.org/jira/browse/SOLR-17140

### CODE REVIEW

**Comment by gus-asf** [comment]
The above tidy/spotless check does not reproduce locally for me. Neither running `gradlew spotlessApply` nor running `gradlew tidy` tasks produce changes. The offending file is not changed in this change list and does not have this flaw on my local machine or in the branch I am merging? https://github.com/gus-asf/solr/blob/SOLR-17140_9x/solr/core/src/test/org/apache/solr/cloud/SolrCloudExampleTest.java#L44  ... seems to be seeing this: https://github.com/apache/solr/commit/9b9f56970b695f64769fd5dc277d3ca66819c034 which apparently broke things. *sigh* Would be nice if this PR interface identified that commits had happened, even if they don't interfere with the merge. Also @epugh maybe following a PR process when back-porting would have caught this without breaking others?

**Comment by janhoy** [comment]
I cannot reproduce either, strange. Maybe open a new JIRA for that precommit failure and proceed with this one?

**Review by sigram — APPROVED** [review]
LGTM.

**Comment by epugh** [comment]
I am working on unmessing up branch_9x with post tool..  Sigh....

**Pull request merged**
