### PR TITLE
SOLR-17480: Use --data-home everywhere

### PR DESCRIPTION
**Pull request by epugh**
https://issues.apache.org/jira/browse/SOLR-17480

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended, not available for branches on forks living under an organisation)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
@malliaridis  and ready!

**Review by malliaridis — CHANGES_REQUESTED** [review]
We should also update:
- [ ] solr/bin/solr.cmd#310 - `-t` should be `--data-home`
- [ ] solr/bin/solr.cmd#344 - `-t` should be `--data-home`
- [ ] solr/bin/solr#370 - `-t` should be `--data-home`

**Comment by dsmiley** [comment]
Just a meta comment but it's annoying to read PR description that is our template that hasn't been filled out.  Either fill it out or remove it.  Always have the JIRA link though.  Our PR template gives explicit permission for us to do so right after the JIRA link, but maybe should encourage us to.

**Review by malliaridis — APPROVED** [review]
LGTM :)

**Pull request merged**
