### PR TITLE
SOLR-16318: Use up to JDK 11 features (avoid type declaration when <> can be used)

### PR DESCRIPTION
**Pull request by cpoerschke**
# Description

* Avoid type declaration when `<>` can be used

## Pull request history

sub-set of the current #912 changes, experimentally identified with a `./dev-tools/scripts/branchSplitter.py 56842452026` script run (script included in the branch history but not in the branch content itself).

the script retains in the branch only changes which appear 'simple to review' (in this case differences that look like template argument removals or additions).

running just `./dev-tools/scripts/branchSplitter.py` identifies what could be split, running with a commit argument does the actual split by reverting back to the named commit point files that changed but not in a 'simple to review' way.

### CODE REVIEW

**Comment by epugh** [comment]
Makes sense to me...    I wonder if we need to have a conversation on dev mailing list related to when we merge this?  I know @dsmiley is interested in seeing #943 get merged soon, and this might impact that.

**Review by risdenk — APPROVED** [review]

**Review by anshumg — APPROVED** [review]

**Comment by epugh** [comment]
I would love to see these get merged, as keeping this patch up to date is going to get harder...    Do we have consensus on merging it?

**Comment by cpoerschke** [comment]
> I would love to see these get merged, as keeping this patch up to date is going to get harder... Do we have consensus on merging it?

Just resolved the merge conflict. And noting that #943 is merged now, is now more convenient then to proceed to merging here? @dsmiley WDYT?

And a question for all, we're planning to cherry-pick from `main` to `branch_9x` also for these changes, right?

**Review by dsmiley — APPROVED** [review]
I didn't review line-by-line but seems totally fine from a bit of spot-checking.

Yes, should be back-ported.

**Pull request merged**
