### PR TITLE
SOLR-16737 Http2SolrClient needs to inherit all properties when initialized with another http2 client

### PR DESCRIPTION
**Pull request by stillalex**
https://issues.apache.org/jira/browse/SOLR-16737

# Description

Copy more properties from the seed client inside the builder itself, at the same time leaving the option to overwrite properties (both before and after the seed is set to avoid any regressions).

This also fixed a regression I identified on https://github.com/apache/solr/pull/1564

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by risdenk — APPROVED** [review]

**Comment by stillalex** [comment]
thank you @risdenk for the blazing fast review!! waiting on @tflobbe to validate this, as I've discussed the changes with him over slack already (it was in the context of the #1564 regression).

**Review by tflobbe — APPROVED** [review]
LGTM!

**Comment by HoustonPutman** [comment]
@stillalex can you update the PR title to be a bit more representative of what the change is?

**Comment by stillalex** [comment]
sure @HoustonPutman. description updated, does it look better now?

**Comment by stillalex** [comment]
there seems to be a test failing on this PR, that does not fail on master, but I can't figure out why/how yet

```
./gradlew :solr:modules:ltr:test --tests "org.apache.solr.ltr.feature.TestExternalFeatures.featureExtraction_valueFeatureRequired_shouldThrowException" -Ptests.jvms=5 "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:ReservedCodeCacheSize=120m" -Ptests.seed=BC33B2384734EA2C -Ptests.file.encoding=US-ASCII
```

**Comment by tflobbe** [comment]
The test failures are not related to this PR. 
@HoustonPutman , are you ok with the updated PR title?

**Comment by stillalex** [comment]
> @HoustonPutman , are you ok with the updated PR title?

@tflobbe he added a 👍 to my comment, so I would take that as a yes? I fixed the merge conflicts too. we should be good to go here?

**Pull request merged**
