### PR TITLE
Upgrade forbiddenapis to version 3.3

### PR DESCRIPTION
**Pull request by uschindler**
This also cleans up signatures files to make use of new wildcard method signatures feature.

I did not open an issue as this is trivial and is more build maintenance. I will commit this to 9x and main branch. I can also backport to 9.0, opinions?

### CODE REVIEW

**Comment by madrob** [comment]
Can you update main/gradle/validation/forbidden-apis/commons-io.commons-io.all.txt as well?

**Comment by uschindler** [comment]
> Can you update main/gradle/validation/forbidden-apis/commons-io.commons-io.all.txt as well?

The copy methods? I don't know them, so I kept untouched.

**Comment by uschindler** [comment]
> > Can you update main/gradle/validation/forbidden-apis/commons-io.commons-io.all.txt as well?
> 
> The copy methods? I don't know them, so I kept untouched.

better now?

**Review by madrob — APPROVED** [review]

**Comment by uschindler** [comment]
9.x and main for now, or should i merge to 9.0, too? I am not uptodate how far we are with the release.

**Comment by madrob** [comment]
9x is fine, this doesn't need to be in 9.0 - we're trying to get smoke tests off the ground so less to perturb them is better

**Pull request merged**
