### PR TITLE
SOLR-15002 Upgrade httpclient to 4.5.13 and httpcore to 4.4.13

### PR DESCRIPTION
**Pull request by asalamon74**
Originally I uploaded the pull request to lucene-solr: apache/lucene-solr#2082 after the split I reupload it to solr (lucene part is already committed)

# Description

Upgrade HttpClient 4.5.13 and HttpCore 4.4.13

# Solution

Upgrade HttpClient 4.5.13 and HttpCore 4.4.13

# Tests

Unit tests

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by janhoy** [comment]
Please add a line to CHANGES.txt for 9.0 version and then we can merge this.

**Comment by janhoy** [comment]
Have you run all the Solr tests?

**Comment by asalamon74** [comment]
I have run `./gradlew check` which executes the tests as far as I know. But I'm ready to execute a `./gradlew test` if that runs more tests.

**Comment by asalamon74** [comment]
Just to be sure, I executed `./gradlew test`. I had one failure, but this test also fails with this seed on the main branch, so this is not related.

```
./gradlew test --tests StreamDecoratorTest.testParallelPriorityStream -Dtests.seed=3D9A6253043D43BB -Dtests.slow=true -Dtests.badapples=true -Dtests.locale=az-Latn -Dtests.timezone=Etc/GMT-1 -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```

**Comment by asalamon74** [comment]
I rebased it to fix the CHANGES.txt conflict. @janhoy can you please check it.

**Review by janhoy — APPROVED** [review]

**Pull request merged**
