### PR TITLE
SOLR-17026: Upgrade to Gradle 8.4

### PR DESCRIPTION
**Pull request by risdenk**
https://issues.apache.org/jira/browse/SOLR-17026

Upgrade Gradle from 7.6 to 8.4 - supports building directly with JDK 21 LTS.

https://docs.gradle.org/8.4/release-notes.html

This builds on https://github.com/apache/solr/pull/1543 and https://github.com/apache/solr/pull/1559. This is related to https://github.com/apache/lucene/issues/12655 and https://github.com/apache/lucene/pull/12650 in Apache Lucene.

Palintir consistent versions tries to copy the classpath and is fixed in 2.16.0 plugin version

```
* What went wrong:
A problem occurred configuring root project 'solr-root'.
> Cannot change the allowed usage of configuration ':solr:benchmark:compileClasspathCopy', as it was locked upon creation to the role: 'Deprecated Resolvable'.
  This role permits the following usage:
        Consumable - this configuration can be selected by another project as a dependency (but this behavior is marked deprecated)
        Resolvable - this configuration can be resolved by this project to a set of files
        Declarable Against - this configuration can have dependencies added to it (but this behavior is marked deprecated)
  Ideally, each configuration should be used for a single purpose.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
2 actionable tasks: 2 up-to-date
```

### CODE REVIEW

**Comment by risdenk** [comment]
Gradle 8.4 is done in Lucene so going to make sure this is all ready to go here too.

**Comment by risdenk** [comment]
Planning to do the same as Lucene - merge as separate commits and put tidy commit in `.git-blame-ignore-revs`

**Review by HoustonPutman — APPROVED** [review]
Thanks for doing this work!!

Are you going to wait until the issues that Dawid and Uwe found in Lucene are fixed, or are you planning on merging first?

**Comment by risdenk** [comment]
They are already fixed. I pulled the one specific to Solr into this branch already - specifically the RUNTIME JAVA env variable stuff. The other was for some of the multi release jars for vector stuff. I'll double check again too.

**Pull request merged**
