### PR TITLE
SOLR-11752: Support Accept-Encoding header to enable response gzip co…

### PR DESCRIPTION
**Pull request by HoustonPutman**
https://issues.apache.org/jira/browse/SOLR-11752

Built off the patch found in the above JIRA.

This is enabled by default but can be removed by setting `SOLR_GZIP_ENABLED=false`

### CODE REVIEW

**Comment by HoustonPutman** [comment]
Oh the only jetty-gzip setting I changed was defaulting the allowed methods to `GET,POST`, since POST is a popular way of querying with large URL params.

**Comment by epugh** [comment]
Would this let me  post  a  gzipped CSV  file directly to Solr?     unzipping a giant CSV,  then  sending it  over, was  always  painful.

**Comment by HoustonPutman** [comment]
> Would this let me post a gzipped CSV file directly to Solr? unzipping a giant CSV, then sending it over, was always painful.

I don't believe this affects data being sent to solr, only data being compressed when being sent in a response.

**Comment by HoustonPutman** [comment]
> Question: where is the Jetty gzip module defined? I expected to see a file or dir named similarly.

Well it's defined, I believe, in the `solr/server/modules/gzip.mod` file, which points to the `solr/server/etc/jetty-gzip.xml` config file. This loads in the `GzipHandler` class which is included in `jetty-server.jar`

**Comment by dsmiley** [comment]
ah; of course.  I didn't notice it in the IntelliJ PR view but I see it now.

**Pull request merged**
