### PR TITLE
SOLR-16287 : MapStream - remap tuple value(s)

### PR DESCRIPTION
**Pull request by danrosher**
https://issues.apache.org/jira/browse/SOLR-16287

# Description

Enables atomic updates for update stream by remapping a value to tuple, solr will recognise the map as an atomic update, otherwise update stream simply overwrites. Normal Solr requirements for atomic/in-place updates are still necessary.

# Solution

Remap from (k,v) => k -> newKey -> value

e.g.  with

map(<stream>,"cand_id=add-distinct") , convert stream tuples from

From:
`
{"cand_id":5718,id:123,v_i:345}
`
To:
`
{
  id:123,
  v_i:345,
  "cand_id": {
    "add-distinct": 5718
}, 
`
# Tests

e.g.
With:
`
new UpdateRequest()
            .add(id, "1", "a_ss", "foo", "b_i", "1", "c_d", "3.3", "d_b", "true")
`
Then:
`update(collection1,map(tuple(id="1",a_ss="bar"),"a_ss=add-distinct"))` will **add-distinct** 'bar' to `a_ss` to then contain ['foo','bar']

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
Docs are looking nice!

**Comment by epugh** [comment]
I sent a note to dev mailing list to see if @joel-bernstein can review it ;-)   If he can't, I can try, but it's just an area I haven't worked much in!

**Comment by epugh** [comment]
Let's give it another few days, and then, if I don't review/merge it, can you bug me?  Say Thursday???   Thanks for this @danrosher

**Comment by danrosher** [comment]
Will do @epugh . I'll be away for a week after that.

**Comment by risdenk** [comment]
@epugh ping ;) slightly more than a week or so. anything left to do here?

**Comment by epugh** [comment]
FYI, Joel is going to merge this once the new jar for streaming is completed.

**Pull request closed without merging**
