### PR TITLE
Update dependency org.apache.calcite.avatica:avatica-core to v1.23.0

### PR DESCRIPTION
**Pull request by solrbot**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [org.apache.calcite.avatica:avatica-core](https://calcite.apache.org/avatica) ([source](https://togithub.com/apache/calcite-avatica)) | dependencies | minor | `1.22.0` -> `1.23.0` |

---

### Configuration

📅 **Schedule**: Branch creation - "* * * * *" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/solrbot/renovate-github-action)

### CODE REVIEW

**Comment by risdenk** [comment]
I think we should do this in https://github.com/apache/solr/pull/1420 since calcite and avatica make sense together

**Comment by janhoy** [comment]
> I think we should do this in #1420 since calcite and avatica make sense together

We could define a custom "group" in renovate.json to define these two to be grouped in same PR in the future, like with `httpcomponents`.

**Comment by risdenk** [comment]
> We could define a custom "group" in renovate.json to define these two to be grouped in same PR in the future, like with httpcomponents.

@janhoy that would be awesome

**Comment by risdenk** [comment]
Opened https://github.com/apache/solr/pull/1429 to combine them into a group

**Pull request closed without merging**
