### PR TITLE
SOLR-14702: Fix ref-guide image to use leader-follower terms.

### PR DESCRIPTION
**Pull request by HoustonPutman**
https://issues.apache.org/jira/browse/SOLR-14702

The jira issue is long resolved and closed, but I found the old terms used in an image in the ref-guide. It's easy to see how they were missed during the mass find and replace.

I can create a new JIRA, but I think it's fine for this one-off image to just use the same jira and backport to 8.9 instead of 8.7

Ref-guide page with old image: https://solr.apache.org/guide/8_7/index-replication.html

New image: 
leader-follower-replication

### CODE REVIEW

**Review by tflobbe — APPROVED** [review]
Thanks! I didn't think about images

**Comment by ctargett** [comment]
I've got a branch in my fork where I'm working on a big re-org and I also updated the same pic to use this image: 

user-managed-replication

I can prefer yours, though, just offering as another option. I didn't have the same icons accessible to me so had to do something else with it.

There is also still an outdated image in https://solr.apache.org/guide/8_8/combining-distribution-and-replication.html which I have not fixed yet in my branch but should be done.

**Review by anshumg — APPROVED** [review]

**Comment by HoustonPutman** [comment]
Yours looks fine, and doesn't have pixelated servers! Is this refactor going to be included in 8.9 or just 9.0? If it's the later then we should probably sub this one in for now (8.x). If you are shooting for 8.9 then I'll just close this 🙂

**Comment by ctargett** [comment]
The refactor won't be in for 8.9 - I'm scrambling to try to get it done for 9.0!

I wasn't sure if there would be an 8.9 so didn't fix this image separately (then forgot about it until I saw your PR today). good idea to go ahead with yours for 8.x and then I'll change it in 9.0.

Are you going to be able to fix the other one for 8.9?

**Comment by HoustonPutman** [comment]
I'll go ahead and fix the other one as well

**Comment by HoustonPutman** [comment]
I'll also go ahead and merge here incase your refactor gets pushed back to 9.1 or later. As mentioned before, feel free to overwrite these changes with anything you have. I don't mind either way.

**Pull request merged**
