### PR TITLE
Add missing comma in TestCloudSearcherWarming's config requests' JSON.

### PR DESCRIPTION
**Pull request by cpoerschke**
(No JIRA ticket or solr/CHANGES.txt entry needed here I think.)

It seems that a

```
{
-  'add-listener' : { ... }
+  'add-listener' : { ... },
   'add-listener' : { ... }
}
```

change is appropriate for clear, well-formed JSON. But clearly it also works without the comma, and I have a strange sense of deja-vu about something like this elsewhere before, relaxed JSON parsing or something?

### CODE REVIEW

**Comment by cpoerschke** [comment]
@andywebb1975 and/or @epugh - perhaps you may be interested in this in connection with https://github.com/apache/lucene-solr/pull/2643 changes?

**Comment by janhoy** [comment]
Also surprised why the ConfigRequest does not throw an exception in the first place?

**Comment by epugh** [comment]
> Also surprised why the ConfigRequest does not throw an exception in the first place?

I chalked it up to Noggit being very lenient and allowing it through

**Comment by madrob** [comment]
Yes, it's https://github.com/apache/solr/blob/main/solr/solrj/src/java/org/noggit/JSONParser.java#L74

**Pull request merged**
