### PR TITLE
SOLR-15365: New cluster row in Grafana Dashboard

### PR DESCRIPTION
**Pull request by janhoy**
See https://issues.apache.org/jira/browse/SOLR-15365

### CODE REVIEW

**Comment by janhoy** [comment]
@thelabdude Please have a look at this. I tested in grafana and did an export through "share" button -> export -> "export for sharing externally". But the diff is all messed up, so hard to review.

I might attempt to just copy/paste the changed and added sections. Any hints?

**Comment by thelabdude** [comment]
Very cool @janhoy . I imported into a live K8s cluster running 8.8.2 with the customized exporter config and see the attached.
Not sure what that extra dimension with `=:` is on the Replica State History panel? Might have a look at that ... It's up now if you want to try it out: http://34.122.167.160:3000/d/yt5eXHbMz5/solr-dashboard-main-fixed?orgId=1&refresh=30s&from=now-5m&to=now (I'll slack you the login creds)

Screen Shot 2021-04-22 at 8 38 18 AM
Screen Shot 2021-04-22 at 8 34 44 AM

**Comment by janhoy** [comment]
> Not sure what that extra dimension with `=:` is on the Replica State History panel?

Since the state label was not there before, you have historic data points without any value. So if you change to last 15 minutes they will disappear...

Thanks for feedback. Will push a commit with some of the things we discussed on slack.

**Comment by janhoy** [comment]
Pushed changes
* state history is now 0 for active, and any non-active will stack up in the graph. Much easier to spot failures
* hide legends of replicas that have never been shard leader
* change title of the dashboard to "Solr Dashboard"

**Pull request merged**
