### PR TITLE
SOLR-16859 Missing Proxy support for Http2SolrClient

### PR DESCRIPTION
**Pull request by stillalex**
https://issues.apache.org/jira/browse/SOLR-16859

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
Is this the type of integration test that would be easier to implement via .bats test??

**Comment by stillalex** [comment]
@epugh would you mind adding a bit more detail? how would a bats test help

**Comment by epugh** [comment]
I noticed that we have a `test_ssl.bats` test that exercises Solr.   I wonder if extending those tests would help validate this fix?

**Comment by stillalex** [comment]
> I noticed that we have a test_ssl.bats test that exercises Solr. I wonder if extending those tests would help validate this fix?

no, we'd need a proxy server for testing ...unless there is some command line proxy server that is easy to integrate into a bats test.

I manually installed one on my local to smoke test this and was able to check http1 and http2 modes. @epugh would you say this is sufficient to push the code in? if there are bugs in more complex setups we can fix them as they come (as opposed to not having this feature in). I would hate to leave this PR open for much longer.

**Review by epugh — APPROVED** [review]
This looks great to me!   Someday I hope we have some way of testing out ALL the various ways of running Solr, though I can imagine that the tooling to support that might be overwhelming too ;-).  Merge it!

**Comment by stillalex** [comment]
minor update. test is failing when the SSL context is enabled, which I did not know it can happen. I spent a bit of time on this and I can not figure out how to get the Solr SocketProxy to talk to the Solr node via https - in theory it has a flag, but I could not get it working, I must be missing some key info here.
I am a bit undecided on what to do with https support. on one hand this will work for plain connections, on the other I can't get the test to setup https so I can't verify https works or not. will sit on this PR a bit more, maybe I can find a way to set this up correctly.

**Comment by stillalex** [comment]
re. SSL testing. it is very difficult to setup the exiting proxy server for this test, I think it does not actually support SSL. I've sent an email to dev list to ask for more help. @risdenk spent some time on this, thanks Kevin! I don't think it's worth while to sit on this much longer. if/when there is feedback that needs more fixes, we can address then, as needed.
Thanks @epugh, will merge this PR very soon.

**Pull request merged**
