### PR TITLE
SOLR-15854: Upgrade semver library to fix versioning constraint bugs in the PackageManager.

### PR DESCRIPTION
**Pull request by HoustonPutman**
https://issues.apache.org/jira/browse/SOLR-15910

### CODE REVIEW

**Comment by madrob** [comment]
This is kind of a pain, but I’d like to see the commits split into a clean fork and then our changes separately. Also, I don’t think we repackage the files, see org.noggit

**Review by janhoy — COMMENTED** [review]
I looked forever too without finding a good, maintained library. I checked the forks etc. Also checked a few Kotlin libs but they tend to have less features. 

I really don't like forking that amount of code into the project, it will for sure rot in here.

**Comment by janhoy** [comment]
There are already 11 contributors to https://github.com/vdurmont/semver4j. Have you tried contacting them? Perhspa if we submit a PR for https://github.com/vdurmont/semver4j/issues/48 and ping a few of the devs, we can help trigger a new release? Two years old can also mean that it is mature and don't need that many updates...

**Comment by epugh** [comment]
Maybe for an adjacent library, just having a fixed version that lives as someone's personal fork in Github would also be okay?  Versus bringing in this code to the Solr project itself.

Github makes it too easy to get lots of forks that all end up vaguely unmaintained, and I wish it encouraged a cluster of forks like what we see for semver to somehow come back together to a single maintained approach.   Oh wait...  _community over code_ ;-)

**Comment by HoustonPutman** [comment]
Completely agree with both of you that not forking would be the best path forward. It's hard company-policy-wise for me to move forward with either of those options, but I would appreciate either of you taking it up!

**Comment by janhoy** [comment]
I'll not veto the code copy, if you clearly mark it and open, say, a blocker JIRA for 10.0 or something to replace it with something that is maintained...

**Comment by risdenk** [comment]
Looks like this was fixed and forked - https://github.com/semver4j/semver4j potentially?

**Comment by risdenk** [comment]
I put up a new PR that builds on this original change: https://github.com/apache/solr/pull/1077

**Comment by risdenk** [comment]
I updated this PR with my changes. I realized I didn't need a new PR since I was able to merge main and then use semver4j.

I need to fix a few things still solr/CHANGES.txt and maybe some other minor things, but overall this is ready to go.

**Review by janhoy — APPROVED** [review]
Cool, looks good. Fingers crossed that this gets maintained. GitHub projects cold learn a lot form ASF wrt adding committers and caring about project community health.

**Pull request merged**
