### PR TITLE
SOLR-16600 Use Array instead of ObjectList when dealling with paralle…

### PR DESCRIPTION
**Pull request by stillalex**
Use Array instead of ObjectList when dealling with parallelCachesRefresh in CloudSolrClient

https://issues.apache.org/jira/browse/SOLR-16600

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by stillalex** [comment]
@epugh PR for SOLR-16600 please review

**Comment by epugh** [comment]
This makes sense to me, though I wonder if others might chime in who have stronger opinons?    @stillalex I wonder if, for bonus points, you'd like to add this pattern to our forbidden-apis check?   Seems like this change is something that we should be continuing to check for in the future?   So that it doesn't come back?    If you want to add it to forbidden-apis, that would be great, and let's leave it open.  Otherwise, if you don't want to do that, then I'll merge once I get another LGTM!  Just let me know!

**Review by epugh — APPROVED** [review]
LGTM.    See my desire to add this to forbidden apis check ;-)

**Comment by stillalex** [comment]
@epugh thank you for the review! I don't know much about the forbidden api check, could you link to some reading resource? just on the surface, this PR is a minor improvement on existing code, I would not add too much strictness to it.

**Comment by epugh** [comment]
I've only seen it used in solr, but the gradle plugin is https://github.com/policeman-tools/forbidden-apis and it's run as part of the precommit check.   

I'll leave this open for another day or so and then merge ;-)

**Comment by stillalex** [comment]
@epugh could we merge this one?

**Review by dsmiley — APPROVED** [review]
+1 Looks good; thanks.
BTW no JIRA or CHANGES.txt is necessary for little internal refactoring like this.

**Pull request merged**
