### PR TITLE
SOLR-14540: add an example clarifying the use case.

### PR DESCRIPTION
**Pull request by mkhludnev**
https://issues.apache.org/jira/browse/SOLR-14540

# Description

Adding one sentence clarifying overall usecase as suggested by community.

### CODE REVIEW

**Comment by janhoy** [comment]
Are you planning to merge this? The JIRA for 8.10 is already closed...

**Comment by epugh** [comment]
@mkhludnev I spotted a double space, so removed it, then changed the wrapping.

**Comment by janhoy** [comment]
The JIRA for this PR is closed. Should this PR also be closed then?

**Comment by epugh** [comment]
This is a nice edit, the JIRA was closed a while ago, then @mkhludnev added this on top of it.  I went ahead and merged it!

**Pull request merged**
