### PR TITLE
SOLR-13243: Correct initial capacity of ops

### PR DESCRIPTION
**Pull request by heythm**
https://issues.apache.org/jira/browse/SOLR-13243

Quick improvement for initial ops capacity

### CODE REVIEW

**Review by madrob — COMMENTED** [review]
Why don't we do List.of and not worry about the sizing?

**Comment by heythm** [comment]
I think it's more readable this way, but it's still a preference.

**Comment by stillalex** [comment]
I think @madrob's proposal fits better, a List.of() looks cleaner to me too.

**Review by risdenk — APPROVED** [review]

**Comment by risdenk** [comment]
Thanks @heythm

**Pull request merged**
