### PR TITLE
SOLR-15414 Use ConfigSetAPI to list configs on AdminUI

### PR DESCRIPTION
**Pull request by NazerkeBS**
https://issues.apache.org/jira/browse/SOLR-15414

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [ ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
I love this!

**Comment by epugh** [comment]
I just tested it, and LGTM.

**Comment by NazerkeBS** [comment]
@epugh Thank you Eric for taking a look! Could you merge it please?

**Comment by epugh** [comment]
Sure..    I typically only merge to 9, because I haven't really figured out the extra steps to backport to branch_8x in the other repo..   Is that okay?

**Comment by NazerkeBS** [comment]
I think it is ok to have it on 9

**Pull request merged**
