### PR TITLE
SOLR-15083: prometheus-exporter incorrect metric namings

### PR DESCRIPTION
**Pull request by mlbiscoc**
https://issues.apache.org/jira/browse/SOLR-15083

# Description

"solr_metrics_jvm_os_cpu_time_seconds", "solr_metrics_node_time_seconds_total", "solr_metrics_core_time_seconds_total" metric has seconds in its name but the metric is incorrectly converting the metric to microseconds. (Nanoseconds / 1000)

# Solution

Change the math conversion in the prometheus_exporter default config to export the metric into seconds (nanoseconds / 10^9 = seconds)

# Tests

Manual testing with prometheus and grafana

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by janhoy — APPROVED** [review]
Thanks. I've seen these insanely large numbers in Grafana graphs, think this is the cure.

You may want to add a line to CHANGES.txt, for version 9.3.0

**Comment by mlbiscoc** [comment]
> 
Thanks @janhoy for quick review! Will add to CHANGES.txt

**Comment by mlbiscoc** [comment]
Is there a reason the Crave.io test is failing? Did I add to CHANGES.txt incorrectly?

**Comment by epugh** [comment]
At least according to github, the Changes.txt file has conflicts...     CHANGES.txt is a bit of a problem child in that it seems to constantly have conflicts that need resolving on a regular basis as other commits happen ;-(.

**Comment by mlbiscoc** [comment]
Ah ok thanks for the info, Eric. Will try to keep it updated so the checks can go through.

**Comment by mlbiscoc** [comment]
Solr Tests seem to be failing from LTR but run fine locally. Is this still somehow related to my PR or a known issue?

`gradlew :solr:modules:ltr:test --tests "org.apache.solr.ltr.feature.TestRankingFeature.testParamsToMap" -Ptests.jvms=96 "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:ReservedCodeCacheSize=120m" -Ptests.seed=9066B014A217BFC5 -Ptests.file.encoding=US-ASCII`

**Comment by mlbiscoc** [comment]
Looks like other check tests failed at LTR as well. For example this change that was only ref-doc change:
https://github.com/apache/solr/actions/runs/4808042532/jobs/8558639488

**Pull request merged**
