### PR TITLE
SOLR-16899: Do not statically register ops in CoreAdminHandler

### PR DESCRIPTION
**Pull request by pvcnt**
https://issues.apache.org/jira/browse/SOLR-16899

# Description

Since Solr 9.1 and [SOLR-16282](https://issues.apache.org/jira/browse/SOLR-16282), one may register custom CoreAdminOp in solr.xml. Custom CoreAdminOp are stored in a static Map in CoreAdminHandler.

Because this map is static, it prevents from starting several instances of Solr in the same JVM that register custom core admin operations. It may notably happen in unit tests.

# Solution

The map containing CoreAdminOp's (default and custom) should not be static.

# Tests

No additional test, but all existing tests should pass.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by stillalex** [comment]
I think is it not completely correct to say `Because this map is static`, because it was static before the change. I think the culprit is the extra verification that throws exception which can clash for tests running multiple instances in the same jvm (what was happening before, a silent override?).
@cpoerschke this PR looks good to me. you were the one that merged SOLR-16282 so could you also take a look?
what I think is still missing is a test showing the exception (and fix).

**Comment by cpoerschke** [comment]
Yes, `CoreAdminHandler.opMap` remaining static when there could be custom actions seems unintended.

**Comment by stillalex** [comment]
thank you for confirming @ctargett.
@pvcnt what name should I use in the CHANGES.txt entry for the credit?

**Comment by pvcnt** [comment]
@stillalex You may use "Vincent Primault". Thanks!

**Pull request merged**
