### PR TITLE
Emphasize the meaning of using replicas without sharding

### PR DESCRIPTION
**Pull request by jebnix**
https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

Personally, that confused me very much. I just didn't understand how is it possible to use Solr without shards but only replicas.
It took some time until I realized it was just talking about maintaining a kind-of-standalone cluster.

# Solution

Emphasize that using Solr without shards isn't a relevant choice for large production clusters.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by mkhludnev — APPROVED** [review]

**Comment by noblepaul** [comment]
TBH, I can't see any value add from adding that one line

**Comment by jebnix** [comment]
@noblepaul just for emphasizing the situation and the importance of sharding for new users

**Comment by janhoy** [comment]
I don't either think this line adds anything. Close?

**Comment by epugh** [comment]
> I don't either think this line adds anything. Close?

I can go with that.  I'd like to see some more information (separately) about how to think about replicas and scaling and all of that..

**Pull request closed without merging**
