### PR TITLE
SOLR-16890: More test cases for Coordinator node role

### PR DESCRIPTION
**Pull request by patsonluk**
https://issues.apache.org/jira/browse/SOLR-16890

# Description

Adding more test cases to verify the Coordinator node role introduced in Solr 9
# Solution

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by patsonluk** [comment]
Added extra unit test cases for Coordinator node. @noblepaul would you mind to take a look? Many thanks!

**Comment by HoustonPutman** [comment]
**testConfigset** is failing pretty consistently on Jenkins (50%): https://ci-builds.apache.org/job/Solr/job/Solr-Check-main/8012/testReport/org.apache.solr.search/TestCoordinatorRole/testConfigset/

http://fucit.org/solr-jenkins-reports/failure-report.html

**Comment by patsonluk** [comment]
> **testConfigset** is failing pretty consistently on Jenkins (50%): https://ci-builds.apache.org/job/Solr/job/Solr-Check-main/8012/testReport/org.apache.solr.search/TestCoordinatorRole/testConfigset/
> 
> http://fucit.org/solr-jenkins-reports/failure-report.html

Thanks for letting me know @HoustonPutman I'm looking at it!

**Comment by patsonluk** [comment]
@HoustonPutman I have created a fix PR https://github.com/apache/solr/pull/1939, would u mind to review it?

I have to use `HttpSolrClient` instead of `Http2SolrClient` as only the former exposes the internal http client which we can conveniently use for our test purpose. Please let me know if there's a better way to approach this.

Many thanks again!! 😊

**Pull request merged**
