### PR TITLE
SOLR-15804 Allow content-types with ;charset in ShowFileRequestHandler

### PR DESCRIPTION
**Pull request by janhoy**
https://issues.apache.org/jira/browse/SOLR-15804

### CODE REVIEW

**Comment by janhoy** [comment]
To reveiewers: 
So the whole idea of the original content-type screening was to avoid Solr presenting a file with an HTML content-type to the browser which would then render that HTML, which is clearly not the intention of the Files Admin UI either. So we silently fall-back `text/html` content-type to `text/plain` and only accept well-known content types.

The issue was that the Admin UI always attaches `;charset=utf-8` to the contentType param, and we did not accommodate for that, also I did not test the UI manually (stupid). This PR fixes this by checking the raw content-type, including lowercasing and we also accept `text/xml`.

It works well in 9.0 Admin UI for the files that I tested. The only thing that I see could still break is if a config-set contains some file that the Admin UI decides to request with an unknown content-type, then the 400 error would not be handled gracefully and result in the red error box on top with no message (that's another bug I think, that the error from the request is not rendered in the UI). But what I can see from [files.js](https://github.com/apache/solr/blob/main/solr/webapp/web/js/angular/controllers/files.js), it will not happen, as the UI only handles xml, html, js, json and css explicitly, and everything else requests `text/plain`. Perhaps the UI should map html to `text/plain` here since that is what will happen on the backend anyway.

**Review by epugh — APPROVED** [review]
Seems good...  Only thought I had was that the adding of the mimetype here seemed odd, should it be added in the jetty config?  Either `web.xml` or `webdefault.xml`?  On the other hand, if this only matters in this handler, maybe that just confuses thinks more.

**Comment by janhoy** [comment]
I tested with 8.10, and put a css file in the config-set. It did not display well, and caused a JS stacktrace
Skjermbilde 2021-11-17 kl  17 11 40
But I think that is unrelated to this and has to do with the syntax highlighter we use. I'll file another JIRA, although CSS files here should not really happen...

**Comment by dsmiley** [comment]
Given Solr has a proper ConfigSet API these days, I don't think we should worry about trying to support apps using ShowFile to download.

**Comment by janhoy** [comment]
> Given Solr has a proper ConfigSet API these days, I don't think we should worry about trying to support apps using ShowFile to download.

Absolutely.

I'll fix up the css highlighting bug (use txt instead), request `.html` with `text/xml`, test in main and then merge.

**Comment by janhoy** [comment]
I tested a bit more, and frontend uses `text/javascript` which is not a standard content-type, so it would get 400 error on those. I change files.js to use `application/javascript`, and also the xml types -> `application/xml` even if backend also supports `text/xml`.

**Pull request merged**
