### PR TITLE
SOLR-16142: Fix Admin UI's spatial parameter generation.

### PR DESCRIPTION
**Pull request by cpoerschke**
https://issues.apache.org/jira/browse/SOLR-16142

### CODE REVIEW

**Comment by cpoerschke** [comment]
Perhaps last minute candidate for 8.11.2 if this fix is accurate? cc/fyi @madrob

**Review by epugh — APPROVED** [review]
LGTM

**Comment by cpoerschke** [comment]
Hmm, I'm not very familiar with this code but from trying to learn via the #122 diff there is I see at https://github.com/apache/solr/blob/releases/solr/9.0.0/solr/webapp/web/js/angular/controllers/query.js#L145 some ` getDependentFields("spatial")` logic which might break if the `spatial.` prefix is simply dropped? So change/fix might be a little more involved?

**Comment by epugh** [comment]
okay, digging in some more

**Comment by cpoerschke** [comment]
> okay, digging in some more

so amending the `purgeParams` calls works I think, making the `spatial` checkbox similar to the `dismax` and `edismax` dropdown options. WDYT?

**Pull request merged**
