### PR TITLE
SOLR-16879: add dedicated thread pool for expensive admin operations

### PR DESCRIPTION
**Pull request by psalagnac**
https://issues.apache.org/jira/browse/SOLR-16879

# Description

This is a simpler change compared to #1761.

# Solution

Add a dedicated thread pool in `CoreAdminHandler` for expensive admin operation. Since it has a limited number of threads, this guarantee we don't execute too many concurrent expensive operations.

# Tests

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by stillalex** [comment]
this looks very good! much easier to follow along!
the only minor suggestion would be to add the `isExpensive()` method to implementors of `CoreAdminAPIBase` which look like candidates for expensiveness: `BackupCoreAPI`, `RestoreCoreAPI` maybe other too but I don't really know.

**Review by stillalex — APPROVED** [review]

**Comment by psalagnac** [comment]
> this looks very good! much easier to follow along!
> the only minor suggestion would be to add the `isExpensive()` method to implementors of `CoreAdminAPIBase` which look like candidates for expensiveness: `BackupCoreAPI`, `RestoreCoreAPI` maybe other too but I don't really know.

Thanks for pointing this @stillalex . My understanding is the are backup/restore operations for API V2, correct?
Yes, they definitely should also be marked as expensive operations. Will change this.

**Review by dsmiley — CHANGES_REQUESTED** [review]
Nice; I like how you used different commits to clarify the different elements of what you did.

I would add "SplitOp" to expensive -- it is _at least_ as expensive as backup or restore!

**Comment by psalagnac** [comment]
Thanks for you feedback. I added marked more operation as expensive.

**Comment by psalagnac** [comment]
Suggested CHANGES.txt line:

> SOLR-16879: Limit the number of concurrent expensive core admin operations by running them in a dedicated thread pool. Backup, Restore and Split are expensive operations.

**Pull request merged**
