### PR TITLE
Update transaction log options descriptions

### PR DESCRIPTION
**Pull request by radu-gheorghe**
If my understanding of the UpdateLog code is right (I'm looking at this bit in particular: https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/update/UpdateLog.java#L506-L519), then:
- new transaction logs (files) are added for each [hard] commit
- old transaction logs are removed if there are more than maxNumLogsToKeep of them OR if we have more than numRecordsToKeep records in total

This means numRecordsToKeep is not per file, but across all the files.

https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

Please provide a short description of the changes you're making with this pull request.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [ ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by radu-gheorghe** [comment]
I'm not sure if a Jira is needed for this small change, but I can surely create one if needed. Thanks!

**Comment by janhoy** [comment]
I skimmed the code and believe you are right. Do you agree @andyetitmoves ?

**Comment by janhoy** [comment]
And I wouldn't bother with a JIRA for just a one-line refguide correction.

**Comment by andyetitmoves** [comment]
> I skimmed the code and believe you are right. Do you agree @andyetitmoves ?

Yep, that's correct.

**Comment by janhoy** [comment]
Thanks!

**Pull request merged**
