### PR TITLE
SOLR-15410: Always use -Xverbosegclog for OpenJ9

### PR DESCRIPTION
**Pull request by colvinco**
# Description
See [SOLR-15410](https://issues.apache.org/jira/browse/SOLR-15410). Always set `-Xverbosegclog` when using Open J9, regardless of Java major version, since `-Xlog:gc` is not recognised by Open J9 0.24.0+ (unless `-XX:+LegacyXlogOption` is set) while `-Xverbosegclog` is supported in all Open J9 versions.

# Solution
Change the Java 9+ GC_LOG_OPTS check to also check the JVM vendor. I've also updated the vendor matching to match both "IBM J9" and "OpenJ9" explicitly. Previously `solr.cmd` was matching both by accident because of the use of `findstr`, while `solr` was only matching "IBM J9". Since "IBM J9" is now known as "OpenJ9" I've replaced the "IBM J9" vendor name references with "OpenJ9"
JAVA_BUILD in solr.cmd isn't read since 8ae3304 so removed it too.

# Tests

Manually checked with Open J9 jdk-11.0.10+9, jdk-11.0.8+10, jdk-9.0.4+12 and Hotspot jdk-11.0.10+9

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ ] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
@risdenk just a mild ping to remind you about testing this on windows, and I'm going to try and test it on unix today ;-)

**Comment by risdenk** [comment]
@epugh  yup thanks on my list will try to get to it early this week.

**Review by risdenk — APPROVED** [review]
As far as I can tell this fixes the error on Windows. I tested with the following on Windows 10 in a Windows Sandbox with and without this PR.

These were downloaded from https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=openj9
* OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9
* OpenJDK11U-jdk_x64_windows_openj9_11.0.8_10_openj9-0.21.0
* OpenJDK11U-jdk_x64_windows_openj9_11.0.11_9_openj9-0.26.0

However during startup I saw the following error for openj9_11.0.11

```
2021-05-27 23:01:24.069 ERROR (main) [   ] o.a.s.c.SolrCore null:java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.jdk.internal.reflect")
```

I only ran `.\bin\solr start -c -f` and it didn't look like Solr came up. This doesn't seem related to this change.

The other weird thing not changed by this PR, but I think related to this java version parsing is:

https://github.com/apache/solr/pull/131/files#diff-118de7ae5d9fc032e479321cb4d3ee62ceb68e9f3c845292b44c5e14c0f769cfR2058

These two `echo` lines end up printing out  the java version and what was parsed:

```
  echo "java version info is !JAVA_VERSION_INFO!"
  REM Extract the major Java version, e.g. 7, 8, 9, 10 ...
  for /f "tokens=1,2 delims=._-" %%a in ("!JAVA_VERSION_INFO!") do (
    echo "Extracted major version is %%a"
```

Either way the change fixes the error message about gc logs for openj9 and doesn't break hotspot jdk 11.

**Comment by colvinco** [comment]
@epugh did you get a look at it on unix?

**Review by epugh — APPROVED** [review]
I got lost in trying to figure OpenJDK versus OpenJ9, figured out that OpenJ9 is just an engine.

**Comment by epugh** [comment]
I just re-read @risdenk message, as I am getting the same exception on OSX with the `jdk-11.0.11+9` setup.   

I feel a bit weird merging this PR when Solr doesn't start....   Thoughts?

**Comment by epugh** [comment]
I built my Solr with `11.0.3, x86_64:	"AdoptOpenJDK 11"	/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home` and then started Solr, and it started just fine.

I swapped to the J9, and I get the access errors. 

`    11.0.11, x86_64:	"OpenJDK 11.0.11"	/Library/Java/JavaVirtualMachines/jdk-11.0.11+9/Contents/Home`

@risdenk you have more experience then I do, should we merge this as "not related to the other issue" and then open a new JIRA issue for the start up problem?  @colvinco do you see the same issue on _main_?   Maybe it's one of those things where it works on _branch_8x_ but due to other changes it doesn't work on _main_?

**Comment by colvinco** [comment]
Hi yes, sorry I hadn't checked on main. I see the same thing on main on Windows
```
o.a.s.c.SolrCore null:java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "accessClassInPackage.jdk.internal.reflect")
```
It works on branch_8x.

So yeah, I think another issue to deal with the ACE on main would be best.

**Comment by epugh** [comment]
@colvinco can you create the other JIRA?   Thanks!  I'll look at merging htis now.

**Comment by colvinco** [comment]
Thanks. I've raised [SOLR-15464](https://issues.apache.org/jira/browse/SOLR-15464)

**Pull request merged**
