### PR TITLE
SOLR-16232: Fix EnvVar usage in bin/solr

### PR DESCRIPTION
**Pull request by HoustonPutman**
https://issues.apache.org/jira/browse/SOLR-16232

### CODE REVIEW

**Review by madrob — COMMENTED** [review]
Do you have tests for these? For some of them, like export and package, I thought that we explicitly did want word splitting?

**Comment by HoustonPutman** [comment]
> For some of them, like export and package, I thought that we explicitly did want word splitting?

@madrob So we do want word splitting, but by what the user split by in the first place. That's what `"$var[@]"` does, it basically just puts quotes around the original arguments provided by the user. Using just `$var[@]` will re-split, even if the user has provided an argument like `-query "*:* - name:Mike"`, that will be resplit to `"-query" "*:*" "-" "name:Mike"`, which is definitely not what we want

I have added a simple test for export that shows this. Not sure it's completely necessary for package, but I guess I could if we really need to.

**Comment by risdenk** [comment]
It might be worth looking at `solr/bin/solr` with `shellcheck` - https://github.com/koalaman/shellcheck I ran `main` `bin/solr` through shellcheck and a few of the things you fixed are mentioned there. might help to focus on `errors` and maybe `warnings` since shellcheck can be noisy.

ie: `shellcheck --severity=error solr/bin/solr`

resulted in the following on `main`:

```

In solr/bin/solr line 833:
  run_tool package -solrUrl "$runningSolrUrl" $@
                                              ^-- SC2068 (error): Double quote array expansions to avoid re-splitting elements.


In solr/bin/solr line 879:
    if [ -n "{$JSTACK:-}" ]; then
             ^-- SC2157 (error): Argument to -n is always true due to literal strings.


In solr/bin/solr line 1436:
  run_tool export $@
                  ^-- SC2068 (error): Double quote array expansions to avoid re-splitting elements.


In solr/bin/solr line 1441:
  run_package $@
              ^-- SC2068 (error): Double quote array expansions to avoid re-splitting elements.


In solr/bin/solr line 1577:
  run_tool auth ${AUTH_PARAMS[@]} -solrUrl "$SOLR_URL_SCHEME://$SOLR_TOOL_HOST:${AUTH_PORT:-8983}/solr" -authConfDir "$SOLR_HOME" $VERBOSE
                ^---------------^ SC2068 (error): Double quote array expansions to avoid re-splitting elements.


In solr/bin/solr line 2201:
    echo -e "    JAVA_MEM_OPTS   = ${JAVA_MEM_OPTS[@]}"
                                   ^-----------------^ SC2145 (error): Argument mixes string and array. Use * or separate argument.


In solr/bin/solr line 2202:
    echo -e "    GC_TUNE         = ${GC_TUNE[@]}"
                                   ^-----------^ SC2145 (error): Argument mixes string and array. Use * or separate argument.


In solr/bin/solr line 2203:
    echo -e "    GC_LOG_OPTS     = ${GC_LOG_OPTS[@]}"
                                   ^---------------^ SC2145 (error): Argument mixes string and array. Use * or separate argument.


In solr/bin/solr line 2207:
      echo -e "    CLOUD_MODE_OPTS = ${CLOUD_MODE_OPTS[@]}"
                                     ^-------------------^ SC2145 (error): Argument mixes string and array. Use * or separate argument.


In solr/bin/solr line 2211:
      echo -e "    SOLR_OPTS       = ${SOLR_OPTS[@]}"
                                     ^-------------^ SC2145 (error): Argument mixes string and array. Use * or separate argument.


In solr/bin/solr line 2220:
      echo -e "    REMOTE_JMX_OPTS = ${REMOTE_JMX_OPTS[@]}"
                                     ^-------------------^ SC2145 (error): Argument mixes string and array. Use * or separate argument.

For more information:
  https://www.shellcheck.net/wiki/SC2068 -- Double quote array expansions to ...
  https://www.shellcheck.net/wiki/SC2145 -- Argument mixes string and array. ...
  https://www.shellcheck.net/wiki/SC2157 -- Argument to -n is always true due...
```

**Comment by HoustonPutman** [comment]
Yeah, this came from the shellcheck errors, after I initially found the `JSTACK` error myself.

**Pull request merged**
