### PR TITLE
SOLR-15280 Misleading error message in HdfsDirectoryFactory

### PR DESCRIPTION
**Pull request by asalamon74**
# Description

Misleading error message in HdfsDirectoryFactory

# Solution

Fixing the error message.

# Tests

Unit tests
# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by janhoy — APPROVED** [review]

**Comment by janhoy** [comment]
If you want credit in CHANGES.txt then please add a line to the 9.0 section of that file

    SOLR-15280 Fixed misleading error message in HdfsDirectoryFactory (András Salamon via janhoy)

**Comment by asalamon74** [comment]
Solved the conflict caused by SOLR-15329. @janhoy can you please check it.

**Comment by madrob** [comment]
@janhoy do you want to merge? If not, I'll update the changes entry and merge it later this week.

**Comment by asalamon74** [comment]
Thanks for picking this up @madrob

**Pull request merged**
