### PR TITLE
Remove the Before SolrCloud section, and expand the supported feature…

### PR DESCRIPTION
**Pull request by jebnix**
…s section instead

https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

There is a pretty confusing section that explains what existed before SolrCloud. That's pretty redundant now since this is pretty old.

# Solution

Remove the Before SolrCloud section, and expand the supported features section instead

# Tests

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by janhoy** [comment]
The old "User Managed" mode is still supported (https://solr.apache.org/guide/solr/latest/deployment-guide/user-managed-distributed-search.html), so I would not remove it. Guess it's there to give a reason why SolrCloud was introudced. 

But perhaps it should be reworded and make it clear that the feature still exists? "Before SolrCloud, solr only supported Distributed Search through <User managed mode>(link)....."

**Comment by janhoy** [comment]
@jebnix Do you want to give it a final stab?

**Review by epugh — APPROVED** [review]
LGTM.    I agree that providing a bit of a history lesson in here is a bit odd!

**Comment by epugh** [comment]
> The old "User Managed" mode is still supported (https://solr.apache.org/guide/solr/latest/deployment-guide/user-managed-distributed-search.html), so I would not remove it. Guess it's there to give a reason why SolrCloud was introudced.
> 
> But perhaps it should be reworded and make it clear that the feature still exists? "Before SolrCloud, solr only supported Distributed Search through (link)....."

So I am re-reading things...  And we start out with a section "Solr Cluster Types" that talks about the various options.   Then you get the section on "User-Managed Clusters" and then "SolrCloud Clusters".    I feel like if you are this page, you don't need this content, because the differences is covered in "Solr Cluster Types", we are just derailing someone at this point...    Thoughts?  Does that change your mind on merging this PR?

**Comment by janhoy** [comment]
I have not reviewed the other pages related to cluster types, but trust you that this might be redundant. It's a pity that doc improvements get stalled. Feel free to land it.

**Comment by epugh** [comment]
@jebnix  thanks for this, and don't forget to ping me on any outstanding PR's you might have ;-)

**Comment by epugh** [comment]
If you are looking for an idea...  We want to rename "User Managed" to "standalone" through the ref guide ;-).   And move the SolrCloud examples above the standalone examples instead of below them ;-)

**Pull request merged**
