### PR TITLE
SOLR-10059: add SearchHandlerAppendsCloudTest

### PR DESCRIPTION
**Pull request by cpoerschke**
https://issues.apache.org/jira/browse/SOLR-10059

### CODE REVIEW

**Comment by epugh** [comment]
@cpoerschke I am going through various issues that I had assigned to me, to catch up on where they are.   Is there any reason not to merge this test?  I ran it, and it passes...   Is the idea that once SOLR-10059 is merged, you would change the test to confirm that the bug ISN'T present?   

BTW, I love the scheme field names you picked ;-)

**Comment by cpoerschke** [comment]
> ... Is there any reason not to merge this test? ...

Thanks for the ping!

From (very vague) memory the test/code behaviour was non-deterministic and part-mysterious, though maybe the `continue;` with the `// SOLR-10059: sometimes (but not always) filterQueriesList contains duplicates` fully accounts for that. Let me go check.

**Comment by cpoerschke** [comment]
> ... maybe the `continue;` with the `// SOLR-10059: sometimes (but not always) filterQueriesList contains duplicates` fully accounts for that. ...

Looks like it does. Also just merged latest`origin/main` into the PR branch.

**Review by epugh — APPROVED** [review]
LGTM.   I look forward to getting the other PR in to ensure no duplicates!

**Comment by epugh** [comment]
Awesome!

**Pull request merged**
