### PR TITLE
SOLR-16127 Ordered Executor orphans locks

### PR DESCRIPTION
**Pull request by madrob**
https://issues.apache.org/jira/browse/SOLR-16127

I'm not sure if the changes in #776 will fix this or not, but this is a test that fails with the current code.

### CODE REVIEW

**Comment by HoustonPutman** [comment]
Does the test fail or does it have leaking threads? My fixes wouldn't fix anything other than leaking threads

**Comment by madrob** [comment]
If fails because I explicitly check for a leaked thread. But it's not leaked by the delegate executor, it's just a thread that never finished executing because it never gets submitted.

**Review by HoustonPutman — APPROVED** [review]
Looks like a good test & fix to me

**Comment by CaoManhDat** [comment]
Looks good to me as well. It is always better to make utility classes safer and reliable.

**Review by CaoManhDat — APPROVED** [review]

**Pull request merged**
