### PR TITLE
SOLR-16210: skip Antora task for lift builds

### PR DESCRIPTION
**Pull request by chriswininger**
https://issues.apache.org/jira/browse/SOLR-16210

# Description

The antora site task is failing when trying to compile solr to prepare for lift static analysis. This prevents some tools from being able to produce results.

# Solution

This will skip the antora task which was failing during the lift
build process by adding a line of configuration to the .lift.toml file

# Tests

There should be no noticeable changes to the behavior of solr its self, but more lift results should be available and, under the tool results panel you should see that Infer ran successfully

image

*Note: As a result lift may claim this pr introduces new issues :-)*

### CODE REVIEW

**Comment by dsmiley** [comment]
I'm glad it helps fix the problem.
* Is "clean" actually necessary?  In general I think this is a habit we all bring from our Ant/Maven knowledge that Gradle should ideally make obsolete.
* Is "assemble" doing too much that Lift doesn't need?  It will create tar.gz etc. and I suspect Lift just needs to look at class files; not even JARs?

**Comment by HoustonPutman** [comment]
I agree that assemble is likely too heavy here. We already run `gradle check` which will do the site checking, and most checks on the `assemble` stuff. But I don't know what lift uses.



> * Is "clean" actually necessary?  In general I think this is a habit we all bring from our Ant/Maven knowledge that Gradle should ideally make obsolete.

If lift is looking at artifacts (tgzs) then clean might be necessary, because old artifact versions in the packaging release folder will not be deleted when `gradle assemble` is run. (This is only true when you are building a new solr version than what exists in the packaging releases folder, so we probably won't hit this often since this is just run on `main`)

**Comment by HoustonPutman** [comment]
Maybe we use `installDist` instead of `assemble` then? It will create the solr release binary and untar it. I'm not sure we need anything else that "assemble" entails. And it's easier than keeping a list of things that we don't want.

**Comment by dsmiley** [comment]
If the `jar` files are all that is needed by Lift then just do `gradlew jar`.  It won't run tests or do Antora stuff.

**Comment by chriswininger** [comment]
> If the `jar` files are all that is needed by Lift then just do `gradlew jar`. It won't run tests or do Antora stuff.

Let me consult with some folks on our team. I mostly work with maven. If the jar command works and is available across gradle projects then there is an opportunity to fix this entirely on our end and avoid similar problems with other users.

**Comment by chriswininger** [comment]
> If the `jar` files are all that is needed by Lift then just do `gradlew jar`. It won't run tests or do Antora stuff.

I had a discussion with the team. It sounds like we are not quite ready to switch to jar as the default across all gradle projects. There were some historic reasons for favoring assemble; though we may revisit that decision :-)

In the case of solr it definitely makes sense, so, I've updated this pr to just use `./gradlew jar`

**Comment by HoustonPutman** [comment]
This looks good to me, as long as lift doesn't want the dependency jars downloaded as well.

**Comment by chriswininger** [comment]
> This looks good to me, as long as lift doesn't want the dependency jars downloaded as well.

nope, not with current tools in any event.

**Pull request merged**
