### PR TITLE
SOLR-14444: Ref Guide re-organization

### PR DESCRIPTION
**Pull request by ctargett**
https://issues.apache.org/jira/browse/SOLR-14444

# Description

This PR overhauls the entire Ref Guide in several major ways:

- New organizational structure
- Renamed and removed several pages
- Split the Solr Tutorial
- Standardized SolrCloud/standalone/legacy/leader-follower terminology
- Introduced several new formatting elements and approaches

See the wiki page for discussion of all the changes: https://cwiki.apache.org/confluence/display/SOLR/Ref+Guide+Re-Org+2021

### CODE REVIEW

**Review by janhoy — CHANGES_REQUESTED** [review]
I quickly browsed around, then built the HTML guide and ran a dead-link checker.

I noticed that the links generated to Lucene JavaDoc have this format: https://lucene.apache.org/core/9_0_0-prerelease5/core/org/apache/lucene/search/similarities/TFIDFSimilarity.html. The -prerelease5 suffix should probably not be there (and will not either of course in the final release), not sure if it needs change.

Here is the list of broken links
```
http://logging.apache.org/log4j/log4j-2.13.2/ (HTTP_404)
http://metrics.dropwizard.io/4.1.5/manual/core.html#histograms (HTTP_404)
https://www.openssl.org/related/binaries.html (HTTP_404)
https://docs.oracle.com/en/java/javase/11/docs/api/java/time/format/DateTimeFormatter.html#ISO_INSTANT (HTTP_404)
https://docs.oracle.com/en/java/javase/11/docs/api/java/util/TimeZone.html (HTTP_404)
http://accarol.com/contact.htm?from=external&a=10 (HTTP_404)
https://docs.oracle.com/en/java/javase/11/docs/api/java/lang/Character.html#isWhitespace-int- (HTTP_404)
https://sease.io/2020/02/introducing-weighted-synonyms-in-apache-lucene.html (HTTP_404)
http://demo.icu-project.org/icu-bin/locexp (HTTP_404)
https://docs.oracle.com/en/java/javase/11/docs/api/java/text/Collator.html (HTTP_404)
https://docs.oracle.com/en/java/javase/11/docs/api/java/text/Collator.html (HTTP_404)
https://docs.oracle.com/en/java/javase/11/docs/api/java/text/Collator.html (HTTP_404)
https://docs.oracle.com/en/java/javase/11/docs/api/java/text/Collator.html (HTTP_404)
https://docs.oracle.com/en/java/javase/11/docs/api/java/text/RuleBasedCollator.html (HTTP_404)
http://bvg.udc.es/recursos_lingua/stemming.jsp (BLC_UNKNOWN)
https://onlinelibrary.wiley.com/doi/abs/10.1002/asi.20750 (HTTP_403)
https://mvnrepository.com/artifact/org.locationtech.jts/jts-core/1.15.0 (HTTP_403)
https://docs.oracle.com/en/java/javase/11/docs/api/java/lang/Thread.html (HTTP_404)
https://cwiki.apache.org/confluence/display/SOLR/ReleaseNote88 (HTTP_404)
```

On page `learning-to-rank.html` there is a link to https://github.com/apache/lucene-solr/tree/releases/lucene-solr/9.0.0/solr/contrib/ltr/example which looks wrong too

**Comment by ctargett** [comment]
> The -prerelease5 suffix should probably not be there (and will not either of course in the final release), not sure if it needs change.

No, they shouldn't need to change. The Lucene version comes from `versions.props` so when that's right for 9.0 it will be right in the 9.0 Ref Guide. This has been true forever - the URL is always wrong until the javadocs exist.

> Here is the list of broken links

I didn't change anything here, so presumably these are also all 40x in the current Ref Guide. I'm not sure how fixing them relates to approving the overall content re-organization? One could fix them all in the current Ref Guide in `main` right now, or pre-9.0 release, and in branch_8x, etc.

**Review by janhoy — APPROVED** [review]

**Comment by janhoy** [comment]
Yep, let’s do the link fixes in a separate issue.

**Comment by janhoy** [comment]
I created https://issues.apache.org/jira/browse/SOLR-15497 for the broken links

**Comment by gerlowskija** [comment]
This LGTM and is a huge step forward for the ref-guide!

The biggest nitpick I probably have here is that the breaking up of the old "Admin UI" section (a change I'm hugely in favor of) leaves a few vestigial stub pages around as not very useful "screenshot-vehicles". e.g. thread-dump.adoc.  It looks like most of the Admin UI content it looks like was able to be pulled into other pages, but the few places this couldn't be done feel awkward IMO.  Not sure there's a fix to this though - short of individually adding conceptually related content to these pages. (In the thread-dump.adoc example, maybe someone will eventually add info there about Solr-specific things to look for in thread dumps).  That said, I'm totally happy to live with this if it's a side effect of the otherwise overwhelmingly positive change.

Will be great to see this in 9!

**Review by gerlowskija — APPROVED** [review]

**Pull request merged**
