### PR TITLE
Gradle: Use lazy file types

### PR DESCRIPTION
**Pull request by tylerbertrand**
# Description

Updated inputs defined in `CommandLineArgumentProvider`s to use lazy file types. While usage of "eager" file types is not currently causing issues, it is generally preferred to use lazy file types where possible to defer file evaluation to execution time.

# Solution

Replaced `File`s with their lazy counterparts: `Directory` and `RegularFile`

Build scan for these changes: https://scans.gradle.com/s/2rtoy5kx6cipa

# Tests

N/A - this PR only updates build logic

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by risdenk — APPROVED** [review]

**Comment by dsmiley** [comment]
Thanks for improving our build Tyler!  It's a big build; anything helps.

**Comment by risdenk** [comment]
Thanks @tylerbertrand

**Comment by uschindler** [comment]
Please remember to port this to Lucene!

**Comment by risdenk** [comment]
I created https://github.com/apache/lucene/issues/12145 to track adding this to Lucene.

**Pull request merged**
