### PR TITLE
SOLR-16019 Use var keywords in this test

### PR DESCRIPTION
**Pull request by janhoy**
https://issues.apache.org/jira/browse/SOLR-16019

### CODE REVIEW

**Review by madrob — COMMENTED** [review]
Do we have standards or best practices regarding var? I know it's a new language feature, but I'm not in the habit of using it yet and don't have a great intuition about when it is appropriate and when it would reduce clarity?

**Comment by janhoy** [comment]
> Do we have standards or best practices regarding var? I know it's a new language feature, but I'm not in the habit of using it yet and don't have a great intuition about when it is appropriate and when it would reduce clarity?

We don't have any coding standards like this. I'm used to it with Kotlin and it removes lots of boilerplate code. We should not yet do a cross-the-board update of the codebase, since we still may need to merge with 8.x for still another year.

But I tend to do minor refactorings and improvements as I touch various code paths for other reasons. Sometimes I'm tempted to convert clunky code to streaming etc. But I agree that a separate PR is far better than unrelated changes in a feature or bugfix commit.

**Comment by dsmiley** [comment]
The gist of it:  Use `var` when the type is obvious.  Perhaps the variable's name (e.g. `zkStateReader`) makes the type declaration needless, or you call some method to initialize it and this method's name makes it obvious.  There is some subjectivity of course... I'm more likely to be loose about it in a test.

**Comment by janhoy** [comment]
Leaving this for a more general cleanup later, closing.

**Pull request closed without merging**
