### PR TITLE
Clean up docker-faq.adoc

### PR DESCRIPTION
**Pull request by janhoy**
Spinoff from #1114 which will clean up One sub chapter, while this cleans up the rest of the file.

### CODE REVIEW

**Review by epugh — APPROVED** [review]
LGTM..    This looks so much nicer..  It felt like developer notes and now seems more FAQ..    I always struggled to understand them...

**Comment by janhoy** [comment]
> It felt like developer notes and now seems more FAQ

I actually think the FAQ text copied over from the old `docker-solr` project was written even before our `Dockerfile` had the `VOLUME` declaration, and before data folder was moved to `/var/solr`. So lots of doc rot there.

**Comment by syats** [comment]
The fact that this PR is not yet in the productive documentation https://solr.apache.org/guide/solr/latest/deployment-guide/docker-faq.html as of 2023-03-07 is a source of confusion! The current documentation does not reflect the move of the data folder!

**Comment by epugh** [comment]
I don't believe changes to ref guides go immediately (unlike the website changes)...    We don't have a "quick push this change to productioin ref guide" that isn't tied to a release.   Hopefully 9.6 will be out soon, and I don't think this will justify a 9.5.x release...

**Comment by janhoy** [comment]
Hmm, if I'm not mistaken, a merge of this fix to `branch_9_5` may actually update the 9.5 guide. Let me try.

**Comment by epugh** [comment]
If this works...    I wonder if we should try an establish a stronger pattern for doc fixes going `main` --> `branch_9x` and --> `branch_9_5` ?   Though it is a whole nother step....

**Comment by janhoy** [comment]
I did a push, let's wait for daily build of https://ci-builds.apache.org/job/Solr/job/solr-reference-guide-official/ - I think it will kick off in an hour or so.

**Comment by janhoy** [comment]
The theory behind the guide build is that there is not supposed to be any functional change within a minor version, so any fixes pushed to `branch_9_5` are by definition bug fixes, including fixes to ref guide. This makes it safe to build the guide immediately even without a code release.

We could even use this to push "Errata" entries to the guide after we discover bugs in a release that will not be fixed in an upcoming release...

**Comment by HoustonPutman** [comment]
> Hmm, if I'm not mistaken, a merge of this fix to `branch_9_5` may actually update the 9.5 guide. Let me try.

You are not mistaken!

**Pull request merged**
