### PR TITLE
Ignore 3rd Party JS in Lift

### PR DESCRIPTION
**Pull request by madrob**

### CODE REVIEW

**Comment by madrob** [comment]
@TomMD FYI

**Comment by TomMD** [comment]
Thank you for the tag @madrob. If your view of eslint is particularly dim you might also want:

```
disableTools = [ "eslint" ]
```

**Comment by madrob** [comment]
It looks like the ignoreFiles doesn't get properly respected? https://lift.sonatype.com/results/github.com/apache/solr/01FZTK2DJWP5S2G8CSD7MJ6Q4P shows `d3.js` and `prettify.min.js` both getting analyzed.

**Comment by TomMD** [comment]
@madrob One of those commits is no longer in the repo. The other commit shows the config proposed in this PR is not the config used in that analysis:

```
% cat .lift.toml
# This file can configure Muse PR static analysis.
# Docs for adding, removing or changing checks can be found here:
# https://docs.muse.dev/docs/repository-configuration/

jdkVersion = "11"
% git rev-parse HEAD
ff4ed0b2461f5f8fea52bab32b5308a0ebd47b7d
```

**Comment by madrob** [comment]
How can we test lift configuration if the PR runs with the settings from the head branch?

**Comment by TomMD** [comment]
@madrob All good questions.

> gradle/documentation/render-javadoc/prettify/prettify.min.js

This directory is not being ignored, per config of:

```
ignoreFiles = '''
  solr/webapp/web/libs/*.js
'''
```

> d3.js

This directory might be intended to be ignored but the matcher probably thinks `solr` does not match `  solr` - we should strip leading spaces, I'll bring this thought back to the team.

> How can we test lift configuration if the PR runs with the settings from the head branch?

The PR analysis is actually two separate analyses of both the source and the destination branches, not just the HEAD.  The bugs detected in the source branch can be found using the phases of Introduced and Preexisting. We're likely to make this more straight-forward in the future.  Also, you can analyze a single branch at any time from the web console such as https://lift.sonatype.com/results/github.com/madrob/solr.

**Comment by denastro** [comment]
@madrob - We are investigating the issue @TomMD has pointed out. I will keep you updated.

**Comment by madrob** [comment]
@denastro @TomMD - I had to add the default ignores of `**/test/**` and `**/*.min.js` to the `ignoreFiles` configuration.

**Comment by TomMD** [comment]
Thanks @madrob that makes sense. @denastro and I are both aware of the jshint/eslint errors you mentioned so they will get prioritized and worked accordingly.

**Pull request merged**
