### PR TITLE
SOLR-15886: remove showItems

### PR DESCRIPTION
**Pull request by petdance**
# Description

Removes the last few mentions of the showItems argument for fieldValueCache.

# Checklist

Please review the following and check all that apply:

- [X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [X] I have created a Jira issue and added the issue ID to my pull request title.
- [X] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [X] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
LGTM.    I'll leave it open to see if anyone else comments...    Ping me in a day or two to merge if no one else does.

**Review by madrob — APPROVED** [review]
@epugh do you want to drive this across the finish line?

**Comment by epugh** [comment]
@petdance how do you want to be credited in `CHANGES.txt`?  petdance?  Andy Lester?

**Comment by petdance** [comment]
"Andy Lester", please.

Thanks, y'all.  Glad to help where I can.  Pretty good for not knowing Java, huh? :-)

**Comment by epugh** [comment]
> 

What's Java?!!!  ;-)

**Pull request merged**
