### PR TITLE
Build: report test history via GE

### PR DESCRIPTION
**Pull request by dsmiley**
Put a convenient link to test history, powered by Gradle Enterprise.
Could be enhanced to also include fucit.org

Improve the corresponding build logic to be more "groovy", as it's said.

Example, with me forcing some failures to demo:
```
> Task :solr:core:test FAILED
ERROR: The following test(s) have failed:
  - org.apache.solr.search.TestThinCache.testInitCore (:solr:core)
    Test history: https://ge.apache.org/scans/tests?search.rootProjectNames=solr-root&tests.container=org.apache.solr.search.TestThinCache&tests.test=testInitCore
    Test output: /Users/dsmiley/SFDCDev/solr_main/solr/core/build/test-results/test/outputs/OUTPUT-org.apache.solr.search.TestThinCache.txt
    Reproduce with: gradlew :solr:core:test --tests "org.apache.solr.search.TestThinCache.testInitCore" -Ptests.jvms=8 "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:ReservedCodeCacheSize=120m" -Ptests.seed=4701215A96003B03 -Ptests.useSecurityManager=false -Ptests.locale=cs-CZ -Ptests.timezone=America/Dawson_Creek -Ptests.badapples=false -Ptests.file.encoding=UTF-8

```

Indentation should be the same as it was; just added a URL.

Note that gradle.buildFinished is deprecated but [it doesn't yet have a concise replacement](https://docs.google.com/document/d/1nS1JTwdCMQN_0WaaFrSUxoQOj3zOqmKmXxC6k0OXUR0/edit#heading=h.4691loc5bp0p) so I'm leaving it be.

### CODE REVIEW

**Comment by iamsanjay** [comment]
+1 

Knowing test history would empower (old/**new**) Devs to make better decision. For instance, I observed that lots of build failed due to the flaky test cases, and I did not even knew about this URL before David shared it with me. 

Research on this:

As per one survey participants were asked what information or tools would be most helpful to them in order to better handle flaky test cases, from University of Passau, ([Martin and Gordon, 2022](https://arxiv.org/abs/2203.00483)).

> We observe a significant demand for improved visualization of flakiness. They specifically request tools to display test result histories, with comments such as, "We run tests so often, I often miss the bigger picture", and a desire for "a tool to visualize how tests fail and succeed over time" Additionally, they emphasize that such a tool should include meta-information like "on which device/environment [the test was executed]

The second most commonly stated wish asks for tools that can automatically detect flaky test. And that's I proposed before as well and you have told me to share it on dev mailing list. I will do it!

https://arxiv.org/abs/2203.00483

**Comment by dsmiley** [comment]
Added fucit.org now like so:
```
Test history: https://ge.apache.org/scans/tests?search.rootProjectNames=solr-root&tests.container=org.apache.solr.search.TestThinCache&tests.test=testSimple http://fucit.org/solr-jenkins-reports/history-trend-of-recent-failures.html#series/org.apache.solr.search.TestThinCache.testSimple
```

-- a long line that surely overflows to the next line.  Only applies for test failure, not suite failure.

I think this PR also fixes/improves upon seeing "classMethod" in reproduce lines that shouldn't be there.  CC @dweiss .  I placed a `fail()` in a BeforeClass method and surprisingly it was the `afterTest` instead of `afterSuite` handler that was called.

**Comment by dsmiley** [comment]
Ha... another test failure and now we can see it in action here:
```
ERROR: The following test(s) have failed:
  - org.apache.solr.client.solrj.impl.BasicHttpSolrClientTest.classMethod (:solr:solrj)
    Test history: https://ge.apache.org/scans/tests?search.rootProjectNames=solr-root&tests.container=org.apache.solr.client.solrj.impl.BasicHttpSolrClientTest&tests.test=classMethod
    Test output: /tmp/src/solr/solr/solrj/build/test-results/test/outputs/OUTPUT-org.apache.solr.client.solrj.impl.BasicHttpSolrClientTest.txt
    Reproduce with: gradlew :solr:solrj:test --tests "org.apache.solr.client.solrj.impl.BasicHttpSolrClientTest.classMethod" -Ptests.jvms=96 "-Ptests.jvmargs=-XX:TieredStopAtLevel=1 -XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:ReservedCodeCacheSize=120m" -Ptests.seed=C788D52D93C87F21 -Ptests.timeoutSuite=600000! -Ptests.file.encoding=US-ASCII
```

That was for the first commit, _before_ I improved it.  Thus it shows the "classMethod" problem that pre-existed.

That test which failed is not a flapper.  It timed out due to a known intermittent hang bug that I fixed but not merged yet -- #2474 

I'll merge this Monday, giving more time for more review.

**Comment by AndreyBozhko** [comment]
LGTM - just echoing the comment from @gus-asf: https://github.com/apache/solr/pull/2483#issuecomment-2138043439

> if we are touching this lets add a ./ on the front of the command so one can actually cut and paste it :)

**Pull request merged**
