### PR TITLE
chore(deps): update dependency com.adobe.testing:s3mock-junit4 to v3 - autoclosed

### PR DESCRIPTION
**Pull request by solrbot**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [com.adobe.testing:s3mock-junit4](https://redirect.github.com/adobe/S3Mock) | test | major | `2.17.0` -> `3.11.0` |

---

### Release Notes

<details>
<summary>adobe/S3Mock (com.adobe.testing:s3mock-junit4)</summary>

### [`v3.11.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#3110)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.10.3...3.11.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   none
-   Version updates (deliverable dependencies)
    -   Bump aws-v2.version from 2.26.25 to 2.28.11
    -   Bump aws.version from 1.12.765 to 1.12.772
    -   Bump spring-boot.version from 3.3.2 to 3.3.3
    -   Bump commons-io:commons-io from 2.16.1 to 2.17.0
    -   Bump com.fasterxml.jackson:jackson-bom from 2.17.2 to 2.18.0
    -   Bump testcontainers.version from 1.20.0 to 1.20.1
    -   Bump alpine from 3.20.2 to 3.20.3 in /docker
    -   Bump kotlin.version from 2.0.0 to 2.0.20

### [`v3.10.3`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#3103)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.10.2...3.10.3)

Test release that incremented the patch version number.
Please refer / update to version 3.11.0, thanks.

### [`v3.10.2`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#3102)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.10.1...3.10.2)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Let CopyObject overwrite store headers (fixes [#&#8203;2005](https://redirect.github.com/adobe/S3Mock/issues/2005))
-   Version updates (build dependencies)
    -   Bump org.apache.maven.plugins:maven-deploy-plugin from 3.1.2 to 3.1.3
    -   Bump org.apache.maven.plugins:maven-dependency-plugin from 3.7.1 to 3.8.0
    -   Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.8.0 to 3.10.0
    -   Bump org.apache.maven.plugins:maven-gpg-plugin from 3.2.6 to 3.2.7
    -   Bump org.apache.maven.plugins:maven-checkstyle-plugin from 3.4.0 to 3.5.0
    -   Bump license-maven-plugin-git.version from 4.5 to 4.6
    -   Bump com.puppycrawl.tools:checkstyle from 10.17.0 to 10.18.1
    -   Bump actions/checkout from 4.1.7 to 4.2.0
    -   Bump github/codeql-action from 3.26.7 to 3.26.9
    -   Bump actions/setup-java from 4.3.0 to 4.4.0

### [`v3.10.1`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#3101)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.10.0...3.10.1)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   CRT-based S3 client has timeouts with mock when uploading streams of unknown size (fixes [#&#8203;2049](https://redirect.github.com/adobe/S3Mock/issues/2049))
-   Version updates (build dependencies)
    -   Bump io.fabric8:docker-maven-plugin from 0.44.0 to 0.45.0
    -   Bump org.codehaus.mojo:exec-maven-plugin from 3.3.0 to 3.4.1
    -   Bump org.apache.maven.plugins:maven-install-plugin from 3.1.2 to 3.1.3
    -   Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.3.1 to 3.5.0
    -   Bump org.apache.maven.plugins:maven-surefire-plugin from 3.3.1 to 3.5.0
    -   Bump github/codeql-action from 3.25.15 to 3.26.7
    -   Bump step-security/harden-runner from 2.9.0 to 2.10.1
    -   Bump actions/setup-java from 4.2.1 to 4.3.0
    -   Bump actions/upload-artifact from 4.3.4 to 4.4.0

### [`v3.10.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#3100)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.9.1...3.10.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Allow PUT requests without content-type application/xml (fixes [#&#8203;1978](https://redirect.github.com/adobe/S3Mock/issues/1978))
-   Version updates (deliverable dependencies)
    -   Bump aws-v2.version from 2.25.59 to 2.26.25
    -   Bump aws.version from 1.12.729 to 1.12.765
    -   Bump spring-boot.version from 3.3.0 to 3.3.2
    -   Bump alpine from 3.20.0 to 3.20.2 in /docker
    -   Bump com.fasterxml.jackson:jackson-bom from 2.17.1 to 2.17.2
    -   Bump testcontainers.version from 1.19.8 to 1.20.0
    -   Bump org.mockito.kotlin:mockito-kotlin from 5.3.1 to 5.4.0
-   Version updates (build dependencies)
    -   Bump com.puppycrawl.tools:checkstyle from 10.16.0 to 10.17.0
    -   Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.2.5 to 3.3.1
    -   Bump org.apache.maven.plugins:maven-surefire-plugin from 3.2.5 to 3.3.1
    -   Bump org.apache.maven.plugins:maven-enforcer-plugin from 3.4.1 to 3.5.0
    -   Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.6.3 to 3.8.0
    -   Bump org.apache.maven.plugins:maven-dependency-plugin from 3.6.1 to 3.7.1
    -   Bump org.apache.maven.plugins:maven-checkstyle-plugin from 3.3.1 to 3.4.0
    -   Bump org.apache.maven.plugins:maven-release-plugin from 3.0.1 to 3.1.1
    -   Bump org.apache.maven.plugins:maven-clean-plugin from 3.3.2 to 3.4.0
    -   Bump org.apache.maven.plugins:maven-jar-plugin from 3.4.1 to 3.4.2
    -   Bump org.sonatype.plugins:nexus-staging-maven-plugin from 1.6.13 to 1.7.0
    -   Bump docker/setup-qemu-action from 3.0.0 to 3.2.0
    -   Bump actions/upload-artifact from 4.3.3 to 4.3.4
    -   Bump actions/dependency-review-action from 4.3.2 to 4.3.4
    -   Bump actions/checkout from 4.1.6 to 4.1.7
    -   Bump github/codeql-action from 3.25.6 to 3.25.14
    -   Bump ossf/scorecard-action from 2.3.3 to 2.4.0
    -   Bump step-security/harden-runner from 2.8.0 to 2.9.0

### [`v3.9.1`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#391)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.8.0...3.9.1)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Persist metadata for parts, validate checksum on multipart completion (fixes [#&#8203;1205](https://redirect.github.com/adobe/S3Mock/issues/1205))
-   Refactorings
    -   Migrate Unit tests to Kotlin
    -   Run ITs against real S3, fix code or tests in case of errors
        -   Fix Checksums for Multiparts
        -   Add ObjectOwnership config for Buckets, setting ACLs is not allowed otherwise
        -   Fix StorageClass, it's not returned for most APIs if it's "STANDARD"
-   Version updates (deliverable dependencies)
    -   Bump aws-v2.version from 2.25.49 to 2.25.59
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.720 to 1.12.729
    -   Bump kotlin.version from 1.9.24 to 2.0.0
    -   Bump alpine from 3.19.1 to 3.20.0 in /docker
-   Version updates (build dependencies)
    -   Bump org.codehaus.mojo:exec-maven-plugin from 3.2.0 to 3.3.0
    -   Bump com.github.ekryd.sortpom:sortpom-maven-plugin from 3.4.1 to 4.0.0
    -   Bump license-maven-plugin-git.version from 4.4 to 4.5
    -   Bump actions/checkout from 4.1.5 to 4.1.6
    -   Bump github/codeql-action from 3.25.4 to 3.25.6
    -   Bump step-security/harden-runner from 2.7.1 to 2.8.0

### [`v3.8.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#380)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.7.3...3.8.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Fix failing uploads after EOL detection refactoring (fixes [#&#8203;1840](https://redirect.github.com/adobe/S3Mock/issues/1840), [#&#8203;1842](https://redirect.github.com/adobe/S3Mock/issues/1842))
        -   Adding additional tests for combinations of HTTP / HTTPS and sync / async clients with different test files
        -   Known issue: using HTTP, AWS SDKv2 sends the wrong checksum for SHA256, leading uploads to fail
-   Version updates (deliverable dependencies)
    -   Bump aws-v2.version from 2.25.39 to 2.25.49
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.709 to 1.12.720
    -   Bump com.fasterxml.jackson:jackson-bom from 2.17.0 to 2.17.1
    -   Bump kotlin.version from 1.9.23 to 1.9.24
    -   Bump org.xmlunit:xmlunit-assertj3 from 2.9.1 to 2.10.0
    -   Bump testcontainers.version from 1.19.7 to 1.19.8
    -   Bump org.testng:testng from 7.10.1 to 7.10.2
    -   Bump com.puppycrawl.tools:checkstyle from 10.15.0 to 10.16.0
-   Version updates (build dependencies)
    -   Bump license-maven-plugin-git.version from 4.3 to 4.4
    -   Bump org.apache.maven.plugins:maven-deploy-plugin from 3.1.1 to 3.1.2
    -   Bump org.apache.maven.plugins:maven-install-plugin from 3.1.1 to 3.1.2
    -   Bump step-security/harden-runner from 2.7.0 to 2.7.1
    -   Bump actions/checkout from 4.1.4 to 4.1.5
    -   Bump actions/dependency-review-action from 4.2.5 to 4.3.2
    -   Bump ossf/scorecard-action from 2.3.1 to 2.3.3
    -   Bump github/codeql-action from 3.25.3 to 3.25.4

### [`v3.7.3`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#373)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.7.2...3.7.3)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Support large, chunked, unsigned, asynchronous uploads (fixes [#&#8203;1818](https://redirect.github.com/adobe/S3Mock/issues/1818))

### [`v3.7.2`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#372)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.7.1...3.7.2)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Calculate and validate checksums on upload (fixes [#&#8203;1827](https://redirect.github.com/adobe/S3Mock/issues/1827))
        -   UploadPart API now also returns checksums, if available.

### [`v3.7.1`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#371)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.6.0...3.7.1)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Correctly handle chunked unsigned uploads (fixes [#&#8203;1662](https://redirect.github.com/adobe/S3Mock/issues/1662))
        -   Known issue: when using one of the Async SDK clients, uploads sometimes fail when the file size is >16KB.
            Not yet sure why. Uploads <16KB work just fine.
    -   Let Jetty handle "UNSAFE" characters in URIs, again (see [#&#8203;1686](https://redirect.github.com/adobe/S3Mock/issues/1686))
-   Version updates
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.698 to 1.12.709
    -   Bump aws-v2.version from 2.25.28 to 2.25.39
    -   Bump spring-boot.version from 3.2.4 to 3.2.5
    -   Bump org.apache.maven.plugins:maven-gpg-plugin from 3.2.2 to 3.2.4
    -   Bump org.apache.maven.plugins:maven-jar-plugin from 3.3.0 to 3.4.1
    -   Bump github/codeql-action from 3.24.10 to 3.25.3
    -   Bump actions/upload-artifact from 4.3.1 to 4.3.3
    -   Bump actions/checkout from 4.1.2 to 4.1.4

### [`v3.6.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#360)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.5.2...3.6.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Return XML prolog and namespace in all responses (fixes [#&#8203;1754](https://redirect.github.com/adobe/S3Mock/issues/1754))
    -   Explain in README.md how `root` property works with Docker. (fixes [#&#8203;1728](https://redirect.github.com/adobe/S3Mock/issues/1728))
-   Refactorings
    -   Removal of JAX-B for AccessControlPolicy requests/responses.
        -   Jackson-databind-xml 2.17.0 adds polymorphic (de-)serializiation through "xsi:type"
    -   Jackson-annotation cleanup in POJOs
-   Version updates
    -   Bump spring-boot.version from 3.2.3 to 3.2.4
    -   Bump aws-v2.version from 2.24.9 to 2.25.28
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.665 to 1.12.698
    -   Bump commons-io:commons-io from 2.15.1 to 2.16.1
    -   Bump org.testng:testng from 7.9.0 to 7.10.1
    -   Bump org.mockito.kotlin:mockito-kotlin from 5.2.1 to 5.3.1
    -   Bump com.puppycrawl.tools:checkstyle from 10.14.0 to 10.15.0
    -   Bump org.apache.maven.plugins:maven-gpg-plugin from 3.1.0 to 3.2.2
    -   Bump org.apache.maven.plugins:maven-compiler-plugin from 3.12.1 to 3.13.0
    -   Bump org.apache.maven.plugins:maven-source-plugin from 3.3.0 to 3.3.1
    -   Bump com.github.ekryd.sortpom:sortpom-maven-plugin from 3.4.0 to 3.4.1
    -   Bump org.jacoco:jacoco-maven-plugin from 0.8.11 to 0.8.12
    -   Bump actions/checkout from 4.1.1 to 4.1.2
    -   Bump actions/setup-java from 4.1.0 to 4.2.1
    -   Bump github/codeql-action from 3.24.6 to 3.24.10
    -   Bump actions/dependency-review-action from 4.1.3 to 4.2.5
    -   Bump maven from 3.8.5 to 3.9.6

### [`v3.5.2`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#352)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.5.1...3.5.2)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Support key names that lead to request paths that do not comply to RFC3986 (fixes [#&#8203;1686](https://redirect.github.com/adobe/S3Mock/issues/1686))
-   Refactorings
    -   Refactor IT usage of S3 clients, add more tests
    -   Use ZGC and ZGenerationalGC when running in Docker
-   Version updates
    -   Bump kotlin.version from 1.9.22 to 1.9.23
    -   Bump testcontainers.version from 1.19.6 to 1.19.7
    -   Bump github/codeql-action from 3.24.5 to 3.24.6
    -   Bump actions/setup-java from 4.0.0 to 4.1.0
    -   Bump com.puppycrawl.tools:checkstyle from 10.13.0 to 10.14.0

### [`v3.5.1`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#351)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.5.0...3.5.1)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Support canned ACLs (fixes [#&#8203;1617](https://redirect.github.com/adobe/S3Mock/issues/1617))
-   Version updates
    -   Bump spring-boot.version from 3.2.2 to 3.2.3
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.656 to 1.12.665
    -   Bump aws-v2.version from 2.23.21 to 2.24.9
    -   Bump testcontainers.version from 1.19.5 to 1.19.6
    -   Bump io.fabric8:docker-maven-plugin from 0.43.4 to 0.44.0
    -   Bump com.github.ekryd.sortpom:sortpom-maven-plugin from 3.3.0 to 3.4.0
    -   Bump org.codehaus.mojo:exec-maven-plugin from 3.1.1 to 3.2.0
    -   Bump actions/dependency-review-action from 4.0.0 to 4.1.3
    -   Bump github/codeql-action from 3.24.0 to 3.24.5

### [`v3.5.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#350)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.4.0...3.5.0)

Release of Java modules failed, please use 3.5.1

### [`v3.4.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#340)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.3.1...3.4.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Support storage classes in APIs
    -   Use "application/octet-stream" as default content-type
-   Refactorings
    -   Use JDK21 as runtime in the Docker container
-   Version updates
    -   Bump spring-boot.version from 3.2.1 to 3.2.2
    -   Bump aws-v2.version from 2.22.7 to 2.23.21
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.627 to 1.12.656
    -   Bump testcontainers.version from 1.19.3 to 1.19.5
    -   Bump com.puppycrawl.tools:checkstyle from 10.12.6 to 10.13.0
    -   Bump alpine from 3.19.0 to 3.19.1 in /docker
    -   Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.2.3 to 3.2.5
    -   Bump org.apache.maven.plugins:maven-surefire-plugin from 3.2.3 to 3.2.5
    -   Bump github/codeql-action from 3.22.12 to 3.24.0
    -   Bump actions/upload-artifact from 4.0.0 to 4.3.1
    -   Bump actions/dependency-review-action from 3.1.4 to 4.0.0
    -   Bump step-security/harden-runner from 2.6.1 to 2.7.0

### [`v3.3.1`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#331)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.3.0...3.3.1)

Accidental release, should have been 3.4.0

### [`v3.3.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#330)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.2.0...3.3.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Support initial and existing buckets (fixes [#&#8203;1433](https://redirect.github.com/adobe/S3Mock/issues/1433))
    -   Compile with "parameters=true" (fixes [#&#8203;1555](https://redirect.github.com/adobe/S3Mock/issues/1555))
-   Version updates
    -   Bump spring-boot.version from 3.1.5 to 3.2.1
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.580 to 1.12.627
    -   Bump aws-v2.version from 2.21.14 to 2.22.7
    -   Bump commons-io:commons-io from 2.15.0 to 2.15.1
    -   Bump testcontainers.version from 1.19.1 to 1.19.3
    -   Bump kotlin.version from 1.9.20 to 1.9.22
    -   Bump alpine from 3.18.4 to 3.19.0 in /docker
    -   Bump org.testng:testng from 7.8.0 to 7.9.0
    -   Bump org.mockito.kotlin:mockito-kotlin from 5.1.0 to 5.2.1
    -   Bump com.puppycrawl.tools:checkstyle from 10.12.4 to 10.12.6
    -   Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.2.1 to 3.2.3
    -   Bump org.apache.maven.plugins:maven-surefire-plugin from 3.2.1 to 3.2.3
    -   Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.6.0 to 3.6.3
    -   Bump org.apache.maven.plugins:maven-compiler-plugin from 3.11.0 to 3.12.1
    -   Bump org.codehaus.mojo:exec-maven-plugin from 3.1.0 to 3.1.1
    -   Bump actions/setup-java from 3.13.0 to 4.0.0
    -   Bump step-security/harden-runner from 2.6.0 to 2.6.1
    -   Bump actions/dependency-review-action from 3.1.0 to 3.1.4
    -   Bump actions/upload-artifact from 3.1.3 to 4.0.0
    -   Bump github/codeql-action from 2.22.5 to 3.22.12
    -   Bump mvn version from 3.5.4 to 3.8.5

### [`v3.2.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#320)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.1.0...3.2.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Better description of S3Mock API usage and SDK usage (fixes [#&#8203;219](https://redirect.github.com/adobe/S3Mock/issues/219), [#&#8203;125](https://redirect.github.com/adobe/S3Mock/issues/125), [#&#8203;1196](https://redirect.github.com/adobe/S3Mock/issues/1196))
        -   Presigned URLs were working all along.
        -   Added documentation and tests.
    -   Add ListObjectVersions API - dummy implementation (fixes [#&#8203;1215](https://redirect.github.com/adobe/S3Mock/issues/1215))
-   Version updates
    -   Bump aws-v2.version from 2.20.115 to 2.21.14
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.519 to 1.12.580
    -   Bump spring-boot.version from 3.1.0 to 3.1.5
    -   Bump alpine from 3.18.2 to 3.18.4 in /docker
    -   Bump testcontainers.version from 1.18.3 to 1.19.1
    -   Bump kotlin.version from 1.9.0 to 1.9.20
    -   Bump commons-io:commons-io from 2.13.0 to 2.15.0
    -   Bump com.puppycrawl.tools:checkstyle from 10.12.2 to 10.12.4
    -   Bump io.fabric8:docker-maven-plugin from 0.43.2 to 0.43.4
    -   Bump org.apache.maven.plugins:maven-enforcer-plugin from 3.3.0 to 3.4.1
    -   Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.5.0 to 3.6.0
    -   Bump org.apache.maven.plugins:maven-dependency-plugin from 3.6.0 to 3.6.1
    -   Bump org.apache.maven.plugins:maven-surefire-plugin from 3.1.2 to 3.2.1
    -   Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.1.2 to 3.2.1
    -   Bump org.apache.maven.plugins:maven-checkstyle-plugin from 3.3.0 to 3.3.1
    -   Bump org.apache.maven.plugins:maven-clean-plugin from 3.3.1 to 3.3.2
    -   Bump license-maven-plugin-git.version from 4.2 to 4.3
    -   Bump org.jacoco:jacoco-maven-plugin from 0.8.10 to 0.8.11
    -   Bump org.mockito.kotlin:mockito-kotlin from 5.0.0 to 5.1.0
    -   Bump actions/setup-java from 3.12.0 to 3.13.0
    -   Bump actions/checkout from 3.5.3 to 4.1.1
    -   Bump actions/upload-artifact from 3.1.2 to 3.1.3
    -   Bump actions/dependency-review-action from 3.0.6 to 3.1.0
    -   Bump github/codeql-action from 2.21.2 to 2.22.5
    -   Bump docker/setup-qemu-action from 2.2.0 to 3.0.0
    -   Bump step-security/harden-runner from 2.5.0 to 2.6.0
    -   Bump ossf/scorecard-action from 2.2.0 to 2.3.1

### [`v3.1.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#310)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.0.1...3.1.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Fixes various bugs, vulnerabilities, code smells, security hot spots etc found by Sonarqube
-   Refactorings
    -   Scanned repo with StepSecurity tools
        -   Merged various PRs related to the security of Github actions and Github review actions
        -   Reviewed [OSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/adobe/S3Mock), applied various fixes
        -   Reviewed [OSSF Best practices](https://bestpractices.coreinfrastructure.org/projects/7673)
-   Version updates
    -   Bump com.amazonaws:aws-java-sdk-s3 from 1.12.501 to 1.12.519
    -   Bump aws-v2.version from 2.20.98 to 2.20.115
    -   Bump com.github.ekryd.sortpom:sortpom-maven-plugin from 3.2.1 to 3.3.0
    -   Bump io.fabric8:docker-maven-plugin from 0.43.0 to 0.43.2
    -   Bump com.puppycrawl.tools:checkstyle from 10.12.1 to 10.12.2
    -   Bump kotlin.version from 1.8.22 to 1.9.0
    -   Bump github/codeql-action from 2.21.1 to 2.21.2

### [`v3.0.1`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#301)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/3.0.0...3.0.1)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Features and fixes
    -   Fix startup on existing data folder issues (fixes [#&#8203;1245](https://redirect.github.com/adobe/S3Mock/issues/1245))
    -   Return checksumAlgorithm in ListObjects / ListObjectsV2 (fixes [#&#8203;1220](https://redirect.github.com/adobe/S3Mock/issues/1220))

### [`v3.0.0`](https://redirect.github.com/adobe/S3Mock/blob/HEAD/CHANGELOG.md#300)

[Compare Source](https://redirect.github.com/adobe/S3Mock/compare/2.17.0...3.0.0)

3.x is JDK17 LTS bytecode compatible, with Docker and JUnit / direct Java integration.

-   Refactorings
    -   Use various Java language features introduced between JDK 8 and JDK 17
    -   Use new Spring Boot 3 features
    -   Use new Spring Framework 6 features
    -   Dependency cleanup
    -   Code cleanup
    -   Deprecate JUnit 4 TestRule
        -   This module will be removed in S3Mock 4.x
-   Version updates
    -   Bump spring-boot.version from 2.7.13 to 3.1.0
        -   This updates all Spring Boot dependencies as well
    -   Bump Spring Framework to 6.0.9
    -   Bump Java bytecode version from 8 to 17
        -   This change is necessary, as Spring Framework 6 and Spring Boot 3 raise the baseline Java version from 8 to 17.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 9am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://redirect.github.com/solrbot/renovate-github-action)

### CODE REVIEW

**Comment by HoustonPutman** [comment]
Yeah we can't merge this until Solr is JDK 17+, which presumably will be Solr 10.x, since Lucene 10 will be JDK 17+

**Comment by cpoerschke** [comment]
> Yeah we can't merge this until Solr is JDK 17+, which presumably will be Solr 10.x, since Lucene 10 will be JDK 17+

Wondering if/how we could communicate this to @solrbot and/or ourselves. Perhaps leaving this PR open but converting it to "draft" status?

**Comment by cpoerschke** [comment]
Wondering if we'd like to
* close this,
* create a JIRA for manual upgrade later and
* exclude from solrbot trying again
* (and then the exclusion would be removed as part of the JIRA)?

**Comment by malliaridis** [comment]
The module uses `org.springframework.boot:spring-boot-starter-jetty:3.2.5`, which transitively depends on Jetty 12. Therefore, related to https://github.com/apache/solr/pull/2782.

**Pull request closed without merging**
