### PR TITLE
SOLR-15917: Rename contrib -> modules

### PR DESCRIPTION
**Pull request by HoustonPutman**
https://issues.apache.org/jira/browse/SOLR-15917

This is a big patch obviously, but I think I've curated into some reasonable commits.

I've run the following gradle commands, and all look good:

- `check`
- `installDist`
- `testDocker`
- `testDockerfileOfficial`

Happy to test whatever else.

### CODE REVIEW

**Comment by risdenk** [comment]
It might be worth testing nightly?

Here is an example of testing all the `hdfs` related tests that I've been running for other stuff. It should take about 20 min:

```
/gradlew test --tests "*hdfs*" --tests "*Hdfs*" --tests "*HDFS*" --tests "*Hadoop*" -Ptests.jvms=4 -Ptests.jvmargs=-XX:TieredStopAtLevel=1 -Ptests.nightly=true -Ptests.awaitsfix=false -Ptests.badapples=false -Ptests.file.encoding=UTF-8
```

I have no idea how long nightly tests take regularly. Feel free to play with with `--tests`

**Review by janhoy — COMMENTED** [review]
LGTM. 
Thanks for structuring the commits like that.
I have not compiled or tested this and obioulsy not looked through every change. So I support running Slow and Nightly tests a few times.

With this many RefGuide changes I'm afraid there may be a ton of manual work for @ctargett to port things over to the Antora branch. And the only way to avoid that is to let her merge that branch before this one - but then the burden rests on yourself.

I did a test merge here and there is only 12 adoc files conflicting, and in each of those there are a handful of lines that contain both contrib->modules change and e.g. a `xref:` link style change. So from my sampling the job seems doable either way.

**Comment by ctargett** [comment]
I'm fine with merging this and dealing with the merge conflicts in the Antora branch, I suspect these would be relatively minor. If this is ready, let's keep making progress IMO.

**Comment by HoustonPutman** [comment]
Ok after many rounds of testing the Nightly & HDFS tests, only 1 fails: `SharedFSAutoReplicaFailoverTest`. However this fails on main for me consistently, so I don't think it is relevant.

Will make a writeup on `major-changes-in-9.adoc`, then after a review of that I'll go ahead and merge (& backport) this.

**Pull request merged**
