### PR TITLE
SOLR-16928: Add missing unit tests for RegexFileFilter and StrUtils.toLower

### PR DESCRIPTION
**Pull request by jrhenderson1988**
https://issues.apache.org/jira/browse/SOLR-16928

# Description

Adding some unit tests that cover the `RegexFileFilter` class and the `StrUtils.toLower` method

# Solution

N/A

# Tests

N/A

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by mkhludnev — APPROVED** [review]

**Comment by jrhenderson1988** [comment]
@mkhludnev Thanks for approving. The build seems to have failed and I don't think it's related to my change. However, I'm unable to re-run the build. Would you be able to kick it off again, please?

**Comment by mkhludnev** [comment]
Yeah, @jrhenderson1988 `SplitShardWithNodeRoleTest.testSolrClusterWithNodeRoleWithPull` have failed. Kicked test off again.

**Comment by mkhludnev** [comment]
I think, we might not mention it in CHANGES.txt. WDYT?

**Comment by jrhenderson1988** [comment]
@mkhludnev Thanks for kicking off again. Looks to have passed this time.

> I think, we might not mention it in CHANGES.txt. WDYT?

I'm not sure that I understand. Would you like me to add something to CHANGES.txt under the 10.0.0 release, or do you think it is not necessary? Please let me know if you'd like me to add something, and I can do that. Otherwise, you can feel free to merge this PR whenever you are ready 🙂

**Comment by mkhludnev** [comment]
Thanks, Jonathon. I'm for merging and picking it into 9, without mention in CHANGES. I'm taking a pause for a while to check if there's an alternative opinion.

**Comment by jrhenderson1988** [comment]
Sounds good! Let me know if there's anything you need from me

**Pull request merged**
