### PR TITLE
Link Solr Operator for learning on Solr in Kubernetes, and better exp…

### PR DESCRIPTION
**Pull request by jebnix**
…lain the relevancy of docker-networking

https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

The Docker networking page seems to have a pretty old description. While this page is still relevant (mainly for local development), it is important to link Solr Operator to the subject. In general, it seems like a pretty blog kind of a page, therefore I've also removed the "I" and "I'll" words, and replaced them with "We" and "We'll" which seems more professional.

# Solution

described

# Tests

No

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by jebnix** [comment]
@epugh @janhoy I'm thinking whether we should [migrate this blog post](https://lucidworks.com/post/running-solr-on-kubernetes-part-1/) into a page of its own (some sort of "Solr in Kubernetes" page with general tips), or whether the Solr Operator project is enough.
After all there are people who'll use Kubernetes without the Operator...

**Comment by janhoy** [comment]
What about removing the entire page https://solr.apache.org/guide/solr/latest/deployment-guide/docker-networking.html?

And add a new page "Solr in Kubernetes" which alongside or below "Solr in Docker", as a very short introduction to the subject and then a link to the Solr-operator project?

**Comment by janhoy** [comment]
I feel that the entire "Solr in Docker" content needs a rewrite. It was dumped into the refguide, but was not initially written for the refguide.

Personally I have never used the `solr-precreate` script or other custom scripts of the image, probably because I no longer maintain any standalone clusters, only Cloud. But that may be my preference. If those scripts are frequently used, they should definitely be described in the refguide.

However, the networking page is a way too detailed and hacky workarounds trying to make ZK run in a cluster in prod. I cannot say it is something I'd recommend to a client, so let's point them to the Operator, and perhaps some 3rd party maintained way of running ZK standalone in Docker for those with such needs.

**Comment by HoustonPutman** [comment]
> I feel that the entire "Solr in Docker" content needs a rewrite. It was dumped into the refguide, but was not initially written for the refguide.

Completely agree. I dumped it because rewriting it at the time would have been too much work on top of migrating everything else. But it really needs to be fixed up or just redone entirely.



> Personally I have never used the `solr-precreate` script or other custom scripts of the image, probably because I no longer maintain any standalone clusters, only Cloud. But that may be my preference. If those scripts are frequently used, they should definitely be described in the refguide.

I don't either, but we should keep the docs around as long as the scripts are still included.

> However, the networking page is a way too detailed and hacky workarounds trying to make ZK run in a cluster in prod. I cannot say it is something I'd recommend to a client, so let's point them to the Operator, and perhaps some 3rd party maintained way of running ZK standalone in Docker for those with such needs.

+1

**Comment by jebnix** [comment]
@HoustonPutman I don't understand if you're voting for removing the page since you've said
> but we should keep the docs around as long as the scripts are still included
If you both agree to remove the page I'll add this to the PR. I'll also add to this PR the `Solr in Kubernetes` page.

**Comment by janhoy** [comment]
Maybe the gist of the networking page can be summarized as “Running distributed Zookeeper requires stable host names and IP addresses. Although possible, we discourage rolling your own zookeeper cluster in Docker. Dev/test instances can use a single node.”

Maybe we can link to somewhere in the zookeeper project?

**Comment by jebnix** [comment]
@janhoy What link exactly?

**Comment by janhoy** [comment]
> @janhoy What link exactly?

I'd just link to https://hub.docker.com/_/zookeeper and let users turn to the Zookeeper project for any support on how to make replicated Zookeeper work in plain Docker, Docker Swarm or any other orchestrator other than Kubernetes.

**Comment by janhoy** [comment]
Looks like this PR lost some steam. It is not my intention to shoot down suggestions - a cleanup of this content is definitely needed! I'd opt for shortening it down rather than adding more content though.. Feel free to sketch out an outline of the changes you plan to do after the discussions above. I'd love to review a PR with some of this cleanup!

**Comment by janhoy** [comment]
The changes in this pr is an improvement in itself so perhaps merge it and the  embark on a rewrite later?

**Comment by janhoy** [comment]
I pushed some changes
* Remove docker-networking page
* Replace the FAQ bullet about cluster and zk, with a few paragraphs linking to Solr Operator and Zookeeper docker
* Removed FAQ advice on using `--link` between containers as it is definitely not a good advice anymore

I plan to merge this next week if no objections

**Comment by epugh** [comment]
This looks much nicer...    Does this also cover some of the other patches that @jebnix provided?   Thanks @janhoy  for taking up some of these old PR's!

**Comment by janhoy** [comment]
> This looks much nicer... Does this also cover some of the other patches that @jebnix provided?

This is mainly related to running zookeeper and the cloud paragraph.

See #2277 for more cleanup of faq file.

**Comment by epugh** [comment]
@janhoy I was looking at the `solr-in-docker.adoc` page from the perspective of making sure the use of the `solr post` tool was working, and I noticed a lot of glitches.....   Would it make sense for me to push my  fixes (since some overlap witht his one) to this PR instead of making my own...   For example, I found the same issues in the example `docker-compose.yml` file...

**Comment by janhoy** [comment]
Let me try to land this first, then you follow on with those improvements, and I’m sure many more will follow too?

**Comment by epugh** [comment]
Sure!

**Comment by HoustonPutman** [comment]
Sorry, I was out on vacation. Thanks for finishing this up and seeing it through!

**Pull request merged**
