### PR TITLE
SOLR-17079: Allow to declare replica placement plugins in solr.xml

### PR DESCRIPTION
**Pull request by pvcnt**
https://issues.apache.org/jira/browse/SOLR-17079

# Description

Currently, container-level plugins can only be declared installed via calls to /cluster/plugin APIs. In some situations (especially corporate ones having tight security requirements), it is not possible to mutate the configuration of a cluster at runtime. Cluster should rather be configured fully at startup, and any change in config requires a re-deployment.

# Solution

While there are several affected plugins, this PR makes it possible to configure replica placement (only) plugins in solr.xml. This default plugin will be installed by default, and can still be overridden by cluster plugins.

# Tests

Enriched existing integration tests.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by dsmiley** [comment]
Looks good!

**Review by HoustonPutman — COMMENTED** [review]
This is a great change! Definitely needs documentation in the solr XML ref guide page though, also probably needs to be linked in the Placement Plugins page.

**Comment by pvcnt** [comment]
Sure, I was looking for feedback about the approach first! Since this looks acceptable, I added some tests and documentation for the feature.

**Comment by ycallea** [comment]
Thanks @pvcnt for proposing this enhancement, `solr.xml` definitely feels like a great place for configuring placement plugins 🙂

I am looking forward to this feature especially for configuring the Affinity placement plugin without having to rely on the `/cluster/plugin` API !

**Review by dsmiley — APPROVED** [review]
It's looking quite nice!

**Comment by pvcnt** [comment]
I added a line in CHANGES.txt and a precision in documentation about the class attribute in solr.xml. Btw, there are tests in `TestXLSXResponseWriter` failing in CI, but I cannot reproduce locally (and it does not really seem related to my change).

**Comment by dsmiley** [comment]
The XLSX issue is only on Crave pertaining to the JDK used there being somewhat incomplete.  I reported it and it should be fixed soon if not already.

So I merged this but I should have checked more carefully; there are test failures.  For example PlacementPluginIntegrationTest has 3 new tests and they create a CoreContainer but don't shut them down.  I pushed a quick fix for that.  But there are also test failures in OverseerCollectionConfigSetProcessorTest.  I ignored that test temporarily; can you please look into this soon with fix PR?

**Comment by pvcnt** [comment]
Ooops, sorry about that. Is there a view of all tests failures in a CI run? Or is there a way to configure that? I know that in Jenkins we can have a specific view of all failing tests instead of scrolling into logs looking for failing tests buried somewhere.

Anyway, thank you for fixing one of those, and here is the fix for the other one: #2085 2085

**Comment by cpoerschke** [comment]
> ... Btw, there are tests in `TestXLSXResponseWriter` failing in CI, but I cannot reproduce locally (and it does not really seem related to my change).

Filed https://issues.apache.org/jira/browse/SOLR-17081 for visibility.

**Pull request merged**
