### PR TITLE
SOLR-17321: Fix TestSolrCoreSnapshots.testBackupRestore

### PR DESCRIPTION
**Pull request by iamsanjay**
TestSolrCoreSnapshots.testBackupRestore test started failing on Windows after merging #2501.

Thank you @HoustonPutman for reporting this. This one specifically failed due to the backslash in the windows location path that passed to the URI ctor. 

The solution for this issue is to encode all the passed params before passing it to the URI ctor.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by iamsanjay** [comment]
Is there anyway to test this on Windows?

**Comment by iamsanjay** [comment]
Replaced the `StringBuilder` with `URIBuilder` and also there is no need to explicitly encode the params as `URIBuilder` takes care of it. 

Is there any way to test `TestHdfsBackupRestoreCore`?

**Review by epugh — APPROVED** [review]
LGTM.   Is the URIBuilder something that we should be using in more places?

**Comment by HoustonPutman** [comment]
> LGTM. Is the URIBuilder something that we should be using in more places?

I certainly think so

**Comment by epugh** [comment]
> > LGTM. Is the URIBuilder something that we should be using in more places?
> 
> 
> 
> I certainly think so

How do we get these tasks actually tracked and moved forward?  Worth opening a jira?  We have a patten of "we should do" but then it's just in our heads!

**Comment by dsmiley** [comment]
`URIBuilder` is in the Apache HttpClient dependency, using it goes in the opposite direction we're trying to go in!  Granted in tests, this isn't a priority, so this PR is acceptable.  But be mindful please.

> We have a patten of "we should do"

That could be quite a list; I'm not sure what tracking it accomplishes.  If something is important enough, create a JIRA.  Ideally when a "we should do" is identified, it can be done everywhere instead of just one spot.

**Pull request merged**
