### PR TITLE
SOLR-17038: /admin/segments handler: Expose the term count

### PR DESCRIPTION
**Pull request by rahulgoswami**
https://issues.apache.org/jira/browse/SOLR-17038

# Description

Added fieldFlags.add("termCount", terms.size()) in SegmentsInfoRequestHandler to add termsCount when ?fieldInfo=true

# Solution

Added fieldFlags.add("termCount", terms.size()) in SegmentsInfoRequestHandler to add termsCount when ?fieldInfo=true

# Tests

No specific test cases added since currently there are no test cases for individual properties in the handler output.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by rahulgoswami** [comment]
One odd thing that I noticed was that upon running /gradlew tidy updateLicenses check -x test it ended up deleting solr/licenses/jakarta.inject-2.6.1.jar.sha1 . Don't think updateLicenses task should do that since there is no dependency removal because of this change.

**Comment by cpoerschke** [comment]
Thanks @rahulgoswami for opening this pull request!

May I suggest to undo the removal of the `.sha1` file -- it appears to be unrelated to the handler changes (and tidy or precommit prompting for the removal needs separate investigation i.e. thanks for indirectly surfacing this issue).

> Added fieldFlags.add("termCount", terms.size()) in SegmentsInfoRequestHandler to add termsCount when ?fieldInfo=true

optional suggestion: addition of class level javadocs to make the `fieldInfo=true` parameter more discoverable

> No specific test cases added since currently there are no test cases for individual properties in the handler output.

optional suggestion: additional test coverage e.g. expanding `SegmentsInfoRequestHandlerTest.testFieldInfo` https://github.com/apache/solr/blob/releases/solr/9.4.1/solr/core/src/test/org/apache/solr/handler/admin/SegmentsInfoRequestHandlerTest.java#L155-L179

**Comment by rahulgoswami** [comment]
Incorporated review comments by @cpoerschke : 1) Added back jakarta.inject-2.6.1.jar.sha1 removed while running ./gradlew tidy updateLicenses check -x test  
2) Added tests for new and existing field flags when fieldInfo=true

**Review by cpoerschke — APPROVED** [review]

**Comment by rahulgoswami** [comment]
The (unrelated) hadoop-auth test module keeps failing. Bad apple ?

**Comment by cpoerschke** [comment]
> The (unrelated) hadoop-auth test module keeps failing. Bad apple ?

I would agree that it's unrelated. Had a look at https://github.com/apache/solr/blob/main/dev-docs/FAQ.adoc#where-can-i-find-information-about-test-history resources and found no obvious history of previous failures.

**Comment by rahulgoswami** [comment]
Thanks for merging the PR @cpoerschke!

**Pull request merged**
