### PR TITLE
SOLR-16363: DirectUpdateHandler2 should not throw UnknownFormatConversionException

### PR DESCRIPTION
**Pull request by risdenk**
https://issues.apache.org/jira/browse/SOLR-16363

Based on IntelliJ analysis, this is the only place in Solr code base where String.format has String concatenation. So this should be the only place this is a problem.

### CODE REVIEW

**Comment by dsmiley** [comment]
Can we please consider not using String.format here at all?  String.format is useful when there is non-trivial formatting.  I don't think we should use String.format when a trivial String concatenation can do the job.  I don't understand why some people reach for more complex tools like this when the language itself is adequate.

We wouldn't even need a test.

**Comment by dsmiley** [comment]
Wow; let's allow more time to review please?

**Comment by risdenk** [comment]
> Can we please consider not using String.format here at all? String.format is useful when there is non-trivial formatting. I don't think we should use String.format when a trivial String concatenation can do the job. I don't understand why some people reach for more complex tools like this when the language itself is adequate.

hmm good point. I mistakenly hit the merge button on this trying to merge the commons-text one. I can follow up w/ this change.

**Comment by risdenk** [comment]
> We wouldn't even need a test. 

I'm going to leave the test - it tests the `IllegalArgumentException` code path in `DirectUpdateHandler2` that doesn't seem to be tested elsewhere. new PR incoming soon w/ `String.format` removed.

**Comment by risdenk** [comment]
https://github.com/apache/solr/pull/1124 to remove String.format from DirectUpdateHandler2

**Pull request merged**
