### PR TITLE
Upgrade to Jetty 9.4.45.v20220203

### PR DESCRIPTION
**Pull request by risdenk**
https://issues.apache.org/jira/browse/SOLR-XXXXX

### CODE REVIEW

**Comment by madrob** [comment]
Maybe not needed in favor of #585 ?

**Comment by risdenk** [comment]
@madrob yea totally possible just saw it could be upgraded while looking at other stuff so threw the PR up.

**Comment by markrmiller** [comment]
Would probably make sense in the likely case Jetty 10 doesn't go out in 9.0 or if there is another 8.x release.

**Comment by risdenk** [comment]
@anshumg sure (there is 9.4.46 now). I never created a jira.

**Pull request closed without merging**
