### PR TITLE
SOLR-16837: Introducing AffinityPlacementFactory.withCollectionShards…

### PR DESCRIPTION
**Pull request by mkhludnev**
… to collocate shards for join operation. (Mikhail Khludnev)

https://issues.apache.org/jira/browse/SOLR-16837

### CODE REVIEW

**Review by tflobbe — APPROVED** [review]
LGTM, make sure you rebase after https://github.com/apache/solr/pull/1696. Also, probably want to coordinate with @HoustonPutman because this will heavily conflict with https://github.com/apache/solr/pull/1650

**Comment by HoustonPutman** [comment]
Yeah, it looks like https://github.com/apache/solr/pull/1650 has buy-in. I'm happy to do the refactor here after that's merged, but I'd appreciate it if we merge the big one first. It's going to make this code much simpler anyways.

**Comment by mkhludnev** [comment]
Sure, @HoustonPutman take your time. I'll revamp this after #1650 is landed.

**Comment by mkhludnev** [comment]
dropping in favor of #1709

**Pull request closed without merging**
