### PR TITLE
SOLR-16029: Enable spotless on ltr module

### PR DESCRIPTION
**Pull request by risdenk**
https://issues.apache.org/jira/browse/SOLR-16029

### CODE REVIEW

**Comment by cpoerschke** [comment]
#189 from some time ago now updated, it covers only the non-test portion of the code (53 files changed), if we proceeded with those changes first then #664 here could target the test code separately (95 - 53 = 42 files).

Thanks @risdenk for reviving the spotless effort!

**Comment by risdenk** [comment]
Updated after https://github.com/apache/solr/pull/189 was merged.

**Review by HoustonPutman — APPROVED** [review]
The precommit and tests pass for the module, so it's likely good to go, especially since it's just tests.

**Review by cpoerschke — COMMENTED** [review]
LGTM

**Pull request merged**
