### PR TITLE
SOLR-16563 DefaultCollectionSolrClient

### PR DESCRIPTION
**Pull request by dsmiley**
A draft of an idea expressed in
https://issues.apache.org/jira/browse/SOLR-16563 and earlier in https://issues.apache.org/jira/browse/SOLR-12502

### CODE REVIEW

**Comment by dsmiley** [comment]
The initial impl was more of a "default" and hence the name DefaultCollectionSolrClient.  But I felt it shouldn't be merely a default, it should be more of a chroot idea; an intentional limitation / scope.  Just `CollectionSolrClient` would be better.

**Comment by epugh** [comment]
@dsmiley I tried using the `DefaultCollectionSolrClient` with out much success.  Everywhere wanted a CloudSolrClient...   Or, I didn't have setters in the testing infrastructure to take in a `DefaultCollectionSolrClient`....    So not sure here.

I am now wondering if having `setDefaultCollection` is that bad?   Maybe it's okay to have it there.  Or, rip the band-aid off and force the use of collectionName everywhere?   At least, in our test infrastrutture?

**Comment by epugh** [comment]
I don't think right now I am going to push forward with this approach....   While it may have value in general, it didn't make it easier for me to migrate the tests away from changing the collection that the client was pointed at.  Instead, I am working on updating the tests to not require/need the use of a `solrClient.setDefaultCollection()` method...

**Comment by dsmiley** [comment]
I'm seeing that this very DefaultCollectionSolrClient has value for users as an independent utility someone can opt-in to use.  I'm inclined to reposition it as that.

**Pull request closed without merging**
