### PR TITLE
SOLR-16562 / SOLR-16578: Upgrade caffeine to 3.1.4 and errorprone to 2.18.0

### PR DESCRIPTION
**Pull request by solrbot**
This PR contains the following updates:

| Package | Type | Update | Change | Pending |
|---|---|---|---|---|
| [com.github.ben-manes.caffeine:caffeine](https://togithub.com/ben-manes/caffeine) | dependencies | patch | `3.1.2` -> `3.1.3` | `3.1.4` |

---

### Release Notes

<details>
<summary>ben-manes/caffeine</summary>

### [`v3.1.3`](https://togithub.com/ben-manes/caffeine/releases/tag/v3.1.3): 3.1.3

Cache

-   Fixed the build time dependency constraints from being leaked into the external metadata ([#&#8203;867](https://togithub.com/ben-manes/caffeine/issues/867))
-   Fixed the cause of a removal notification for a discarded refresh when the entry was removed
-   Fixed the behavior for null lookups into returned unmodifiable maps to be consistent ([#&#8203;864](https://togithub.com/ben-manes/caffeine/issues/864))
-   Fixed an unexpected delay of removal notifications when using a scheduler ([#&#8203;859](https://togithub.com/ben-manes/caffeine/issues/859))
-   Fixed explicit refreshes from being deduped if the entry is pending eviction
-   Defaulted methods to [@&#8203;CheckReturnValue](https://errorprone.info/bugpattern/CheckReturnValue) for static analysis ([#&#8203;863](https://togithub.com/ben-manes/caffeine/issues/863))
-   Reduced the lock hold time during Map.clear ([#&#8203;835](https://togithub.com/ben-manes/caffeine/issues/835))

JCache

-   Fixed `putAll` with an immutable map that causes an exception when using a cache writer ([#&#8203;841](https://togithub.com/ben-manes/caffeine/issues/841))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "* 8-20 * * *" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/solrbot/renovate-github-action)

### CODE REVIEW

**Comment by risdenk** [comment]
This one needs a closer look. This ends up being a relatively bigger change due to changes to how caffeine fixed their transitive dependencies. https://issues.apache.org/jira/browse/SOLR-16562 has some details and https://github.com/apache/solr/pull/1198#issuecomment-1336503053

**Review by risdenk — CHANGES_REQUESTED** [review]
This one needs a closer look. This ends up being a relatively bigger change due to changes to how caffeine fixed their transitive dependencies. https://issues.apache.org/jira/browse/SOLR-16562 has some details and https://github.com/apache/solr/pull/1198#issuecomment-1336503053

**Comment by risdenk** [comment]
I wonder why this didn't go directly to 3.1.4? - https://github.com/ben-manes/caffeine/releases/tag/v3.1.4

**Comment by janhoy** [comment]
3.1.4 was released 4 days and we use a 5 day delay, so it will likely be updated tomorrow.

**Review by risdenk — CHANGES_REQUESTED** [review]
I checked the changed dependencies. The only one that we currently manage in `versions.props` is errorprone and so need to update `versions.props` with `com.google.errorprone:*=2.18`.

**Comment by chatman** [comment]
@janhoy Can we add a [renovatebot] to the PR title, please? I think dependabot used to do that.

**Comment by janhoy** [comment]
We can customize title, but I’d instead like to add label “dependencies” on all these. Requires Solr bot to have “triage” karma, but that’s easily done in asf.yaml

**Comment by janhoy** [comment]
X-ref https://github.com/apache/solr/pull/1400 - which will be auto closed once this is merged.

**Comment by janhoy** [comment]
Found existing JIRA https://issues.apache.org/jira/browse/SOLR-16562 for 9.2, so I tagged title and bumped CHANGES

**Review by risdenk — APPROVED** [review]

**Comment by risdenk** [comment]
Added changes to SOLR-16578 for errorprone since might as well fix that entry too.

**Pull request merged**
