### PR TITLE
Fix typo in the user-managed mode explanation

### PR DESCRIPTION
**Pull request by jebnix**
https://issues.apache.org/jira/browse/SOLR-XXXXX

# Description

Typo

# Solution

Fix it with better grammar

# Tests

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by epugh** [comment]
What do you think about `will be` ???   Thanks for chasing these grammer items!

**Comment by jebnix** [comment]
I've updated the PR

**Comment by epugh** [comment]
Thanks for this!

**Comment by jebnix** [comment]
@epugh 
> Solr's user-managed mode requires that cluster coordination activities that SolrCloud normally uses ZooKeeper for are performed manually or with local scripts.

That ain't good. A comma is required here:

> Solr's user-managed mode requires that cluster coordination activities that SolrCloud normally uses ZooKeeper **for,** are performed manually or with local scripts.

**Pull request merged**
