### PR TITLE
SOLR-16574: Demonstrate Dense Vectors and KNN as part of the Films example

### PR DESCRIPTION
**Pull request by gabrielmagno**
https://issues.apache.org/jira/browse/SOLR-16574

# Description

Enrich the `films` example to demonstrate how to use the Dense Vectors feature.

# Solution

Added the field `film_vector` to the films dataset. This is an embedding vector created to represent the movie with 10 dimensions. The vector is created by combining the first 5 dimensions of a pre-trained BERT sentence model applied on the name of the movies plus the name of the genres, followed by an item2vec 5-dimensions model of itemset co-occurrence of genres in the movies, totaling 10 dimensions. Even though it is expected that similar movies will be close to each other, this is just a "toy example" model to serve as source for creating the films vectors.

The `README` of the example was also updated to include the specification of the Dense Vector field in the schema. Also, a new section was created, with examples showing how to make KNN queries with the vectors.

# Tests

- Added the new field `film_vector` to the 3 dataset formats (JSON, XML, CSV), making sure to preserve the exact same data from the original datasets, so that the "diff" will be only the appendage of the new field.
- Checked the creation of the collection for the 3 dataset formats. Regardless of the format all the 1100 films were indexed, and the `film_vector` field was correctly parsed and indexed as well.
- Checked the KNN example queries for all the 3 dataset formats.

# Checklist

Please review the following and check all that apply:

- [X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [X] I have created a Jira issue and added the issue ID to my pull request title.
- [X] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [X] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by gabrielmagno** [comment]
I tried running `gradlew check`, but got an error that I don't think is related to the changes of this PR:
```
> Task :solr:solr-ref-guide:buildLocalAntoraSite FAILED
/home/gabrielmagno/dev-solr/apache-solr/.gradle/node/solr-ref-guide/node_modules/@antora/ui-loader/lib/load-ui.js:180
      if (response.statusCode !== 200) {
                   ^

TypeError: Cannot read properties of undefined (reading 'statusCode')
    at /home/gabrielmagno/dev-solr/apache-solr/.gradle/node/solr-ref-guide/node_modules/@antora/ui-loader/lib/load-ui.js:180:20
    at ClientRequest.<anonymous> (/home/gabrielmagno/dev-solr/apache-solr/.gradle/node/solr-ref-guide/node_modules/simple-get/index.js:88:21)
    at ClientRequest.f (/home/gabrielmagno/dev-solr/apache-solr/.gradle/node/solr-ref-guide/node_modules/once/once.js:25:25)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by epugh** [comment]
How hard would it be to include the steps you did for vectorization?  I notice that most tutorials start with the vectors...   However, what if I wanted to play with this example and add my own tweaks to the vector?   Is creating the vector a simple script, or was it a ton of work and out of scope????

**Comment by epugh** [comment]
i think I'm mostly thinking, what if I add a new movie to the list...   or want to play with it, can we provide that script as well?   I sometimes dream that the vecotrization process is supported by Solr ;-)   You could imagine a ScriptingUpdateRequestProcessor stage that called out to a service to do it..   Or even do it direclty!

**Comment by gabrielmagno** [comment]
Having a builtin model loader and vector encoder in Solr would be amazing!

Regarding the current vector example, how about I recreate the vectors with the 1-algorithm solution (extracting the first 10 dimensions), then provide the instructions (code) of how to vectorize the movies?

**Comment by gabrielmagno** [comment]
Hey @epugh !

I've created a new model and have put the Python scripts that were used to create the model and calculate the films vectors inside a subfolder called `vectors`.

**Comment by gabrielmagno** [comment]
Gradlew returned and error:
```
Execution failed for task ':solr:example:rat'.
> Detected license header issues (skip with -Pvalidation.rat.failOnError=false):
  Unknown license: /home/runner/work/solr/solr/solr/example/films/vectors/films.py
  Unknown license: /home/runner/work/solr/solr/solr/example/films/vectors/create_dataset.py
  Unknown license: /home/runner/work/solr/solr/solr/example/films/vectors/create_model.py
```

Not sure how to proceed.

**Comment by epugh** [comment]
progress is looking great!

**Comment by epugh** [comment]
@gabrielmagno  are you ready for me to review this PR?  I was sort of waiting till you gave me the all clear!

**Comment by gabrielmagno** [comment]
Hey @epugh!

Yeah, at least from my side I think I have finished it.
Sorry for not making that more clear 😅

By the way, sonatype complained about using lxml, but since we are creating the XML and not really parsing a XML, I think we could ignore it.

You can go ahead and review it.
Thank you very much!

**Comment by epugh** [comment]
@gabrielmagno how do you want to be credited in `CHANGES.txt`?

**Comment by epugh** [comment]
`bin/solr start -example films` no longer creates all the fields....

**Comment by epugh** [comment]
This is looking really cool...    I wonder, is it worth docuemnting running the python scripts?

**Comment by gabrielmagno** [comment]
Hey @epugh !

You can credit me as "Gabriel Magno".

What about I create a readme file inside the "vectors" folder, explaining the utilization of the scripts?

**Comment by krickert** [comment]
Hello - I just saw these requests and I'd like to (eventually) have a full blog post as to how to create the vector for input with the example being a full wikipedia dump using java, a pretrained model, and deeplearning4j.  I suspect once I have this completed, this can help create an example that can lead to this being a feature in solr.

Would anyone be up for a discussion on this?  I suppose this point might not be the best place to ask - but this thread is the closest to finding someone who is trying to accomplish the same thing as I'm doing.

**Comment by krickert** [comment]
Thanks!

I have to get it to the point where I get the dents vectors and the vector
search working first :) after that I would be glad to write a tutorial.

I'll open up a discussion. I'd like someone to ensure that I'm calculating
the debate vectors right.  Thanks. I'll ask there!

**Comment by dsmiley** [comment]
Next time, please put newlines at the end of each sentence in our asciidoc, as is consistent with most of our asciidoc.  It's much easier to consume in diffs.

**Comment by epugh** [comment]
I wish we had a lint checker for this kind of thing.   We have a lot of "best practices" in writing code, but they are all enforced manually ;-(.    I did google briefly for "ventilated prose lint checker" with no luck.   https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line

**Pull request merged**
