### PR TITLE
Update the GHA script to account for the new clone location

### PR DESCRIPTION
**Pull request by uvatbc**
# Description

With the recent change to the cloning mechanism in Crave, the sources are cloned in a slightly different location: Instead of it being inside a solr subdirectory, it will be in the parent.

Fix the GHA yaml to account for this.

# Solution

The solr subdirectory is no longer required in the scripts. Remove it

# Tests

This GHA should only be merged after the Solr GHA runners are restarted post upgrade to latest Crave version

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [ ] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Comment by janhoy** [comment]
Error
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by uvatbc** [comment]
> Error
> 
> > Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Yes, this change is preparing for the new Crave infra. The GHA wont pass until we upgrade Crave.     
I'm holding off the upgrade for a time when its a bit quiet.

Is there a good time frame when the Solr community isn't doing much?

**Comment by dsmiley** [comment]
@uvatbc now :-) or whenever I guess

**Comment by uvatbc** [comment]
> @uvatbc now :-) or whenever I guess

Upgraded! Can you run this GHA please?

**Comment by uvatbc** [comment]
Yay! It worked!

**Comment by dsmiley** [comment]
LMK if we should merge.  I recall there was a PR... I thought this one, that you didn't want to actually merge.

**Comment by uvatbc** [comment]
Yes this is the PR that I had said we need to not merge until the upgrade is done.
The upgrade is done, and that's the reason why the tests actually work for this one.

It should now be merged.

**Pull request merged**
