### PR TITLE
SOLR-16213 Upgrade Jackson to 2.13.3

### PR DESCRIPTION
**Pull request by janhoy**
https://issues.apache.org/jira/browse/SOLR-16213

### CODE REVIEW

**Review by risdenk — APPROVED** [review]

**Comment by janhoy** [comment]
Not sure I understand why precommit fails here
> [21:05:39.470] FATAL (antora): problem encountered while reading ui.supplemental_files: ENOENT: no such file or directory, access '/home/runner/work/solr/solr/.gradle/node/solr-ref-guide/node_modules/@antora/lunr-extension/supplemental_ui'

Wonder if that is some stale builder cache issue, seems unrelated.

**Comment by HoustonPutman** [comment]
> Not sure I understand why precommit fails here
> 
> > [21:05:39.470] FATAL (antora): problem encountered while reading ui.supplemental_files: ENOENT: no such file or directory, access '/home/runner/work/solr/solr/.gradle/node/solr-ref-guide/node_modules/@antora/lunr-extension/supplemental_ui'
> 
> Wonder if that is some stale builder cache issue, seems unrelated.

It looks like the upstream antora-lunr-extension changed it's download path in the node modules? Will make a fix soon

**Comment by HoustonPutman** [comment]
Ahh ok it's here. Just making our lives easier 🙂 

https://gitlab.com/antora/antora-lunr-extension/-/issues/15

**Comment by risdenk** [comment]
@janhoy I pushed the merging to main to get precommit fixes from Houston.

**Pull request merged**
