### PR TITLE
SOLR-16457: Use pwd -P

### PR DESCRIPTION
**Pull request by risdenk**
https://issues.apache.org/jira/browse/SOLR-16457

### CODE REVIEW

**Review by HoustonPutman — APPROVED** [review]
Nice! Glad we can get rid of that envVar

**Comment by elyograg** [comment]
Looks good to me.  I'm not familiar with the docker stuff that's gets one line removed or what that will do.

**Comment by risdenk** [comment]
> Looks good to me. I'm not familiar with the docker stuff that's gets one line removed or what that will do.

I added the docker env var line when I implemented SOLR-16457 which works around the symlink stuff specifically only for Docker. Since `pwd -P` fixes this issue in bin/solr no need to fix it in Docker anymore.

**Review by elyograg — APPROVED** [review]
@risdenk helped me find the approve button.

**Pull request merged**
