### PR TITLE
SOLR-14667 Make zkClientTimeout consistent and based on a system property

### PR DESCRIPTION
**Pull request by stillalex**
https://issues.apache.org/jira/browse/SOLR-14667

# Description

Pulling together all zk client timeout values that I could find in a single class `SolrZkClientTimeout`. not the best name, open to suggestions. location of this class is in solrj module, also open to suggestions. values are based on system properties with a default of 30s.
A bit of extra work went into providing setters for these values via the CloudHttp2SolrClient and CloudLegacySolrClient builders. this will make things a bit simpler client side, if anyone does not want to rely purely on system properties.

I have also started a discussion on the dev list for the [ZkCmdExecutor class](https://lists.apache.org/thread/g42bg5v6twps2y5pwdyqtzhm2rnx943k). there were no changes to this class in this PR. I ended up not needing to touch it. if anything comes out of that thread, it could be its own PR.

# Solution

Please provide a short description of the approach taken to implement your solution.

# Tests

Please describe the tests you've developed or run to confirm this patch implements the feature or solves the problem.

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [x] I have added tests for my changes.
- [x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by epugh — APPROVED** [review]
This all makes sense to me.   I have dreams someday of a single place to configure all your various settings for Solr, so they aren't distributed all over the place, so getting these hardcoded settings into a single class makes sense to me....

**Comment by stillalex** [comment]
thank you for the review @epugh. will leave this open for a bit more, if no other comments will merge it as is. we can rename later if anyone finds a better name for this config class.

**Comment by stillalex** [comment]
did a force push to have another build run. not sure if there is an easier way to do this

**Review by epugh — COMMENTED** [review]
LGTM.

**Pull request merged**
