### PR TITLE
Capture build scans on ge.apache.org to benefit from deep build insights

### PR DESCRIPTION
**Pull request by clayburn**
# Description

This PR publishes a build scan for every CI build on Jenkins and GitHub Actions and for every local build from an authenticated Apache committer. The build will not fail if publishing fails.

The build scans of the Apache Solr project are published to the Gradle Enterprise instance at [ge.apache.org](https://ge.apache.org/), hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle. This Gradle Enterprise instance has all features and extensions enabled and is freely available for use by the Apache Solr project and all other Apache projects.

This pull request enhances the functionality of publishing build scans to the publicly available [scans.gradle.com](https://scans.gradle.com/) by instead publishing build scans to [ge.apache.org](https://ge.apache.org/). On this Gradle Enterprise instance, Apache Solr will have access not only to all of the published build scans but other aggregate data features such as:

Dashboards to view all historical build scans, along with performance trends over time
Build failure analytics for enhanced investigation and diagnosis of build failures
Test failure analytics to better understand trends and causes around slow, failing, and flaky tests
If interested in exploring a fully populated Gradle Enterprise instance, please explore the builds already connected to [ge.apache.org](https://ge.apache.org/), the [Spring project’s instance](https://ge.spring.io/scans?search.relativeStartTime=P28D&search.timeZoneId=Europe/Zurich), or any number of other [OSS projects](https://gradle.com/enterprise-customers/oss-projects/) for which we sponsor instances of Gradle Enterprise.

Please let me know if there are any questions about the value of Gradle Enterprise or the changes in this pull request and I’d be happy to address them.

# Solution

N/A - This PR is a Gradle build enhancement

# Tests

N/A - This PR does not affect functional code in the project

# Checklist

Please review the following and check all that apply:

- [x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ ] I have created a Jira issue and added the issue ID to my pull request title.
- [x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [x] I have developed this patch against the `main` branch.
- [x] I have run `./gradlew check`.
- [ ] I have added tests for my changes.
- [ ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)

### CODE REVIEW

**Review by risdenk — CHANGES_REQUESTED** [review]
I left a comment on https://github.com/apache/lucene/pull/12266 since Apache Lucene and Solr have a very similar build process. The same changes should be made here. It would be good to focus on Apache Lucene first and then if that gets merged easy to make the same changes here.

**Comment by risdenk** [comment]
So is this change actually necessary? @clayburn at least from Apache Jenkins jobs it looks like build scans are automagically being published?

https://ci-builds.apache.org/job/Solr/job/Solr-Check-main/ -> https://ci-builds.apache.org/job/Solr/job/Solr-Check-main/6911/ -> https://ci-builds.apache.org/job/Solr/job/Solr-Check-main/6911/buildScans/ -> https://ge.apache.org/s/446qtyw65lwgw

this applies it looks like to all Apache Solr jobs at least without this change. Same goes for Lucene.

**Comment by runningcode** [comment]
@risdenk Good question. This adds the Gradle Enterprise for all builds, not just those executed via Jenkins. This means that local development builds will also produce build scans when an access key is present.

**Comment by clayburn** [comment]
I'm going to temporarily close this one as the [lucene PR](https://github.com/apache/lucene/pull/12293) undergoes review. I'll reopen once that is done with changes matching those changes.

**Comment by dsmiley** [comment]
Replaced by #2042

**Pull request closed without merging**
