### PR TITLE
Admin UI: fixed node list display bug caused by different hostname with same front part

### PR DESCRIPTION
**Pull request by hgdharold**
# Description
old code:
```// Checks if this node is the first (alphabetically) for a given host. Used to decide rowspan in table
  $scope.isFirstNodeForHost = function(node) {
    var hostName = node.split(":")[0]; 
    var nodesInHost = $scope.filteredNodes.filter(function (node) {
      return node.startsWith(hostName);
    });
    return nodesInHost[0] === node;
  };
```
hostname like `server-1`, `server-10`, this code will cause the node list to be displayed incorrectly

# Solution
```
  $scope.isFirstNodeForHost = function(node) {
    var hostName = node.split(":")[0]; 
    var nodesInHost = $scope.filteredNodes.filter(function (node) {
      return node.split(":")[0] === hostName;
    });
    return nodesInHost[0] === node;
  };
```

### CODE REVIEW

**Comment by cpoerschke** [comment]
Thanks for this contribution!

The `Gradle Precommit` CI failure looks unrelated and pre-existing and @epugh is fixing it in #2450 pull request. Just FYI.

**Comment by epugh** [comment]
I'd like to merge this, however can you give me some concrete examples of different hostname with same front part?   I'm just not totally sure how to test the fix ;-).  @cpoerschke not sure if you have a strategy to test it?

**Comment by cpoerschke** [comment]
> ... @cpoerschke not sure if you have a strategy to test it?

No, I don't, sorry.

**Comment by epugh** [comment]
@hgdharold  how would you like to be credited in the `solr/CHANGES.txt` file?

**Comment by epugh** [comment]
Due to challenges pushing changes, replacing this one with https://github.com/apache/solr/pull/2475.

**Pull request closed without merging**
