### PR TITLE
SOLR-15876: Only disable error-prone, if it is running as an alternate runtime JVM

### PR DESCRIPTION
**Pull request by uschindler**
see https://issues.apache.org/jira/browse/SOLR-15876

### CODE REVIEW

**Comment by uschindler** [comment]
Hi @dweiss, could you have a quick look? Due to the new spotless options we can run errorprone in Gradle also with JDK 16+, it only fails to work when javac gets forked due to alternative runtime.

I will apply the same hack to Lucene once we are on JDK-17, otherwise errorprone would not even run on nightly Jenkins runs anymore. This enables errorprone, when it runs *inside* the Gradle JVM. If you have a better idea without the rootProject extra property, tell me! :-)

**Comment by uschindler** [comment]
Works fine!

With alternate toolchain:
```
$ gradlew clean :solr:core:jar
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :altJvmWarning
NOTE: Alternative java toolchain will be used for compilation and tests:
  Project will use 18 (OpenJDK 18-ea+26-1787, home at: C:\Program Files\Java\jdk-18)
  Gradle runs with 11 (Eclipse Adoptium JDK 11.0.13+8, home at: C:\Program Files\Java\jdk-11.0.13)

> Task :errorProneSkipped
WARNING: errorprone disabled (won't work with JDK 18 if used as alternate runtime JVM)

> Task :solr:solrj:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

With plain JDK-17 as JAVA_HOME:
```
C:\Users\Uwe Schindler\Projects\lucene\solr>java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

C:\Users\Uwe Schindler\Projects\lucene\solr>gradlew clean :solr:solrj:jar
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
<===========--> 86% EXECUTING [33s]
> IDLE
> IDLE
> :solr:solrj:compileJava
```

**Comment by dweiss** [comment]
This looks ok to me. An alternative would be to pass options that would open these modules to JavaCompile - see the task's options and fork options - these can be used to always force external compiler and pass module options there?

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.ForkOptions.html

**Comment by uschindler** [comment]
> This looks ok to me. An alternative would be to pass options that would open these modules to JavaCompile - see the task's options and fork options - these can be used to always force external compiler and pass module options there?
> 
> https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.ForkOptions.html

I was thinking about this, too. But the additional complexity wasn't worth to do this. If you run with alternate JVM, I don't think you require errorprone.

We can tune this. But then we have to put all those module-opens in 2 different files and I am sure somebody forgets to update them.

Also: I am not sure if hooking into javac internal Apis works with possible future JDK versions.

**Pull request merged**
