### PR TITLE
SOLR-15446: Fix three off-by-one ArrayList initialCapacity choices when calling ZooKeeper.multi API.

### PR DESCRIPTION
**Pull request by cpoerschke**
https://issues.apache.org/jira/browse/SOLR-15446 created but no `solr/CHANGES.txt` entry planned for this small change.

### CODE REVIEW

**Comment by HoustonPutman** [comment]
Not directly related to the PR, but is there a reason for using ZooKeeper.multi when only issuing 1 command?

**Comment by cpoerschke** [comment]
> Not directly related to the PR, but is there a reason for using ZooKeeper.multi when only issuing 1 command?

Interesting question! From a quick look at the ZooKeeper docs I could see no reasons for preferring `multi` over the single command equivalent.

**Review by risdenk — APPROVED** [review]

**Comment by risdenk** [comment]
Another idea might be `List.of()` which would avoid having to even keep track of the initial capacity at all?

**Comment by risdenk** [comment]
FWIW PR #1232 addressed a part of this. I'll resolve the conflict and use List.of since that makes it so we don't even need to deal w/ sizes.

**Review by risdenk — APPROVED** [review]

**Pull request merged**
