### PR TITLE
SOLR-7642: add opt-in support to create ZK chroot on startup

### PR DESCRIPTION
**Pull request by cpoerschke**
https://issues.apache.org/jira/browse/SOLR-7642

Converting the patches from Steve Molloy and Isabelle Giguere into a pull request.

### CODE REVIEW

**Comment by HoustonPutman** [comment]
Can we add this add an optional Env Var as well?

**Comment by epugh** [comment]
This will make life easier when I run mutliple versions of Solr on a single ZK cluster!    Out of curiosity, would you ever NOT want it to be autocreated?    Is adding a switch that opts in the right way?   What if it was a switch to opt out of autocreate?

**Comment by cpoerschke** [comment]
> Can we add this add an optional Env Var as well?

Replied on [jira](https://issues.apache.org/jira/browse/SOLR-7642?focusedCommentId=17417721&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17417721) where there was already other non-code discussion history.

**Comment by cpoerschke** [comment]
> This will make life easier when I run mutliple versions of Solr on a single ZK cluster! Out of curiosity, would you ever NOT want it to be autocreated? Is adding a switch that opts in the right way? What if it was a switch to opt out of autocreate?

Replied on [jira](https://issues.apache.org/jira/browse/SOLR-7642?focusedCommentId=17417721&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17417721) where there was already other non-code discussion history.

**Review by HoustonPutman — APPROVED** [review]
Looks great to me!

Should be easy to backport in case we do 8.11

**Pull request merged**
