### PR TITLE
SOLR-16473: Fix race condition in shard split when a sub-shard is put in recovery state.

### PR DESCRIPTION
**Pull request by bruno-roustant**

### CODE REVIEW

**Comment by bruno-roustant** [comment]
@andyvuong I created the Jira issue and this PR for your fix.

**Review by dsmiley — APPROVED** [review]
We've had this change locally for a long while now and it's been safe/fine.

**Comment by risdenk** [comment]
Is this at all related to https://github.com/apache/lucene-solr/pull/1277 and https://issues.apache.org/jira/browse/SOLR-14278

it looks like this is missing a test

**Comment by dsmiley** [comment]
The bug was found/fixed locally in May of 2020.  I see that Yonik's SOLR-14278 is a test for shard split errors (not committed; seems rather WIP/DRAFT).  I took the old patch and updated it to apply, and the test seems to fail for inexplicable reasons about not being able to connect; it didn't get to the point where it makes a final assertion.  So I don't know; maybe this bug fix helps.  I don't think we need a test to reproduce a race condition to gate committing improvements.  It'd be nice but we don't have one.

**Review by risdenk — APPROVED** [review]

**Pull request merged**
